### ISSUE TITLE
Only Blackscreen loading Molot Compressor

### ISSUE THREAD

**Issue by hfte** [osxmidi/LinVst#1]
First of all: Nice Work!

I tried to load Molot Compressor v0.3.1b 64-bit under
Wine 2.5 and only get a blackscreen-window.

```fixme:heap:RtlSetHeapInformation 0x230000 0 0x22f3a0 4 stub
fixme:d2d:d2d_factory_init Ignoring factory type 0x1.
fixme:win:EnumDisplayDevicesW ((null),0,0x22e8c0,0x00000000), stub!
fixme:dxgi:DXGID3D10CreateDevice Ignoring flags 0x20.
fixme:dxgi:dxgi_check_feature_level_support Ignoring adapter type.
fixme:winediag:dxgi_check_feature_level_support None of the requested D3D feature levels is supported on this GPU with the current shader backend.
```

Disabling GPU Acceleration was mentioned, but i'm not shure how to do that. Any Ideas?

Greetings!

**Comment by osxmidi** [comment]
Hi.

Seems like it's a Wine D3D error that's probably due to your video system/driver not being able to handle Wine's DirectX 10 requirements.

When that happens, screen errors can happen.

Maybe some Wine based game sites might have some workarounds for your particular video setup.

**Comment by hfte** [comment]
Thanks, haven't tried your latest edits, but using the prorietary nvidia driver with its own libgl implemantations solved it before.
