### ISSUE TITLE
Crash when I attempt to run the plugin

### ISSUE THREAD

**Issue by maxxatgit** [osxmidi/LinVst#101]
I'm new to running wine so I don't know much about it. I have been using Linux for a while, I know how to use the compiler, and I'm comfortable with the command line.

I'm running 64 bit Ubuntu 16.4, Wine 4.0.1 stable on a quad core -7. I'm pretty sure I installed wine from system packages. 

I don't know about winetricks or even where to begin fixing this, so please point me in the right direction. 

I've tried LinVST 2.65 from both Reaper 5.980 and Bitwig 2.5. I get this error when I try to open the Aurora FM VST in Bitwig (I got the same error when Reaper scanned the dll/svt plugin directory):

the program lin-vst-servertrack has encountered a serious problem and needs to close

Here is the stacktrace:
 Unhandled exception: page fault on read access to 0x00000008, invalid program stack in 64-bit code (0x0000000180051edb).
Register dump:
 rip:0000000180051edb rsp:000000000023e580 rbp:000000000023e950 eflags:00010246 (  R- --  I  Z- -P- )
 rax:0000000180038000 rbx:0000000000000000 rcx:0000000000000000 rdx:0000000180038000
 rsi:00007f0c27f87015 rdi:0000000000000000  r8:0000000180000000  r9:0000000000000000 r10:0000000000000000
 r11:0000000000000000 r12:000000000023e710 r13:000000007c928a70 r14:000000000023eaa0 r15:000000000023eae0
Stack dump:
0x000000000023e580:  0000000000000000 00000000000004ff
0x000000000023e590:  000000000023e6d0 0000000000000000
0x000000000023e5a0:  0000000000380060 0000000180049e15
0x000000000023e5b0:  00000000000ad670 00007f0c2479b77d
0x000000000023e5c0:  000000000023e6c0 000000007b45bd55
0x000000000023e5d0:  0000000000380060 000000018003820f
0x000000000023e5e0:  0000000000000004 000000000023e7e4
0x000000000023e5f0:  0000001ba32205cf 2020202020202020
0x000000000023e600:  0000000000000000 000000018002961c
0x000000000023e610:  0000000000000000 33556a515a623830
0x000000000023e620:  4e31694873724e45 000000007bca25ef
0x000000000023e630:  0000000000000000 000000018002a4f6
Backtrace:
=>0 0x0000000180051edb EntryPoint+0xffe06283() in aurora fm (0x000000000023e950)
  1 0x0000000180049e15 EntryPoint+0xffdfe1bc() in aurora fm (0x000000000023e950)
  2 0x000000018003820f EntryPoint+0xffdec5b6() in aurora fm (0x000000000023e950)
  3 0x000000018002961c EntryPoint+0xffddd9c3() in aurora fm (0x000000000023e950)
  4 0x000000018002a4f6 EntryPoint+0xffdde89d() in aurora fm (0x000000000023e950)
  5 0x000000018002929c EntryPoint+0xffddd643() in aurora fm (0x000000000023e950)
  6 0x00007f0c2c5a6d1c _ZN15RemoteVSTServer10EffectOpenEv+0xcb() in lin-vst-servertrack (0x000000000023e950)
  7 0x00007f0c2c5aca81 _ZN18RemotePluginServer21dispatchControlEventsEv+0xb0() in lin-vst-servertrack (0x000000000000000b)
  8 0x00007f0c2c5ae050 _ZN18RemotePluginServer15dispatchControlEi+0x3f() in lin-vst-servertrack (0x00007f0c2c5b47d0)
  9 0x00007f0c2c5aa5b8 WinMain+0x1087() in lin-vst-servertrack (0x00007f0c2c5b47d0)
  10 0x00007f0c2c5a5375 main+0xc4() in lin-vst-servertrack (0x0000000000000001)
  11 0x00007f0c2c5aef33 __wine_spec_exe_entry+0x82() in lin-vst-servertrack (0x000000000023fdd0)
  12 0x000000007b47cda8 PowerClearRequest+0x16a7() in kernel32 (0x000000000023ffd0)
0x0000000180051edb EntryPoint+0xffe06283 in aurora fm: cmpl	%ecx,0x0000000000000008(%rbx)
Modules:
Module	Address					Debug info	Name (117 modules)
ELF	        7ac00000-        7aca1000	Deferred        riched20<elf>
  \-PE	        7ac10000-        7aca1000	\               riched20
ELF	        7b400000-        7b82a000	Dwarf           kernel32<elf>
  \-PE	        7b420000-        7b82a000	\               kernel32
ELF	        7bc00000-        7bd29000	Deferred        ntdll<elf>
  \-PE	        7bc20000-        7bd29000	\               ntdll
ELF	        7c000000-        7c004000	Deferred        <wine-loader>
PE	       180000000-       1804fa000	Export          aurora fm
ELF	    7f0c22550000-    7f0c2259e000	Deferred        usp10<elf>
  \-PE	    7f0c22560000-    7f0c2259e000	\               usp10
ELF	    7f0c2259e000-    7f0c226fc000	Deferred        comctl32<elf>
  \-PE	    7f0c225b0000-    7f0c226fc000	\               comctl32
ELF	    7f0c22b84000-    7f0c22d8a000	Deferred        libxfixes.so.3
ELF	    7f0c22d8a000-    7f0c22f94000	Deferred        libxcursor.so.1
ELF	    7f0c22f94000-    7f0c231a4000	Deferred        libxi.so.6
ELF	    7f0c231a4000-    7f0c233a7000	Deferred        libxcomposite.so.1
ELF	    7f0c233a7000-    7f0c235b2000	Deferred        libxrandr.so.2
ELF	    7f0c235b2000-    7f0c237bc000	Deferred        libxrender.so.1
ELF	    7f0c237bc000-    7f0c239c2000	Deferred        libxxf86vm.so.1
ELF	    7f0c239c2000-    7f0c23bc5000	Deferred        libxinerama.so.1
ELF	    7f0c23bc5000-    7f0c23dcb000	Deferred        libxdmcp.so.6
ELF	    7f0c23dcb000-    7f0c23fcf000	Deferred        libxau.so.6
ELF	    7f0c23fcf000-    7f0c241f1000	Deferred        libxcb.so.1
ELF	    7f0c241f1000-    7f0c2452b000	Deferred        libx11.so.6
ELF	    7f0c2452b000-    7f0c2473d000	Deferred        libxext.so.6
ELF	    7f0c2476f000-    7f0c24816000	Deferred        winex11<elf>
  \-PE	    7f0c24780000-    7f0c24816000	\               winex11
ELF	    7f0c24816000-    7f0c2482b000	Deferred        api-ms-win-core-localization-l1-2-1<elf>
  \-PE	    7f0c24820000-    7f0c2482b000	\               api-ms-win-core-localization-l1-2-1
ELF	    7f0c2482b000-    7f0c24a3f000	Deferred        libgpg-error.so.0
ELF	    7f0c24a3f000-    7f0c24caf000	Deferred        libpcre.so.3
ELF	    7f0c24caf000-    7f0c24f90000	Deferred        libgcrypt.so.20
ELF	    7f0c24f90000-    7f0c251b2000	Deferred        liblzma.so.5
ELF	    7f0c251b2000-    7f0c253d4000	Deferred        libselinux.so.1
ELF	    7f0c253d4000-    7f0c25459000	Deferred        libsystemd.so.0
ELF	    7f0c25459000-    7f0c25661000	Deferred        libffi.so.6
ELF	    7f0c25661000-    7f0c2587c000	Deferred        libresolv.so.2
ELF	    7f0c2587c000-    7f0c25a80000	Deferred        libkeyutils.so.1
ELF	    7f0c25a80000-    7f0c25ccc000	Deferred        libdbus-1.so.3
ELF	    7f0c25ccc000-    7f0c25f4c000	Deferred        libgmp.so.10
ELF	    7f0c25f4c000-    7f0c2617f000	Deferred        libhogweed.so.4
ELF	    7f0c2617f000-    7f0c263b5000	Deferred        libnettle.so.6
ELF	    7f0c263b5000-    7f0c265c8000	Deferred        libtasn1.so.6
ELF	    7f0c265c8000-    7f0c267fb000	Deferred        libidn.so.11
ELF	    7f0c267fb000-    7f0c26a5f000	Deferred        libp11-kit.so.0
ELF	    7f0c26a5f000-    7f0c26c6a000	Deferred        libkrb5support.so.0
ELF	    7f0c26c6a000-    7f0c26e6e000	Deferred        libcom_err.so.2
ELF	    7f0c26e6e000-    7f0c2709d000	Deferred        libk5crypto.so.3
ELF	    7f0c2709d000-    7f0c2736f000	Deferred        libkrb5.so.3
ELF	    7f0c2736f000-    7f0c27580000	Deferred        libavahi-client.so.3
ELF	    7f0c27580000-    7f0c2778c000	Deferred        libavahi-common.so.3
ELF	    7f0c2778c000-    7f0c27abc000	Deferred        libgnutls.so.30
ELF	    7f0c27abc000-    7f0c27d06000	Deferred        libgssapi_krb5.so.2
ELF	    7f0c27d06000-    7f0c27f86000	Deferred        libcups.so.2
ELF	    7f0c27f8f000-    7f0c27fa3000	Deferred        api-ms-win-core-fibers-l1-1-1<elf>
  \-PE	    7f0c27f90000-    7f0c27fa3000	\               api-ms-win-core-fibers-l1-1-1
ELF	    7f0c27fa3000-    7f0c27fb8000	Deferred        api-ms-win-core-synch-l1-2-0<elf>
  \-PE	    7f0c27fb0000-    7f0c27fb8000	\               api-ms-win-core-synch-l1-2-0
ELF	    7f0c27fb8000-    7f0c27fe7000	Deferred        msacm32<elf>
  \-PE	    7f0c27fc0000-    7f0c27fe7000	\               msacm32
ELF	    7f0c27fe7000-    7f0c280ae000	Deferred        winmm<elf>
  \-PE	    7f0c27ff0000-    7f0c280ae000	\               winmm
ELF	    7f0c280ae000-    7f0c28118000	Deferred        oleacc<elf>
  \-PE	    7f0c280c0000-    7f0c28118000	\               oleacc
ELF	    7f0c28118000-    7f0c2820a000	Deferred        crypt32<elf>
  \-PE	    7f0c28130000-    7f0c2820a000	\               crypt32
ELF	    7f0c2820a000-    7f0c2822e000	Deferred        bcrypt<elf>
  \-PE	    7f0c28210000-    7f0c2822e000	\               bcrypt
ELF	    7f0c2822e000-    7f0c282e8000	Deferred        gdiplus<elf>
  \-PE	    7f0c28240000-    7f0c282e8000	\               gdiplus
ELF	    7f0c282e8000-    7f0c2846e000	Deferred        oleaut32<elf>
  \-PE	    7f0c28310000-    7f0c2846e000	\               oleaut32
ELF	    7f0c2846e000-    7f0c284ad000	Deferred        uxtheme<elf>
  \-PE	    7f0c28480000-    7f0c284ad000	\               uxtheme
ELF	    7f0c284ad000-    7f0c2854e000	Deferred        rpcrt4<elf>
  \-PE	    7f0c284c0000-    7f0c2854e000	\               rpcrt4
ELF	    7f0c2854e000-    7f0c28706000	Deferred        ole32<elf>
  \-PE	    7f0c28570000-    7f0c28706000	\               ole32
ELF	    7f0c28706000-    7f0c28730000	Deferred        shcore<elf>
  \-PE	    7f0c28710000-    7f0c28730000	\               shcore
ELF	    7f0c28730000-    7f0c287bc000	Deferred        shlwapi<elf>
  \-PE	    7f0c28740000-    7f0c287bc000	\               shlwapi
ELF	    7f0c287bc000-    7f0c291cf000	Deferred        shell32<elf>
  \-PE	    7f0c287e0000-    7f0c291cf000	\               shell32
ELF	    7f0c291cf000-    7f0c29219000	Deferred        winspool<elf>
  \-PE	    7f0c291e0000-    7f0c29219000	\               winspool
ELF	    7f0c29219000-    7f0c2922d000	Deferred        msimg32<elf>
  \-PE	    7f0c29220000-    7f0c2922d000	\               msimg32
ELF	    7f0c2932d000-    7f0c29356000	Deferred        imm32<elf>
  \-PE	    7f0c29330000-    7f0c29356000	\               imm32
ELF	    7f0c2948d000-    7f0c296b6000	Deferred        libexpat.so.1
ELF	    7f0c296b6000-    7f0c298f9000	Deferred        libfontconfig.so.1
ELF	    7f0c298f9000-    7f0c29b1e000	Deferred        libpng12.so.0
ELF	    7f0c29b1e000-    7f0c29d38000	Deferred        libz.so.1
ELF	    7f0c29d38000-    7f0c29fe2000	Deferred        libfreetype.so.6
ELF	    7f0c2a014000-    7f0c2a0ad000	Deferred        advapi32<elf>
  \-PE	    7f0c2a030000-    7f0c2a0ad000	\               advapi32
ELF	    7f0c2a0ad000-    7f0c2a230000	Deferred        gdi32<elf>
  \-PE	    7f0c2a0c0000-    7f0c2a230000	\               gdi32
ELF	    7f0c2a230000-    7f0c2a4a1000	Deferred        user32<elf>
  \-PE	    7f0c2a250000-    7f0c2a4a1000	\               user32
ELF	    7f0c2a923000-    7f0c2ab2b000	Deferred        librt.so.1
ELF	    7f0c2ab42000-    7f0c2ab5d000	Deferred        version<elf>
  \-PE	    7f0c2ab50000-    7f0c2ab5d000	\               version
ELF	    7f0c2ab5d000-    7f0c2ad6f000	Deferred        libnss_files.so.2
ELF	    7f0c2ad6f000-    7f0c2af7b000	Deferred        libnss_nis.so.2
ELF	    7f0c2af7b000-    7f0c2b194000	Deferred        libnsl.so.1
ELF	    7f0c2b194000-    7f0c2b39d000	Deferred        libnss_compat.so.2
ELF	    7f0c2b875000-    7f0c2ba8b000	Deferred        libgcc_s.so.1
ELF	    7f0c2ba8b000-    7f0c2bd94000	Deferred        libm.so.6
ELF	    7f0c2bd97000-    7f0c2bf9b000	Deferred        libdl.so.2
ELF	    7f0c2bf9c000-    7f0c2c366000	Deferred        libc.so.6
ELF	    7f0c2c366000-    7f0c2c583000	Deferred        libpthread.so.0
ELF	    7f0c2c58f000-    7f0c2c5b5000	Dwarf           lin-vst-servertrack<elf>
  \-PE	    7f0c2c5a0000-    7f0c2c5b5000	\               lin-vst-servertrack
ELF	    7f0c2c5b5000-    7f0c2c95b000	Dwarf           libwine.so.1
ELF	    7f0c2c95c000-    7f0c2cb84000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000020    0
	0000001b    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	00000018    0
	00000017    0
	00000016    0
	00000012    0
00000019 plugplay.exe
	0000001d    0
	0000001c    0
	0000001a    0
0000001e winedevice.exe
	00000025    0
	00000022    0
	00000021    0
	0000001f    0
00000023 explorer.exe
	0000002a    0
	00000029    0
	00000028    0
	00000024    0
0000002b (D) Z:\usr\bin\lin-vst-servertrack.exe
	0000002f    0
	0000002e    0
	0000002d    0
	0000002c    0 <==
System information:
    Wine build: wine-4.0.1
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 4.4.0-159-generic

**Comment by osxmidi** [comment]
It seems that Wine can't handle that plugin.
