### ISSUE TITLE
LinVst 2.66 many Xruns

### ISSUE THREAD

**Issue by clusterx** [osxmidi/LinVst#108]
Hi osxmidi,
I see man xruns in reaper when opening a VST plugin w/ LinVst 2.66, also everything works maybe a little slower as before also while reaper starts.

**Comment by keybreak** [comment]
Good one!

Tested some of plugins on Renoise as well - i agree, some (but not all) plugins have periodic xruns, and 2.65 doesn't.

**Comment by clusterx** [comment]
Thanks for your review! I am using wine-staging 4.15 bionic on KDE Neon 5.16 (4.18.0-25-lowlatency) maybe it's due to the wine version?
I see this issue w/ all WIN VSTs, the xruns shown in cadence increase each time using another.
wine details (screenshot)
[https://i.ibb.co/bdYHqwF/Screenshot-20190913-095657.png](url)

**Comment by keybreak** [comment]
@osxmidi 
Maybe it have to do with those changes?

**remotepluginserver.cpp**
![image](https://user-images.githubusercontent.com/47599989/64905692-c9eab300-d6e4-11e9-8d8d-d3edf603d41b.png)

**remotepluginclient.cpp**
![image](https://user-images.githubusercontent.com/47599989/64905698-d838cf00-d6e4-11e9-9521-1ea07f815344.png)

**Comment by clusterx** [comment]
sorry I forgot to mention a few details, I'm using the LinVst-2.66-Debian-Stretch.zip package w/o the *.cpp files inside. I did the installation as follows
`cp lin-vst-servertrack.exe /usr/bin
cp lin-vst-servertrack.exe.so /usr/bin
cp lin-vst-servertrack32.exe /usr/bin
cp lin-vst-servertrack32.exe.so /usr/bin
chmod +x /usr/bin/lin-vst-servertrack.exe
chmod +x /usr/bin/lin-vst-servertrack32.exe`

**Comment by osxmidi** [comment]
That's the version number.

I don't care what the indentation looks like.

**Comment by osxmidi** [comment]
As I've said, there is really not much difference between 2.66 and 2.65, only some name display things.

**Comment by keybreak** [comment]
> I don't care what the indentation looks like.

lol me too, just mentioned it because i know there are some programming languages that do care about indentation to the point of it causes errors...
So thought maybe it's the cause.

> As I've said, there is really not much difference between 2.66 and 2.65, only some name display things.

I know...But there must be something that caused it, doubt it's this display stuff

**Comment by clusterx** [comment]
what would be the lowest version number of linVST which I can use for KDE neon 5.16 (ubuntu 4.18.0-25-lowlatency)?

**Comment by clusterx** [comment]
hmm, strange ... seems this happens only w/ reaper ... when using the same VSTs in audacity, no xruns occur or shown in cadence.
