### ISSUE TITLE
Allow converter to descend in to subdirectories

### ISSUE THREAD

**Issue by spectromas** [osxmidi/LinVst#11]
The batch tool is very handy but when there are directories inside your main vst directory it becomes pretty tedious. 

Another suggestion would be for the gui tool to not be a once-only operation, at the moment if you choose a directory and convert it you have to close the tool and reopen again to convert another directory. It would be great if you could run the convert, change the target directory and pretty convert again.

**Comment by osxmidi** [comment]
Good idea.

I've done a linvstconverttree version that does it.

**Comment by spectromas** [comment]
Thanks, I finally got around to testing this and it works perfectly.
