### ISSUE TITLE
Request: access to old releases

### ISSUE THREAD

**Issue by lucmp** [osxmidi/LinVst#111]
I was using linvst 2.43. Everything worked fine.

I upgraded to 2.66. Now some plugins crash when I click them to see their GUI then hide them back. This one, for example:

http://www.vst4free.com/free_vst.php?plugin=Midinaut_Drum_Station&id=1676

All of Necromare's plugins stopped working too.

http://bigcatinstruments.blogspot.com/2016/03/necromare-vsts.html 

I wish I could go back to 2.43, but I made the mistake of deleting it. Or even better, the latest version I can find that won't cause that problem. I can only go back as far as 2.54, but that one is causing the problem, too.

**Comment by osxmidi** [comment]
[LinVst-2.4.3-Debian-Stretch.zip](https://github.com/osxmidi/LinVst/files/3612444/LinVst-2.4.3-Debian-Stretch.zip)
[LinVst-master.zip](https://github.com/osxmidi/LinVst/files/3612445/LinVst-master.zip)

**Comment by lucmp** [comment]
Thank you.

The first link works. The second doesn't. I just get an XML file.

Can I have access to other 2.x releases?

**Comment by osxmidi** [comment]
Interesting, I don't get an xml file.
I've only got  LinVst 2.41


[LinVst-2.4.1-Debian-Stretch.zip](https://github.com/osxmidi/LinVst/files/3612678/LinVst-2.4.1-Debian-Stretch.zip)
[LinVst-master.zip](https://github.com/osxmidi/LinVst/files/3612679/LinVst-master.zip)

**Comment by lucmp** [comment]
![linvst-xml-x](https://user-images.githubusercontent.com/2882969/64910320-631cc800-d6eb-11e9-9899-efe895d03b85.png)
I get this. But that's OK. I appreciate your attention.

I just think that 2.43 works better than latest and can only wonder what changes have been put into it between one and the other.

Thank you again for the file. It's going to help a lot.

**Comment by lucmp** [comment]
Sorry, I just realized I had some kind of content blocker active that treats that page as suspicious. I can access all files now. Thank you again.
