### ISSUE TITLE
Feature Request - Do not require root permissions

### ISSUE THREAD

**Issue by ChuckDaniels87** [osxmidi/LinVst#112]
I think that not requiring root permissions would be a very interesting addition to this project, for both development and final end-user usage.

I am still trying to understand the code flow but I have noticed that `/usr/bin/lin-vst*` are hardcoded in [`remotevstclient.cpp`](https://github.com/osxmidi/LinVst/blob/63a4fbe62d92be2d8fad8d0c98d390178147a3ec/remotevstclient.cpp#L219-L541). The logic to obtain the correct path for `LinVstName` could be included in another place (`path.cpp` for example) in order to refactor and simplify `remotevstclient.cpp`. Finally,  I think that `execlp()` already looks for files includes in $PATH as far as it is described [here](https://stackoverflow.com/a/21559499/3191211). 

This way LinVst can be used without root permissions but maybe I am missing some reason here that you could clarify.

If you are interested, I would like to contribute to this project and try to handle this issue.

**Comment by osxmidi** [comment]
I think I needed to hardcode the path because of how Wine starts the server.

The execlp() already looks for files includes in $PATH might work for linux things but I couldn't get it working with Wine.

**Comment by ChuckDaniels87** [comment]
First, sorry for the late response. I would like to take a deeper look at this issue if this is OK for you. I don't know if I will find a solution but I will do my best.

In addition, I was wondering if you are interested in refactoring the code related to this part, that is mostly macro-based. In any case, I would do that in a separate PR.

**Comment by osxmidi** [comment]
If you come up with anything then I'll look at it and test it out.

**Comment by osxmidi** [comment]
I'll test it out soon.
