### ISSUE TITLE
[VST] Camelcrusher 

### ISSUE THREAD

**Issue by Jgjot-Singh** [osxmidi/LinVst#113]
I've had previous installs of wine and linvst where this plugin worked vanilla without any modifications or overrides; but now trying to install on a new machine(running Manjaro with realtime kernel), and am getting the following error when trying to load the plugin via Bitwig:

/home/user/.wine/drive_c/Program Files/VSTPlugins/CamelCrusher.so

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Communications error with plugin host process
exit code:1
stdout:
PluginHost: Reading VST 2.4 plugin metadata for /home/user/.wine/drive_c/Program Files/VSTPlugins/CamelCrusher.so

stderr:
mlock fail1: Cannot allocate memory
mlock fail2: Cannot allocate memory
mlock fail3: Cannot allocate memory
LinVst Error: lin-vst-server not found or vst dll load timeout or LinVst version mismatch
X connection to :0.0 broken (explicit kill or server shutdown).

-------------------------------------------------------------------

**Comment by osxmidi** [comment]
From the errors, it seems like lin-vst-servertrack.exe and  lin-vst-servertrack.exe can't be found in /usr/bin

Try to reinstall LinVst.

**Comment by keybreak** [comment]
@osxmidi 
Just tested both **CamelCrusher v1.0.1** and **CamelPhat v3.50.1.629** are working perfect on Manjaro with LinVST, i think you can safely close this issue :wink: 

@Jgjot-Singh 
If you still have problems, please use similar environments as here https://github.com/keybreak/linux-vst-compatibility-list (x86_64 host / Wine 4.15-staging amd64 or above / Winetricks defaults), you should be fine, although i think you just incorrectly installed LinVST as mentioned above.
