### ISSUE TITLE
[VST] Cytomic The Glue v1.3.19 | Ringmod sound distortion

### ISSUE THREAD

**Issue by keybreak** [osxmidi/LinVst#114]
## Description

Once loaded all audio going through is in constant sound distortion, regardless of plugin settings (sounds a lot like ringmod).
[Bug demo.zip](https://github.com/osxmidi/LinVst/files/3671940/Bug.demo.zip)

That one is really weird, serious and looks like caused specifically by LinVST, because at first i though it was caused by Wine itself, or some options like oversampling, but no - it works fine bridged with Airwave...

I've tested licenced one, so not sure if demo behaves the same, but here it is: https://cytomic.com/glue

## Dependencies

**strings "The Glue 64.dll" | grep -i '.dll'**
```
dsound.dll
Shell32.dll
netapi32.dll
MAPI32.dll
kernel32.dll
user32.dll
SHCore.dll
avrt.dll
Wmvcore.dll
DWrite.dll
d2d1.dll
The Glue.dll
KERNEL32.dll
USER32.dll
GDI32.dll
COMDLG32.dll
ADVAPI32.dll
SHELL32.dll
ole32.dll
OLEAUT32.dll
WININET.dll
WS2_32.dll
SHLWAPI.dll
WINMM.dll
IMM32.dll
OPENGL32.dll
CRYPT32.dll
```

## Enviroments

```
OS: Manjaro 18.1.0 Juhraya
Kernel: x86_64 Linux 5.2.11-1-MANJARO
Shell: bash 5.0.9
DE: Deepin 15.11
WM: Deepin WM
Disk: 5,0T / 12T (46%)
dm: LightDM 
gcc v: 9.1.0 
tk: Qt 5.13.0 
driver: nvidia v: 435.21 
WINE: 4.15-staging amd64
```

## Winetricks
```
gdiplus
andale
arial
comicsans
courier
georgia
impact
times
trebuchet
verdana
webdings
corefonts
tahoma
wininet
fontsmooth=rgb
win7
```

**Comment by osxmidi** [comment]
I think it's a bug in the TheGlue_v1.3.19 version.

Bugs will get exposed or maybe not get exposed with different wrappers and real windows, so the results can vary.

TheGlue_v1.3.12 is ok.

**Comment by keybreak** [comment]
@osxmidi 
Thx, i'll try your fixes today to also check few other suspects to be affected!

Can you please explain those changes you've made in simple terms?
```
m_plugin->dispatcher(m_plugin, effSetBlockSize, 0, 1024, NULL, 0);
m_plugin->dispatcher(m_plugin, effSetSampleRate, 0, 0, NULL, (float)44100);
```
I'm little concerned that such specificity can probably cause problems in some others...

- Is it just telling that by default plugin on init wrapped plugin should use 1024 / 44100 (if not requested by the plugin itself)?

- If so, what will happen if, let's say host is in 256 / 96000 and plugin requests something like 512 / 48000?

**Comment by keybreak** [comment]
Update:
I've compiled from source, it's still same for me with TheGlue_v1.3.19

**Comment by osxmidi** [comment]
They are just default init values that should be overriden by the plugin.

I've gotten TheGlue_v1.3.19 working ok after adding the default init values to the code or maybe it was installing TheGlue_v1.3.12 and then installing TheGlue_v1.3.19 over the top of it, I don't know because I did both at the same time.

If it works because of installing TheGlue_v1.3.12 and then installing TheGlue_v1.3.19 over the top of it then that would point to one of it's config files as being the problem, which I can't do anything about.

**Comment by keybreak** [comment]
> or maybe it was installing TheGlue_v1.3.12 and then installing TheGlue_v1.3.19 over the top of it, I don't know because I did both at the same time.

I'll try 1.3.12 in isolated environment and report back to see if it's the case...
All that's weird stuff, still wonder why airwave is so ignorant to that problem

**Comment by keybreak** [comment]
@osxmidi 
Well, i was trying a lot of things lately to try repeat your success - one thing i'm sure this issue is not fixed because of your latest commits.

Basically i've managed to repeat it on VirtualBox VM by:
1. Installing & registering TheGlue_v1.3.19
2. Installing & registering TheGlue_v1.3.12 over it
3. Making new .so rescan - it worked

But i was unable to repeat it like 3 times i've tried....So it looks like you're right - there's something going on with this 1.3.19.

I was making a diff, nothing really sticks out elsewhere (registry .dll itslef etc), except this location:
**drive_c/users/x133/Application Data/Cytomic/The Glue**

**Settings.xml** in v1.3.19
```
<?xml version="1.0" encoding="UTF-8"?>

<Cytomic Product="The Glue" Version="1.3.19">
  <Settings Version="1.3.19">
    <Tuple Key="UiScale" Value="1"/>
    <Tuple Key="HdRender" Value="false"/>
    <Tuple Key="DetectSilence" Value="true"/>
    <Tuple Key="OverSampleRealtime" Value="x2"/>
    <Tuple Key="OverSampleRender" Value="x8"/>
    <Tuple Key="OverSampleTypeUp" Value="LinPhase"/>
    <Tuple Key="OverSampleTypeDn" Value="LinPhase"/>
    <Tuple Key="Au_HighResolutionParameters" Value="false"/>
    <Tuple Key="SingleProgram" Value="true"/>
    <Tuple Key="ExternalSidechain" Value="true"/>
    <Tuple Key="ForceDynamicLatency" Value="false"/>
    <Tuple Key="CurrentPath" Value="C:\users\x133\Application Data\Cytomic\The Glue\Presets\Factory Bank 1\Drum - open sounding bus comp.tgp"/>
  </Settings>
</Cytomic>
```


**Settings.xml** in v1.3.12
```
<?xml version="1.0" encoding="UTF-8"?>

<Cytomic Product="The Glue" Version="1.3.12">
  <Settings Version="1.3.12">
    <Tuple Key="SingleProgram" Value="true"/>
    <Tuple Key="ExternalSidechain" Value="true"/>
    <Tuple Key="CheckIo" Value="false"/>
    <Tuple Key="ShowPeakNeedle" Value="false"/>
    <Tuple Key="LockPad" Value="true"/>
    <Tuple Key="OverSampleRealtime" Value="x2"/>
    <Tuple Key="OverSampleRender" Value="x8"/>
    <Tuple Key="UiScale" Value="1"/>
    <Tuple Key="CurrentPath" Value="C:\users\x133\Application Data\Cytomic\The Glue\Presets\Factory Bank 1\Drum - full parallel.tgp"/>
  </Settings>
</Cytomic>
```

I suggest to just use v1.3.12 for now,  reverse those commits just in case and see what future versions will give us...Certainly it's one of a kind.

One thing i could assume probably it have something to do with piracy protection (maybe ringmod is their method to indicate unregistered version and it partially fails under Wine), although mine says that it's authorized successful without any issues...

**Comment by keybreak** [comment]
Btw, probably it's caused by this **advanced setting to allow dynamic updating of latency**
```
v1.3.18 (7 July 2017)
• New: reduced oversampler latency to use the lowest possible to support current realtime and render
oversampling amounts
• New: added advanced setting to allow dynamic updating of latency when switching between realtime
and render – note: very few hosts support this, so this setting has to be manually changed in the
settings.xml config file
• Fixed: uninitialised variable in linear phase oversampler
```

**Comment by osxmidi** [comment]
If you remove the matching /* and */ pairs from case audioMasterGetInputLatency: and case audioMasterGetOutputLatency: in lin-vst-server.cpp then it might have some effect.

Text gets commented out inside the /* and */ and the text has no effect on the code and so removing the /* and */  means that the text becomes part of the code.

If there is some code printing out hello in a terminal such as

printf("hello\n");

then it can be disabled or commented out by 

/*
printf("hello\n");

*/

which will stop hello being printed.

The /*  and */ are used together as pairs ie bookends or matching pairs and anything inside them is ignored by the compiler.

I'vet the input and output latency functions commented out and so removing the /*  and */  from them will enable them.

**Comment by keybreak** [comment]
By pairs you mean whole segments 1863-1876 and 1882-1895?

It's nice of you to explain code comment / uncomment, but for the future - i'm kinda familiar with general principles of coding and i can code some stuff myself, just don't know C / C++ specific things :smile: 

I did try that one, again same results - i was able to get rid of it on VirtualBox, but on real machine no...

_____

Then i've started to test and experiment with 1.3.19 itself again, turns out the reason is LinearPhase.

If you turn it off (it's on by default) and save as default - then this ringmod is gone on real machine as well...

![image](https://user-images.githubusercontent.com/47599989/66133772-e7ce7800-e5ff-11e9-9da5-bcb7087f7163.png)

Actually it's only enough to turn off Up Linear Phase in my case.
Btw what the hell is Up? When signal gets upsampled from host, i assume...Couldn't find it in Manual though (it's outdated against current plugin state).

I think we should ask this questions now:
- Is it only LinearPhase in this particular plugin, or LinVST can't handle it at all under some mysterious conditions? I can remember for now only https://www.ikmultimedia.com/products/trlinphaseeq/?pkey=t-racks-single-linear-phase-equalizerwhich has LinearPhase options, if you'll be faster than me to test it please report back (i will get to check this some time later, since i'm following my folder structure not to get lost in my plugs)

- Why same OS, same Kernel, same settings, same packages, same Wine, same Renoise, same plugin etc have this problem on real machine, and doesn't have on VirtualBox? To me that doesn't make any sense...There should be something else we're missing here.

_____________

Since i've just tested it with LinVst 2.7 to confirm my real machine and it works fine without LinearPhase, turns out this problem still has nothing to do with what we've tried out, so i think it's good idea to roll those changes down (to not accidentally mess anything else)
```
m_plugin->dispatcher(m_plugin, effSetBlockSize, 0, 1024, NULL, 0);
m_plugin->dispatcher(m_plugin, effSetSampleRate, 0, 0, NULL, (float)44100);
```
or uncommented blocks inside
```
audioMasterGetInputLatency
audioMasterGetOutputLatency
```

**Comment by keybreak** [comment]
P.S. If it matters - Up Intermediate Phase also rings, only Mininmum Phase don't..

**Comment by keybreak** [comment]
Just tested AudioD3CK KRUCZ v1.5 which also have LinearPhase option - it works without this problem, so looks like it's specifically Glue problem...

**Comment by keybreak** [comment]
Although, **DMG Audio Equality v1.31** when switching to **LinearPhase** immediately crashes :thinking: 
But reasons i'm not sure.

**Comment by keybreak** [comment]
Interesting, it's certainly Cytomic problem. **Cytomic The Drop v1.5.8** also have this exact problem, and exact same settings to avoid it:

![image](https://user-images.githubusercontent.com/47599989/66687685-2dd4ad00-ec8c-11e9-9105-cc250b9d366f.png)

**Comment by keybreak** [comment]
@osxmidi 
I don't think it's exclusively Cytomic thing now, found out just now from **Sonnox Oxford Elite collection native v1.0**:
```
Oxford SuprEsser
Oxford SuprEsser HR
Oxford SuprEsser LL
```

Those have exactly same ringmod effect, but you can't do anything about it, since it doesn't have any oversampling / Linear phase settings available..

**Comment by keybreak** [comment]
@osxmidi 
New entry for this issue from **Steinberg Mastering edition v1.5** bundle (i know, i know - old but gold):
```
ME Compressor
```

LinVst gave same heavy ringmod distortion + very high CPU (30% +), while testing with Ariwave on the other hand CPU was about 3-5% and no ringmod distortion.

If it's about Linear phase, then in this case you can't opt out of it...
