### ISSUE TITLE
Keyboard input issue

### ISSUE THREAD

**Issue by casual-droid** [osxmidi/LinVst#118]
Hello,

I have an issue with Linvst and keyboard input under Reaper in Linux.
VST bridging seems to work fine, but keyboard input doesn't.

I tested this behavior with 
- Reaper 5.983 (native linux)
- Linvst 2.7 embedded
- Latest winehq stable, devel and staging (stock, no overrides, etc ...)
- Ubuntu 16.04 (tried xfce too, and Linvst 2.66 at some point)
- Ubuntu 18.04 (fresh install, I tried kubuntu-desktop on it too, I also compiled Linvst from source at some point with no change)
- Free Voxengo plugins (and some other ones too (free / commercial), all behave the same).

I tried a lot of things but the only way to make it work reliably in all my tests was to uncheck "Allow the window manager to control the windows" in winecfg.
With this option unchecked, it is working fine, but the mouse, submenus and subwindows behavior is not good, I clearly understand why you suggest the option to be checked.

Anyone having success with keyboard input in bridged win VST's in Ubuntu?
Is this supposed to work with current Linvst version? (I suppose so, at least the Detailed Guide suggests it should work).
Is there some kind of configuration to do to make it work?
What distro / wine version is recommended to run linvst?

Thanks

**Comment by osxmidi** [comment]
It seems that something altered somewhere and keyboard window focus stopped working.

I've fixed it in the code, so if you can make it it should be ok.

The distro I tend to use is anything Debian based such as MX Linux or Debian etc, because if it works on Debian then it's probably going to work on other distros, so I develop Linst on Debian based systems.

**Comment by casual-droid** [comment]
Thanks a lot for the quick fix.
I did compile it and quickly tried with a couple plugins and it seems way better indeed.
I'll try it more deeply within the next few days and will close the issue after some more tests.

**Comment by casual-droid** [comment]
After some more testing, I can confirm this particular issue is now fixed.
For those looking for setup feedback: I have LinVst running in Ubuntu 18.04 w/ latest wine-stable in native reaper.
