### ISSUE TITLE
Remember linvst.so location

### ISSUE THREAD

**Issue by thomhoess** [osxmidi/LinVst#119]
What a great work you do with this piece of software! Thank you!

Would it be possible to somehow let the gui remember where the linvst.so is located? Or maybe specify it via something like linvstconvert --linvstpath "usr/..."?
I just find it really daunting that everytime I add or try a VST and convert it I have to work my way through the file manager to find the file again.

**Comment by keybreak** [comment]
You can use this script to manage, update, enable / disable (it's already included in LinVST source / master)
https://github.com/Goli4thus/linvstmanage

Very handy, i use it a lot myself :smile:
