### ISSUE TITLE
[VST / VSTi] Rob Papen all plugs are very long to open / close / load / save

### ISSUE THREAD

**Issue by keybreak** [osxmidi/LinVst#123]
### All Rob Papen plugins (except Predator 2)

https://keybreak.github.io/linux-vst-compatibility-list/
Search for Rob Papen to see whole list, in those it's extremely obvious, but there are a lot of plugins i've seen over my testing that have done similar thing, just faster.

## Description

It take very long time for those plugins to:
- Open
- Close
- Load project
- Save project

It happens, because for some reason some of plugins enumerate absolutely all values / presets and options available to plugin visually (doesn't matter if GUI opened or not), it looks like that:

https://i.imgur.com/1JRixWD.mp4

Such stuff depending on how big plugin is can go anywhere from 10 to 30 seconds, now imagine  you have 15 Rob Papen plugin project, to open it will multiply 30 seconds x 15...Doesn't look good :thinking: 

Looks like it's related to WM_PAINT bug too, if i get you correctly on it.

## Enviroments

```
 OS: Manjaro 18.1.2 Juhraya
 Kernel: x86_64 Linux 5.2.21-1-MANJARO
 Shell: bash 5.0.11
 DE: Deepin 15.11
 WM: Deepin WM
 dm: LightDM 
 gcc v: 9.2.0 
 tk: Qt 5.13.1 
 driver: nvidia v: 440.26 
 WINE: 4.19-staging amd64
```

## Winetricks

```
gdiplus
andale
arial
comicsans
courier
georgia
impact
times
trebuchet
verdana
webdings
corefonts
tahoma
wininet
fontsmooth=rgb
win7
mfc42
vcrun6
```

**Comment by keybreak** [comment]
Maybe it's only wine problem though, since Airwave also behaves same way, but not Windows..

**Comment by keybreak** [comment]
@osxmidi 
Why close? It's not solved...

And even if it's out of your control scope, since this is massive problem and affects not only Rob Papen but hundreds of other random plugins, can you please at least comment your thought on cause? :smile:

**Comment by robbert-vdh** [comment]
@keybreak 
There are a few similar issues caused by the way LinVst handles VST events. [This issue](https://github.com/osxmidi/LinVst/issues/105) for instance causes several plugins to completely freeze the Jack client when opening them. I'd try to fix it myself but I I'm having a hard time navigating through the code.
