### ISSUE TITLE
Focus on VST window when mouse hover (Reaper)

### ISSUE THREAD

**Issue by olivierlemoal** [osxmidi/LinVst#129]
I have a problem similar to https://github.com/osxmidi/LinVst/issues/27 since commit https://github.com/osxmidi/LinVst/commit/ce2537f8b7f2bf71ea5016af9a8f858c35840d93.
Using Reaper, every time the pointer is over the VST window, it gets focus.
Reverting https://github.com/osxmidi/LinVst/commit/ce2537f8b7f2bf71ea5016af9a8f858c35840d93 solves the issue.

**Comment by osxmidi** [comment]
Some want keyboard input and that's the only way it works. with the focus

Some don't want the focus.

So I think I'll leave it as a user option and mention it in the docs.
