### ISSUE TITLE
No issue. Just another companion application.

### ISSUE THREAD

**Issue by Goli4thus** [osxmidi/LinVst#132]
https://github.com/Goli4thus/linvstmanager

Any feedback is welcome.
Furthermore: Your TestVst utility was really helpful in making the _Vst scan_ feature a reality.

**Comment by osxmidi** [comment]
Thanks.

**Comment by Goli4thus** [comment]
Update:
Within the last 2 weeks quite a bit has happened and thanks to @keybreak 's vast collection of VSTs, lots of analysis, testing, ..., _LinVstManager_ has matured quite a bit in every regard (stability, features, performance).

One thing I want to make clear is that it's not my intention to take credit for LinVst in any way.
I simply saw a need in regards to user experience and usability and believed I could create something of value that would improve the situation for most users.

So far I don't know your thoughts on this whole project.
If you have some input, objection or vision on what such a graphical manager application should provide in regards to functionality, feel free to say so.

It seems to me that from here on out, the only thing left to do would be to let people know about the application (i.e. posting on Reaper forum).

**Comment by keybreak** [comment]
On my part:
I've done some really extensive testing and i can't imagine my life without this project - it's really well made and helpful with LinVST, thx for @Goli4thus to all his effort and bugfixes! :smiley: 

One thing i haven't personally tested though is VST3, coz i only focus myself on VST2, but i doubt there would be any problems.

**Comment by osxmidi** [comment]
> 
> 
> Update:
> Within the last 2 weeks quite a bit has happened and thanks to @keybreak 's vast collection of VSTs, lots of analysis, testing, ..., _LinVstManager_ has matured quite a bit in every regard (stability, features, performance).
> 
> One thing I want to make clear is that it's not my intention to take credit for LinVst in any way.
> I simply saw a need in regards to user experience and usability and believed I could create something of value that would improve the situation for most users.
> 
> So far I don't know your thoughts on this whole project.
> If you have some input, objection or vision on what such a graphical manager application should provide in regards to functionality, feel free to say so.
> 
> It seems to me that from here on out, the only thing left to do would be to let people know about the application (i.e. posting on Reaper forum).

Hi,

It's very useful.

I do know of people using it for more advanced management.

**Comment by Goli4thus** [comment]
> It's very useful.
> 
> I do know of people using it for more advanced management.

Thanks for the feedback!
