### ISSUE TITLE
An issue "lin-vst-servertrack.exe has encountered a serious problem"

### ISSUE THREAD

**Issue by conychang** [osxmidi/LinVst#135]
Thank you so much for developing! A lot of important VSTs for me are working very well.

Well, I'm trying to install iZotope Ozone Imager, and when I open it I got this message.
![Screenshot from 2020-03-07 00-16-00](https://user-images.githubusercontent.com/55735618/76108105-4cfa1f80-601d-11ea-8eb9-b8bfd528f31b.png)
I've checked detailed-guide in here and I only associated .so file with the main dll.
What's the problem with it?

* using Manjaro Linux, wine-staging

**Comment by osxmidi** [comment]
I don't think it works with Wine at the moment.

**Comment by conychang** [comment]
Humm thanks! For now, gonna close it.

**Comment by SaintJules** [comment]
I have the exact same setup as OP. I got that message whenever I added the wininet dll, it went away when I removed it.
Plugin works perfectly for me, only thing is I can't authorize it (see issue I opened today).
