### ISSUE TITLE
Bitwig 3.1 is unable to analyse some otherwise working LinVst plugins

### ISSUE THREAD

**Issue by GoaSkin** [osxmidi/LinVst#138]
Hello,
 
 
I am using Bitwig Studio under Linux with LinVst and Native Instruments Komplete. Everything worked well as long as I was using Bitwig 2. Yesterday, I renewed my Bitwig upgrade plan and installed version 3.1. Since the update, the plugin scan done by Bitwig fails for Absynth, FM8 and Guitar Rig while all the other plugins are still working.
 
Bitwig Studio prints for e.g.

> FM8 takes a long time to scan. Please check that the plug-in does not have a dialog open that is obscured by Bitwig Studio's user interface."

Meanwhile, there is the following console output:
 
```
 DSSI VST plugin server v0.986
Copyright (c) 2012-2013 Filipe Coelho
Copyright (c) 2010-2011 Kristian Amlie
Copyright (c) 2004-2006 Chris Cannam
LinVst version 2.8.0
Loading  /home/pleiadian/.wine/drive_c/Program Files/Native Instruments/VSTPlugins 64 bit/FM8.dll
002b:fixme:reg:GetEnabledXStateFeatures
002b:fixme:reg:GetEnabledXStateFeatures
[2020-03-25 21:36:55 notifications info] Opening project test:
002b:fixme:ntdll:EtwRegisterTraceGuidsW (0x51ec34, (nil), {f7b697a3-4db5-4d3b-be71-c4d284e6592f}, 7, 0x5debb0, (null), (null), 0x5e2280): stub
002b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {72b14a7d-704c-423e-92f8-7e6d64bcb92a}
002b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e2091f8a-1e0a-4731-84a2-0dd57c8a5261}
002b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e8a3bf1f-a86b-4390-9c60-5390b969d22c}
002b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {5727a00f-50be-4519-8256-f7699871fecb}
002b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {7e854ec7-cdc4-405a-b5b2-aaf7c9e7d40c}
002b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {79a60dc6-5fc8-4952-a41c-1163aeec5eb8}
002b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {2718d25b-5bf5-4479-8e88-babc64bdbfca}
002b:fixme:heap:GetNumaHighestNodeNumber semi-stub: 000000000022E320
002b:fixme:win:RegisterDeviceNotificationW (hwnd=0x1005c, filter=0x22e418,flags=0x00000004) returns a fake device notification handle!
[2020-03-25 21:36:55 float-document-master info] Stopping engine for New 1
[2020-03-25 21:36:55 float-gui-widgets info] Closing audio IO device ...
[2020-03-25 21:36:55 float-document-master info] Starting engine for test
002b:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
[2020-03-25 21:36:55 ramona-server error] Connection broken with client:
    java.io.EOFException
    at com.bitwig.ramona.serial.fHw.V2Q(SourceFile:263)
    at com.bitwig.ramona.serial.fHw.iFY(SourceFile:413)
    at bFi.ogB(SourceFile:847)
    at bFi.HXU(SourceFile:669)
    at bFi.HXU(SourceFile:650)
    at com.bitwig.ramona.protocol.ABw.HXU(SourceFile:88)
    at bGd.cRn(SourceFile:385)
    at bGe.run(SourceFile:276)
0032:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
[2020-03-25 21:36:55 float-engine-communication info] Engine connecting with sample rate 44100 and block size 1024
[2020-03-25 21:36:55 float-document-master info] Engine connected to project test
[2020-03-25 21:36:55 notifications info] Loading plugins...:
[2020-03-25 21:37:12 float-library-metadata error] Plugin host not responding reading metadata from file /home/pleiadian/.wine/drive_c/Program Files/Native Instruments/VSTPlugins 64 bit/FM8.so
[2020-03-25 21:37:12 notifications warning] FM8 is taking a long time to scan: Please check that the plug-in does not have a dialog open that is obscured by Bitwig Studio's user interface
002d:err:ntdll:RtlpWaitForCriticalSection section 0x7bd78720 "loader.c: loader_section" wait timed out in thread 002d, blocked by 002b, retrying (60 sec)
```
 
I am using wine staging 5.4 from the official wine repositories and Ubuntu 19.10 64 Bit and the latest version of LinVst. At first, I had installed the provided debian package but also built a 64Bit-only version and tried it - no difference.
 
With the alternative "airwave", Absynth, FM8 and Guitar Rig remain usable in Bitwig 3.1 but with all the bugs of airwave.
 
 
Do you have an idea why this happens and how to fix it?
 
 
thanks for answers
 
best regards
 
*Paul*

**Comment by osxmidi** [comment]
Try running the plugins individually (and then Wine is treated separately in a different way by Bitwig).

![bit1](https://user-images.githubusercontent.com/26504179/77614829-fe87d300-6f81-11ea-8096-023f05533480.png)
![bit2](https://user-images.githubusercontent.com/26504179/77614837-03e51d80-6f82-11ea-9698-30d656cad924.png)
![bit3](https://user-images.githubusercontent.com/26504179/77614843-08113b00-6f82-11ea-8515-3702ff19dd08.png)

**Comment by osxmidi** [comment]
A quick fix at the moment is to change some lines in linvst.cpp

find  (I think it's line 1081)

        wait(NULL);	        	    
        delete plugin;		

and change it to

      //  wait(NULL);	        	    
        delete plugin;

**Comment by osxmidi** [comment]
Use the quick fix in conjunction with choosing the plugins to be run individually.

**Comment by GoaSkin** [comment]
Hello,

thanks for the replies; I will try out the fix after work.

Yesterday, I found out that a worse workaround also makes the plugin working:

If you convert a single plugin only and let bitwig rescan just one file at a time, you need to wait until bitwig shows the "plugin takes a long time to scan" message. Then, you need to open a shell and force WINE to terminate by running 'wineboot -k'. The message desappears and instead, Bitwig shows "Plugin crashed - restart?". If you click restart, the plugin is listed and usable.

**Comment by GoaSkin** [comment]
> A quick fix at the moment is to change some lines in linvst.cpp
> 
> find (I think it's line 1068)
> 
> ```
>     wait(NULL);	        	    
>     delete plugin;		
> ```
> 
> and change it to
> 
> ```
>   //  wait(NULL);	        	    
>     delete plugin;		
> ```

Fix works. Thanks.
