### ISSUE TITLE
Released binaries won't run on Debian Jessie

### ISSUE THREAD

**Issue by lucmp** [osxmidi/LinVst#14]
Just in case someone is wondering, the released binaries won't run on Debian Jessie.

I haven't tried building from source.

**Comment by osxmidi** [comment]
I'll be trying to build LinVst on Debian Stretch soon, so I'll see what problems I run into.

**Comment by osxmidi** [comment]
The released binaries do run on stretch fwiw.

**Comment by lucmp** [comment]
Thanks, nice, but... still won't run on Jessie. :-(
