### ISSUE TITLE
Tempo is not passed to plug-in

### ISSUE THREAD

**Issue by marcan** [osxmidi/LinVst#140]
The issue is in these lines:

https://github.com/osxmidi/LinVst/blob/master/remotepluginclient.cpp#L1597
https://github.com/osxmidi/LinVst/blob/master/remotepluginclient.cpp#L1670

LinVst does not request the BPM from the host, so it is not returned. It should pass the flag `kVstTempoValid` (and maybe others like `kVstTimeSigValid`) to get more information from the host:

`timeInfo = (VstTimeInfo *)m_audioMaster(theEffect, audioMasterGetTime, 0, kVstTempoValid | kVstTimeSigValid, 0, 0);`

**Comment by keybreak** [comment]
@marcan 
Can you give example of DAW & plugin affected?

For example i've just tested **D16 group Drumazon** internal sequencer with host sync mode in **Renoise** - it perfectly follows host changes BPM..

**Comment by marcan** [comment]
Ardour DAW and Melodyne as a plug-in. Ardour only returns BPM info if the plug-in requests it with kVstTempoValid. I'm guessing Renoise always returns it.

**Comment by osxmidi** [comment]
> 
> 
> The issue is in these lines:
> 
> https://github.com/osxmidi/LinVst/blob/master/remotepluginclient.cpp#L1597
> https://github.com/osxmidi/LinVst/blob/master/remotepluginclient.cpp#L1670
> 
> LinVst does not request the BPM from the host, so it is not returned. It should pass the flag `kVstTempoValid` (and maybe others like `kVstTimeSigValid`) to get more information from the host:
> 
> `timeInfo = (VstTimeInfo *)m_audioMaster(theEffect, audioMasterGetTime, 0, kVstTempoValid | kVstTimeSigValid, 0, 0);`

Thanks, I've made the changes to the code.

**Comment by marcan** [comment]
Seems to be working fine, thanks!
