### ISSUE TITLE
Server process does not exit when the plugin host crashes

### ISSUE THREAD

**Issue by marcan** [osxmidi/LinVst#144]
When the plugin host exits unexpectedly, the child processes do not exit. There should be some way for them to check that the server died and force an exit.

Currently when the host dies, I have to keep killing all servers before restarting it, otherwise they pile up and cause issues.

**Comment by osxmidi** [comment]
> When the plugin host exits unexpectedly, the child processes do not exit. There should be some way for them to check that the server died and force an exit.
> 
> Currently when the host dies, I have to keep killing all servers before restarting it, otherwise they pile up and cause issues.

That might be hard to implement as when the host crashes it cuts communication with the server.

**Comment by marcan** [comment]
The server could periodically check whether the host is alive in some way. Even something as simple as checking whether the result of getppid() changes would work.

**Comment by osxmidi** [comment]
Good suggestion, I'll try it out.
