### ISSUE TITLE
Host does not close file descriptors before exec()ing server.

### ISSUE THREAD

**Issue by marcan** [osxmidi/LinVst#145]
The server processes inherit all of the host's file descriptors. E.g. on Ardour this includes X11 stuff, the JACK connection, a ton of audio files, etc. This causes problems, for example:

* Deleted audio files don't free disk space until the whole DAW is restarted, since they are kept open by the server process
* If the host dies, the server processes linger (#144) and keep a socket to JACK open. This prevents a new instance of the host from connecting to JACK with the same name until the server processes are killed.

Before `exec()`ing the server process, LinVst should close all fds except stdin/stdout/stderr and whatever it uses itself.

**Comment by osxmidi** [comment]
I'll look into it.

**Comment by osxmidi** [comment]
> The server processes inherit all of the host's file descriptors. E.g. on Ardour this includes X11 stuff, the JACK connection, a ton of audio files, etc. This causes problems, for example:
> 
>     * Deleted audio files don't free disk space until the whole DAW is restarted, since they are kept open by the server process
> 
>     * If the host dies, the server processes linger (#144) and keep a socket to JACK open. This prevents a new instance of the host from connecting to JACK with the same name until the server processes are killed.
> 
> 
> Before `exec()`ing the server process, LinVst should close all fds except stdin/stdout/stderr and whatever it uses itself.

I've added some code.

See if it works.

**Comment by marcan** [comment]
Seems to be fixed now, thanks!
