### ISSUE TITLE
Missing architecture in 2.8.1 Debian package?

### ISSUE THREAD

**Issue by pms967** [osxmidi/LinVst#147]
dpkg -i LinVst-64bit-32bit_2.8.1.deb

dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 10 package 'linvst-64bit-32bit':
 empty value for architecture
dpkg: error processing archive LinVst-64bit-32bit_2.8.1.deb (--install):
 package architecture () does not match system (amd64)
Errors were encountered while processing:
 LinVst-64bit-32bit_2.8.1.deb

**Comment by osxmidi** [comment]
It's probably due to being made on Manjaro.

I'll remake it on Debian.

**Comment by osxmidi** [comment]
I've put a Debian Stretch Debian package on the Releases page.
