### ISSUE TITLE
Why VST scanning is so long

### ISSUE THREAD

**Issue by QkiZMR** [osxmidi/LinVst#149]
I created *.so files with linvstconvert script. Then I ran Carla (from Kxstudio package) and make a scan to find new libs. Scanning is taking so much time. Sometimes one VST is taking 1 minute or 2 for scan. This happens in Carla and Renoise. CPU isn't hogged, other resources aren't used too. After when it's done it works fine.

**Comment by osxmidi** [comment]
Maybe there is a renamed linvst.so file that doesn't have a matching vst dll associated with it.

It can happen if a vst dll file is moved or whatever.

Maybe delete all of the renamed linvst .so files and then use the convert utility again and also recopy the lin-vst-server files to /usr/bin.

It could also be a Wine based problem, maybe problems with the wineprefix folder .wine etc.

Also, LinVst is not really designed for use with Carla, Carla has it's own vst bridge.

**Comment by QkiZMR** [comment]
I didn't move any DLL files. I just made *.so file generation and then start Carla, to check if it works. Then shutdown Carla and checked with Renoise. Renoise is making its own VST scanning and again it takes minutes on some of VSTs. I will try to open these troublesome plugins with some VST host to check if it's a Wine problem.
