### ISSUE TITLE
Sonic Academy's Kick 2 cursor disappears

### ISSUE THREAD

**Issue by jameh** [osxmidi/LinVst#150]
When I use Kick 2 as a VST plugin through Bitwig Studio, and use certain controls, the mouse cursor inside the wine window will disappear until it's moved outside the window.

In particular, the "<" ">" buttons for Click 1 make the cursor reliably disappear. (here's a screenshot with the cursor on top of those buttons.)

![2020-04-28-235410_1920x1080_scrot](https://user-images.githubusercontent.com/1538657/80568565-1bae2800-89ac-11ea-824c-0752782f2377.png)

wine-5.7 (Staging), arch linux, linvst stable 2.8.1, bitwig studio 3.1.3

**Comment by osxmidi** [comment]
It might be due to the focus that enables keyboard input.

A possible fix is at https://github.com/osxmidi/LinVst/tree/master/Remove-Focus

**Comment by keybreak** [comment]
@jameh 
May i ask how you get it to launch though?
Crash on start for me

**Comment by jameh** [comment]
@keybreak I have quite a few dll overrides in my winecfg, but cross-referencing with `strings "Kick 2 x64.dll" | grep .dll`, I have:

```
d2d1 (native)
*wininet (builtin)
*gdiplus (native)
```

**Comment by jameh** [comment]
@osxmidi I'm having trouble building my `.so` files correctly with `Remove-Focus/Makefile`.

```
make --file Remove-Focus/Makefile
./convert/convert-cli --input ../windows-vst --clean
./convert/convert-cli --input ../windows-vst --dll ./linvst.so
```

Compilation works without errors, and my `.so` vsts are placed next to their `.dll` equivalents who are all 64bit.

Am I doing this right?

**Comment by jameh** [comment]
It seems I needed to run `sudo make install` to put the new server files in place, now they launch, but I don't notice any change in behaviour from before. Is the Remove-Focus Makefile meant to keep the keyboard focus on the DAW? because I don't experience that

**Comment by osxmidi** [comment]
> 
> 
> It seems I needed to run `sudo make install` to put the new server files in place, now they launch, but I don't notice any change in behaviour from before. Is the Remove-Focus Makefile meant to keep the keyboard focus on the DAW? because I don't experience that

The remove focus version lets Wine handle the window focus and then keyboard input is lost.
The mouse is connected to the window focus, when the mouse is clicked on a window, then the window gets the focus..

If the Remove Focus version didn't help then it's a Wine issue, maybe a d2d1 issue or some other dll.

Overriding or not overriding some dlls might help.
