### ISSUE TITLE
Serum tooltips don't disappear

### ISSUE THREAD

**Issue by jameh** [osxmidi/LinVst#151]
Running Xfer Serum through linvst with tooltips enabled, they show up but don't disappear and even follow me to other desktops. I need to close Serum for it to disappear.

I've tested this on the latest master commit facce332332efa48560304ac57bfa45421787efb

**Comment by osxmidi** [comment]
That's a Wine issue, maybe related to d2d1.

Overriding or not overriding some dlls might help.

**Comment by jameh** [comment]
Using the builtin d2d1 makes serum not render, and the tooltips actually appear over the black window, but I'll try to simplify my winecfg by setting per-app settings.

**Comment by jameh** [comment]
I've used `testvst.exe` on my `Serum_x64.dll` with these overrides (I've tried various combinations, but these give the least warnings) with wine-5.7 (Staging)

```
gdiplus (native)
wininet (native)
d2d1 (native)
```

and it shows:

```
../LinVst/TestVst/testvst.exe Serum_x64.dll
00ca:fixme:msg:pack_message msg 14 (WM_ERASEBKGND) not supported yet
LinVst Vst Test
00ca:fixme:ver:GetCurrentPackageId (0x22eb70 (nil)): stub
HasEditor
NumInputs 0
NumOutputs 2
Maker Xfer Records
00ca:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
```

and also none I've tried have not had the tooltip issue. My current workaround is to disable tooltips, but that kinda sucks.

Is there a known working set of dll overrides that fixes the tooltip issue?
