### ISSUE TITLE
Can't authorize Izotope plugin

### ISSUE THREAD

**Issue by SaintJules** [osxmidi/LinVst#153]
I have installed Izotope Ozone Imager in my default prefix and it works perfectly inside my DAW. I am unable to authorize it, though. Both with online and offline authorization, I get an error from the authorization server. Output from a terminal  goes like this:

`0036:err:wininet:HTTP_ParseDateAsAsctime unexpected weekday L"-1"
0036:err:wininet:HTTP_ParseDate unexpected date format L"-1"
GnuTLS error: The requested data were not available.`

If I understand your guides correctly, I might need to override some dlls but I'm not sure how to go about this. Thanks for any help.

**Comment by thom-s** [comment]
Can confirm I have had the exact same issues with both Ozone Imager and Vynil
