### ISSUE TITLE
No mouse on Native Instrument Kontakt in Bitwig

### ISSUE THREAD

**Issue by ni-ka** [osxmidi/LinVst#158]
Hi,

I've used the bitwig makefile to build linvst, unfortunately when I add a Kontakt 5 or Kontakt 6 Player instrument the UI appears but I have no mouse pointer and thus cannot interact. Any pointers?

Cheers!

**Comment by thom-s** [comment]
I have had similar mouse issues with other VSTs in Bitwig, generally restarting the VST process manually or the whole DAW fixed the issue.
