### ISSUE TITLE
[Question] Changes in 3.0

### ISSUE THREAD

**Issue by keybreak** [osxmidi/LinVst#159]
@osxmidi 
Thx for update! :+1: 

Since i'm not really hip to source code itself and you're not a fan of changelogs...
Can you please tell where to look for testing and what have changed?

I worry a lot about any changes, since tested a lot of stuff as you know :wink:

**Comment by osxmidi** [comment]
> @osxmidi
> Thx for update! 
> 
> Since i'm not really hip to source code itself and you're not a fan of changelogs...
> Can you please tell where to look for testing and what have changed?
> 
> I worry a lot about any changes, since tested a lot of stuff as you know

Hi,

The changes are mainly for Waveform and also a bit of cleaning up.

I've tested a few plugins with Renoise and song saving etc.

If there are problems, it's possible to get the older source code from the previous version from the releases page and also the binaries.

**Comment by keybreak** [comment]
Thx! :+1: 

Yeah i know that you can always downgrade, but it's just nice to have short summary to know where to look, since we're all aimed to make **LinVst** better :wink: 

So far looking good! :smile: 
I'll make sure to write any problems / bugs, just had to pause my testing for a while..

**Comment by keybreak** [comment]
@osxmidi 
I was pretty busy lately, but finally got to test it for real - there are some big problems with 3.1 and current master, compared to 2.8 unfortunately :disappointed:

I've compiled from source on Manjaro there were no errors.

Will create few issues in depth soon...

**Comment by keybreak** [comment]
https://github.com/osxmidi/LinVst/issues/163 https://github.com/osxmidi/LinVst/issues/164 https://github.com/osxmidi/LinVst/issues/165
I would assume that at least couple of those are connected to this changes:
https://github.com/osxmidi/LinVst/issues/161 and also those changes about initial Windows positions / height / weight, remember that issue where someone mentioned problems with Bitwig or some other DAW? Can't find that issue though..
