### ISSUE TITLE
Error loading lin-vst-servertrack.exe.so

### ISSUE THREAD

**Issue by jalovatt** [osxmidi/LinVst#160]
I just upgraded to Ubuntu Studio 20.04 and my dear, sweet EZDrummer stopped working. :(

When scanning for plugins I get this from Reaper:
```
002b:err:module:__wine_process_init failed to load L"Z:\\usr\\bin\\lin-vst-servertrack.exe.so", error c000012f
LinVst Error: lin-vst-server not found or vst dll load timeout or LinVst version mismatch
```

The files are there:
```
$ ls /usr/bin/lin-vst*
/usr/bin/lin-vst-server.exe
/usr/bin/lin-vst-server.exe.so
/usr/bin/lin-vst-servertrack32.exe
/usr/bin/lin-vst-servertrack32.exe.so
/usr/bin/lin-vst-servertrack.exe
/usr/bin/lin-vst-servertrack.exe.so
```
and were extracted from the current release's .zip as was the `linvst.so` I'm using.

I saw a previous issue that turned out to be Wine having remapped `Z:`, but in my case it's still pointing to `/`. `winecfg` _does_ log a relevant-sounding error, though, whenever it tries to do anything with the drive:
```
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
```

Suggestions?

Cheers.

Ubuntu Studio 20.04
Reaper 6.13
LinVST 3.0
Wine 5.0.2 Stable

**Comment by osxmidi** [comment]
> I just upgraded to Ubuntu Studio 20.04 and my dear, sweet EZDrummer stopped working. :(
> 
> When scanning for plugins I get this from Reaper:
> 
> ```
> 002b:err:module:__wine_process_init failed to load L"Z:\\usr\\bin\\lin-vst-servertrack.exe.so", error c000012f
> LinVst Error: lin-vst-server not found or vst dll load timeout or LinVst version mismatch
> ```
> 
> The files are there:
> 
> ```
> $ ls /usr/bin/lin-vst*
> /usr/bin/lin-vst-server.exe
> /usr/bin/lin-vst-server.exe.so
> /usr/bin/lin-vst-servertrack32.exe
> /usr/bin/lin-vst-servertrack32.exe.so
> /usr/bin/lin-vst-servertrack.exe
> /usr/bin/lin-vst-servertrack.exe.so
> ```
> 
> and were extracted from the current release's .zip as was the `linvst.so` I'm using.
> 
> I saw a previous issue that turned out to be Wine having remapped `Z:`, but in my case it's still pointing to `/`. `winecfg` _does_ log a relevant-sounding error, though, whenever it tries to do anything with the drive:
> 
> ```
> wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
> ```
> 
> Suggestions?
> 
> Cheers.
> 
> Ubuntu Studio 20.04
> Reaper 6.13
> LinVST 3.0
> Wine 5.0.2 Stable


"Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available" might be a permissions problem maybe caused by the upgrade.

It's hard to say how to fix it seeing that I've never had that problem before.

I would probably try to reinstall wine again or delete the wine prefix ~.wine and the creating a new one via winecfg but that means that all of your wine apps get deleted.

I'd focus on trying to get rid of the "Read access denied" error and worry about the rest later on because if you can solve the "Read access denied" error then LinVst should then be ok.

The "Read access denied" error basically means that wine can't read the wine drives which are set up in the wineprefix, so it could be that the winprefix ~.wine has been corrupted somehow by the upgrade.

**Comment by keybreak** [comment]
> "Read access denied for device L"\??\Z:\", FS volume label and serial are not available" might be a permissions problem maybe caused by the upgrade.

It's common on Arch too, nothing to worry about, it's definitely not destructive for LinVst

**Comment by keybreak** [comment]
> 002b:err:module:__wine_process_init failed to load L"Z:\\usr\\bin\\lin-vst-servertrack.exe.so", error c000012f
LinVst Error: lin-vst-server not found or vst dll load timeout or LinVst version mismatch

Could it be that it's really version mismatch and you forgot to update the one in vst folder?
It's a little not intuitive process, you can use this tool for ease of management https://github.com/Goli4thus/linvstmanager

**Comment by jalovatt** [comment]
Success! For future me, or anyone else who might run into the same issue since Ubuntu 20.04 is their LTS version now:

Ubuntu 20.04 is built on Debian Bullseye, so apps built for Debian Buster (LinVST 3.0, in this case) may not work. I cloned the repo, built it locally, and EZDrummer came right up.
