### ISSUE TITLE
Linvst Not Using 48khz Sample Rate

### ISSUE THREAD

**Issue by brandflake11** [osxmidi/LinVst#161]
Hello,
Artix Linux user here. I am using the linvst-stable AUR package (2.8-1), and I have noticed that Linvst does not scale to 48khz sampling rate. If I load a windows plugin while Jack2 is running at 48khz, it is slightly higher in pitch. This does not happen when Jack2 is running at 44.1khz. Linvst loaded plugins load in tune. I am able to reproduce this using both Renoise and Carla, ruling out the possibility it is the plugins or the program loading the plugins, and with Carla loading the same plugin with its bridge at 48khz does not give the same out of tune result. Is there anything I can do to force these plugins to run at 48khz, my preferred sample rate?

Another thing I forgot to add was that I am using wine-staging 5.16-1.

**Comment by keybreak** [comment]
Can not confirm it with LinVst v2.8.2 (haven't tested 3 yet)
Tested on:
- Manjaro KDE
- jack2 + Cadence
- Renoise v3.2.2

Tested few plugins and checked meters, no out of tune or anything like that for me...

For better chances of debug please write:
- What audio card do you use
- Version of Renoise

Also try to build latest **LinVst** and see if it helps https://github.com/osxmidi/LinVst/releases/tag/3.0

**Comment by brandflake11** [comment]
Thank you for the reply. 
Audio Card: Realtek ALC298 (onboard laptop card)
Renoise: 3.2.2-1
Carla-git: 1:2.2.0.RC1.r51.g5a58a90ce-1 (Carla-git from AUR)

I will try the releases and builds to see if they make a difference.

The two plugins I am having issues with Linvst is Korg Wavestation and ProteusVX.

**Comment by keybreak** [comment]
> ProteusVX
> 24-bit/192kHz audio playback.

So i assume it's not the plugin then, at least not that one...

>  Audio Card: Realtek ALC298 (onboard laptop card)

Have same one on my DELL laptop, tested - again doesn't happen here :confused: 

That's about as far as i personally can help to debug, hopefully latest non-aur version will help!

**Comment by brandflake11** [comment]
Thanks for testing for me @keybreak. I am thinking that I will try a different version and see if that helps. That, or I will just tune things down. :D I wanted to report if it is a bug though.

**Comment by keybreak** [comment]
You did right by reporting, it's still very well may be a bug, not sure of what exactly though.
Looks more like driver to me, but i'm not sure :smile: 

@osxmidi should know more

**Comment by brandflake11** [comment]
Can confirm that this bug is also happening to me when using the linvst from git. I got this from the aur package linvst, which gave me this source:https://github.com/osxmidi/LinVst.git

I am not sure what would cause this, other than maybe my computer's build environment not being exactly right, but I am also not sure.

**Comment by brandflake11** [comment]
Just installed the latest release (pre-compiled 3.0) from github and I am still getting the same issues happening with renoise and carla.

**Comment by osxmidi** [comment]
Maybe try

in lin-vst-server.cpp

 line 1863
 
 Replace
 
    if(remoteVSTServerInstance)
    {	    
    if (!remoteVSTServerInstance->exiting && remoteVSTServerInstance->effectrun)
    {
    rv = remoteVSTServerInstance->sampleRate;
    }
    }
    
 with
    
    rv = remoteVSTServerInstance->sampleRate;
     
     
     
 line 1903
 
 Replace
 
    if(remoteVSTServerInstance)
    {
    if (!remoteVSTServerInstance->exiting && remoteVSTServerInstance->effectrun)
    {
    rv = remoteVSTServerInstance->bufferSize;
    }
    }    
    
with    
    
    rv = remoteVSTServerInstance->bufferSize;

**Comment by osxmidi** [comment]
> Just installed the latest release (pre-compiled 3.0) from github and I am still getting the same issues happening with renoise and carla.

I found out was was happening.

Those plugins seem to set the samplerate very early and then the default 44100hz was coming in later and overriding the samplerate (instead of the default 44100 being set first and then the samplerate overriding it).

Anyway it's fixed in the code and the binary release.

**Comment by keybreak** [comment]
Huh...That was unexpected :smile: 
Hopefully won't break anything else! :+1:

**Comment by osxmidi** [comment]
> Huh...That was unexpected 
> Hopefully won't break anything else!

Reaper sets the samplerate after, the plugin is (officially) opened via a vst call to open the plugin which (one would expect) would be the usual way to do things but some daws don't do it like that apparently and try to set the samplerate just after the vst dll is loaded.

So because of that the default setting was overriding the samplerate the daw was setting (with some daws).

I've only seen this with Renoise.

**Comment by brandflake11** [comment]
Thanks @osxmidi, just got the latest git version from the AUR (linvst 3.0.r17.5573458-1) and it is fixed. Thanks much for fixing this so quickly!
