### ISSUE TITLE
Gui is not initialized within dual-screen machine.

### ISSUE THREAD

**Issue by Levitanus** [osxmidi/LinVst#162]
![изображение](https://user-images.githubusercontent.com/29713891/94752623-fcca1c80-03b5-11eb-933a-2480e6c1c200.png)
I use two monitors: 1920x1080 from left and 1080x1920 from the right side (I can't remember where I can get the real Xorg canvas dimentions). And many of plugins: by Ignite Amps, Liquid Sonics etc. are opened in black. GUI can be updated within re-rendering of their area, for example, by touching the knob or button.

I'm quite sure it's LinVST issue as carla works goon on dual-screen machine.
Actually I was quite surprised these plugins work good on one monitor, as yesterday I was forced to move and could get only one screen with myself, which opened the problem.

**Comment by osxmidi** [comment]
> ![изображение](https://user-images.githubusercontent.com/29713891/94752623-fcca1c80-03b5-11eb-933a-2480e6c1c200.png)
> I use two monitors: 1920x1080 from left and 1080x1920 from the right side (I can't remember where I can get the real Xorg canvas dimentions). And many of plugins: by Ignite Amps, Liquid Sonics etc. are opened in black. GUI can be updated within re-rendering of their area, for example, by touching the knob or button.
> 
> I'm quite sure it's LinVST issue as carla works goon on dual-screen machine.
> Actually I was quite surprised these plugins work good on one monitor, as yesterday I was forced to move and could get only one screen with myself, which opened the problem.

As far as I know, LinVst used to have issues with dual monitors a long time ago, but I'm pretty sure it got fixed after this issue popped up https://github.com/osxmidi/LinVst/issues/43

**Comment by Levitanus** [comment]
hmm, I'll double-check, but I've built it from this source somewhere at the last spring...

**Comment by keybreak** [comment]
Make sure you also use package:
```
lib32-libxinerama
```

At least that's how it's called on Arch - it fixes **Wine** problems for multi-monitor output

**Comment by Levitanus** [comment]
@keybreak, Thanks, I'll try at evening

**Comment by Levitanus** [comment]
hmm, I think that is it, was installed
![изображение](https://user-images.githubusercontent.com/29713891/94793692-12b2fe00-0405-11eb-9cab-cc62e79874b7.png)
