### ISSUE TITLE
vst.so failed to load in bitwig

### ISSUE THREAD

**Issue by pitrackster** [osxmidi/LinVst#170]
Hi !

First of all thanks a lot for your work... I hope I'll soon be able to get rid of Windows you'll be part of the story !

#### Technical information

- Ubuntu 20.04 standard kernel installation
- wine-6.0-rc1
- LinVst 3.2 (used the deb package)

#### What I did

I installed some NI products through wine : 
- Battery 4
- FM8
- Absynth 5

Then I used `linvstconvert` to build the plugin.so.

The only one that works is Battery 4... the two others wont load in bitwig. I got the message *Absynth5 is taking to long time to scan*

Below are the logs for Absynth 5 FX from bitwig if it can help (the error is the same for all the other plugins)

```log
com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Plugin host did not respond for 20.0 seconds
exit code:137
stdout:
PluginHost: Reading VST 2.4 plugin metadata for /home/guillpat/winvst/Absynth 5 FX.so


stderr:
Failed to set realtime priority: Operation not permitted
03d0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
03d0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
DSSI VST plugin server v0.986
Copyright (c) 2012-2013 Filipe Coelho
Copyright (c) 2010-2011 Kristian Amlie
Copyright (c) 2004-2006 Chris Cannam
LinVst version 3.2
Loading  /home/guillpat/winvst/Absynth 5 FX.dll
03d0:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000021C100 1 C) semi-stub
03d0:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000021C1A0 1 C) semi-stub
03d0:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000021BD30 1 C) semi-stub
03d0:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000021C640 1 C) semi-stub
03d0:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000021DDC0 1 C) semi-stub
03d0:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000021DF30 1 C) semi-stub
03d0:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000021DE10 1 C) semi-stub
03d0:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000021DAD0 1 C) semi-stub
03d0:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000021DA90 1 C) semi-stub
03d0:fixme:service:I_ScRegisterDeviceNotification Notification filters are not yet implemented.
03d0:fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
03d0:fixme:file:NtLockFile I/O completion on lock not implemented yet
03d0:fixme:msvcrt:Concurrency_wait (100) stub!
03e8:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
03e8:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0000000004A8D990 1 C) semi-stub
03d0:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
03d0:fixme:msvcrt:__clean_type_info_names_internal (000000018000AB78) stub
```
If you have any idea ;-)

Thanks again for your work !

**Comment by osxmidi** [comment]
Hi,

It might be due to not having winbind installed.

Try

sudo apt-get install winbind

and then reboot

I don't know if that's the total answer.

**Comment by osxmidi** [comment]
I've uploaded a Bitwig version that gets around some Bitwig problems https://github.com/osxmidi/LinVst/releases

Just install it and use it like the regular LinVst (the regular LinVst and the Bitwig LinVst can coexist and be used together).

Set the plugins to run individually in Bitwig's plugin settings.

**Comment by pitrackster** [comment]
Hey thanks for your answer.

Unfortunatly it did not solved anything.

- I installed winbind and reboot... nothing changed
- I took the bitwig version of linvst and then
  - moved all server files into `/usr/bin`
  - from the extracted folder I launched `./convert/linvstconvert`
  - for `linvst.so` I select `embedded/linvst.so` from the extracted folder
  - then I select the directory where are my vst dlls
  - launch the "conversion"
  - same problem on bitwig

Is the process right ?

Thanks anyway

**Comment by osxmidi** [comment]
> Hey thanks for your answer.
> 
> Unfortunatly it did not solved anything.
> 
>     * I installed winbind and reboot... nothing changed
> 
>     * I took the bitwig version of linvst and then
>       
>       * moved all server files into `/usr/bin`
>       * from the extracted folder I launched `./convert/linvstconvert`
>       * for `linvst.so` I select `embedded/linvst.so` from the extracted folder
>       * then I select the directory where are my vst dlls
>       * launch the "conversion"
>       * same problem on bitwig
> 
> 
> Is the process right ?
> 
> Thanks anyway

Yes that's it but I think something has gone wrong somewhere, and it seems like the Absynth 5 FX.so file is the old one that uses the regular LinVst version.

I'd say to do it again.

Try using linvstconvert (from the Bitwig version) on Absynth 5 FX.dll using linvst.so from the Bitwig version  and copying the lin-vst-server files to /usr/bin.

I did try it out.

I downloaded Absynth and tried it with the regulr LinVst and I got the time out error, and then I tried it with the Bitwig LinVst version and it was ok.

**Comment by pitrackster** [comment]
I tried again with a clean install (removed all lin-vst-server files from /usr/bin and put only those from bitwig version) and everything work !

Thanks a lot for your help and your work !
