### ISSUE TITLE
Bitwig MIDI polyphony broken

### ISSUE THREAD

**Issue by lucianoiam** [osxmidi/LinVst#173]
Thanks for this fine piece of software.

I cannot seem to play chords, only one note at a time. Like the plugins get the first note-on message and ignore any subsequent note-on until a note-off is received first.

- Not related to the MIDI physical input, also happens with recorded events or playing on the physical keyboard + clicking on BW piano roll simultaneously
- Does not seem related to a particular VST plugin, happens on at least two different plugins from different manufacturers
- Wrapping the plugins using Carla works
- Does not happen on REAPER. I tested that DAW for a long time and LinVst is rock solid there. Same WINE environment, plugins, etc...

Running Ubuntu 20.10, built LinVst from Makefile-64-32bit-Bitwig

**Comment by keybreak** [comment]
Maybe it's Bitwig function of mono input accidentally turned on?
I'm not sure where exactly it is in there, but in Renoise and other DAWs there is such functionality.

**Comment by lucianoiam** [comment]
I don't think so, all native plugins work fine in the same track including those WinVSTs wrapped using Carla.

**Comment by osxmidi** [comment]
> Thanks for this fine piece of software.
> 
> I cannot seem to play chords, only one note at a time. Like the plugins get the first note-on message and ignore any subsequent note-on until a note-off is received first.
> 
>     * Not related to the MIDI physical input, also happens with recorded events or playing on the physical keyboard + clicking on BW piano roll simultaneously
> 
>     * Does not seem related to a particular VST plugin, happens on at least two different plugins from different manufacturers
> 
>     * Wrapping the plugins using Carla works
> 
>     * Does not happen on REAPER. I tested that DAW for a long time and LinVst is rock solid there. Same WINE environment, plugins, etc...
> 
> 
> Running Ubuntu 20.10, built LinVst from Makefile-64-32bit-Bitwig

Hi,

LinVst just passes the midi messages on to the host and doesn't alter note on/off info, so I can't imagine what is causing it and I've never heard of the problem before.

I'll look into it when I get the time.

**Comment by lucianoiam** [comment]
No need to, found the cause and it is not a LinVst issue at all. Seems my tracks have MPE enabled by default and that will make the MIDI channel cycle on each key press... quite embarrassing. The screenshot shows what a wrapped VST ( https://freevstplugins.net/midi-monitor/ ) is receiving when playing a C major chord on a controller.

![Screenshot_2020-12-24_10-35-15](https://user-images.githubusercontent.com/930494/103079460-2de07480-45d4-11eb-9372-5be587f630a6.png)

False alarm... 🤯

**Comment by keybreak** [comment]
Told ya :wink:  :laughing:

**Comment by lucianoiam** [comment]
> Maybe it's Bitwig function of mono input accidentally turned on?
> I'm not sure where exactly it is in there, but in Renoise and other DAWs there is such functionality.

Sorry but MPE does not mean "mono input" at all 🤷🏻‍♂️, thanks anyways.
