### ISSUE TITLE
Wine Desktop window constantly open

### ISSUE THREAD

**Issue by NlGHT** [osxmidi/LinVst#175]
I have been using LinVST for years now and love it!
After the last updates (I would like to say around the transition from version 2.x to 3.x) every plugin I try to use causes an annoying constant "Wine Desktop" window to stay open as seen here:
![image](https://user-images.githubusercontent.com/36537208/103699918-f4304600-4fa3-11eb-998b-0846c0b33a6d.png)

Initially the window will open fullscreen covering everything with blue, so I'm slightly surprised there's been no issues posted before, unless i've missed them (sorry! if I have).  I can toggle its fullscreen with my window manager fullscreen toggle button.

I am using REAPER as a VST host so it might be on them i'm not sure.  It doesn't seem to matter which plugin, the same issue occurs.  The problem window will only persist however until there are no more linvst-bridged plugins loaded into REAPER.  So the window will stay open from when you add your first linvst plugin and then close again once all are deleted.

I believe I have seen the WIne Desktop window open when a plugin tries to prompt a window (for something like activation), but the fact that this happens with every plugin I don't think the reason is a popup box.  If there is I can't find it though.

**Comment by osxmidi** [comment]
I havn't heard of that problem before.

It might be a Wine configuration issue of some kind.

A hangover from a previous wine install etc etc.

Are you using Wine from WineHQ?

**Comment by keybreak** [comment]
Yep, that's weird...
Are you sure globally Wine desktop option is disabled in your **winecfg**?

**Comment by NlGHT** [comment]
I think it is indeed an issue with Wine, I will continue looking into it.  I didn't realise it but apparently many wine things are currently broken right now as well on my end.

**Comment by NlGHT** [comment]
So I'm sorry to keep writing here, but as a follow up **the issue was indeed the emulate virtual desktop option in winecfg**.  Unfortunately I was unable to test it out because the recent latest wine versions that were in Arch Linux's repos didn't work with winetricks or winecfg.  This was a bug that was notified to the Arch maintainers, fixed in the latest wine version (6.0).
