### ISSUE TITLE
Host crash on too long sub-window splash

### ISSUE THREAD

**Issue by Levitanus** [osxmidi/LinVst#176]
I've accounted some problems (host crashes) when a sub window of plugin is active for a log time (for example KONTAKT browser). For a long time it was just a trade-off issue, but recently, It made impossible to use some KONTAKT libraries which loading took too long (even after batch-resave).

So, I've updated to the last git version of LinVst 3.2.1 (tagged commit)

Reaper sys output just before crash.
```
01d8:fixme:shell:IDropTargetHelper_fnShow (0x7de2d20)->(0)
01d8:fixme:shell:IDropTargetHelper_fnShow (0x7de2d20)->(1)
01d8:fixme:shell:IDropTargetHelper_fnShow (0x7de2d20)->(0)
01d8:fixme:shell:IDropTargetHelper_fnShow (0x7de2d20)->(1)
01d8:fixme:shell:IDropTargetHelper_fnShow (0x7de2d20)->(0)
01d8:fixme:shell:IDropTargetHelper_fnShow (0x7de2d20)->(1)
0240:fixme:winsock:server_ioctl_sock Unsupported ioctl 98000010 (device=9800 access=0 func=4 method=0)
0240:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (_WSAIOW(IOC_VENDOR, 16))
0240:fixme:winsock:server_ioctl_sock Unsupported ioctl 98000010 (device=9800 access=0 func=4 method=0)
0240:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (_WSAIOW(IOC_VENDOR, 16))
0240:fixme:winsock:server_ioctl_sock Unsupported ioctl 98000010 (device=9800 access=0 func=4 method=0)
0240:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (_WSAIOW(IOC_VENDOR, 16))
0240:fixme:winsock:server_ioctl_sock Unsupported ioctl 98000010 (device=9800 access=0 func=4 method=0)
0240:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (_WSAIOW(IOC_VENDOR, 16))
0240:err:ole:CoUninitialize Mismatched CoUninitialize
0240:err:ole:CoUninitialize Mismatched CoUninitialize
01d8:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpScanMemory
Ошибка сегментирования (стек памяти сброшен на диск)
01d8:fixme:x11drv:X11DRV_DestroyNotify window 0x4009e/6000007 destroyed from the outside
01d8:fixme:shell:IShellBrowser_fnOnViewWindowActive stub, 0xfd180 (0x7ebf770)
```

**Comment by Levitanus** [comment]
Interesting, that on the scanning of plugins sometimes LinVst asked if plugin is freezed. But here it just crashes.

**Comment by osxmidi** [comment]
I havn't experienced it myself.

I'll try to duplicate it but if I can't then I can't do much.

The line

01d8:fixme:x11drv:X11DRV_DestroyNotify window 0x4009e/6000007 destroyed from the outside

shouldn't be happening.

Sometimes the state of the wineprefix (ie ~/.wine) can cause problems, dll overrides and other installs etc.

**Comment by keybreak** [comment]
That line is weird, what wine version do you use ain't it something with **dxvk**?

**Comment by Levitanus** [comment]
last time I've updated wine just before the log: ``winehq-staging 6.0~rc5-focal``` + enomerous dev packages for compiling LinVst)

What about prefix — I'm not sure what is replaced now, as it is about 1,5 years old... Is the way to see all replaced\installed components to the prefix?

**Comment by keybreak** [comment]
> Is the way to see all replaced\installed components to the prefix?

**winetricks.log** in prefix's dir
_________

I don't think it's prefix...Looks like either Wine or something in system like video driver or x11 maybe
Check your **journalctl -p3 -xb** for something suspicious

**Comment by osxmidi** [comment]
> last time I've updated wine just before the log: `winehq-staging 6.0~rc5-focal` + enomerous dev packages for compiling LinVst)
> 
> What about prefix — I'm not sure what is replaced now, as it is about 1,5 years old... Is the way to see all replaced\installed components to the prefix?

https://linuxmusicians.com/viewtopic.php?f=62&t=22336

**Comment by Levitanus** [comment]
> https://linuxmusicians.com/viewtopic.php?f=62&t=22336

I've updated wine to the last one exactly because the wine team said that bug, connected with Kontakt is fixed — so I confirmed it)
The last several months I used wine 5.03, as it was the last stable release.

I doubt this is a personal wine-kontakt problem as for some stable work I use stand-alone version which does no fall. But I will definitely will check everything you're pointing to in the next couple of days, thanks!

**Comment by Levitanus** [comment]
**journalctl -p -xb**
Most errors are connected to apache.
here is something connected to lightdm:
```
янв 08 00:44:28 levitanus-main lightdm[1682]: PAM unable to dlopen(pam_kwallet.>
янв 08 00:44:28 levitanus-main lightdm[1682]: PAM adding faulty module: pam_kwa>
янв 08 00:44:28 levitanus-main lightdm[1682]: PAM unable to dlopen(pam_kwallet5>
янв 08 00:44:28 levitanus-main lightdm[1682]: PAM adding faulty module: pam_kwa>
янв 08 00:44:29 levitanus-main lightdm[1785]: PAM unable to dlopen(pam_kwallet.>
янв 08 00:44:29 levitanus-main lightdm[1785]: PAM adding faulty module: pam_kwa>
янв 08 00:44:29 levitanus-main lightdm[1785]: PAM unable to dlopen(pam_kwallet5>
янв 08 00:44:29 levitanus-main lightdm[1785]: PAM adding faulty module: pam_kwa>
```
There is something with alsa and something with my printer drivers.

**winetricks.log**
```
vcrun2013
w_workaround_wine_bug-37781
vcrun2015
iertutil
wininet
gdiplus
```

**Comment by osxmidi** [comment]
> PAM unable to dlopen(pam_kwallet.>

Google PAM unable to dlopen(pam_kwallet.>

That's the only thing I can come up with.

Apparently some get that error if they install 2 different desktops, but I don't know much about it.
