### ISSUE TITLE
Regression in latest release (3.5) : Many VSTs won't load anymore

### ISSUE THREAD

**Issue by artscoop** [osxmidi/LinVst#177]
Since the upgrade to LinVst 3.5 (alike for Wine32 and Wine64 prefixes), most, but not all, plugins won't load anymore.

- The .so files for the DLLs were correctly regenerated after the upgrade, more than once.
- When using Ardour, or Renoise to register VST plugins, it hangs for a minute before failing (looks like a timeout). Again, this does not happen on some plugins.
- Wine (5.22 Staging) works well otherwise. Wine apps using VSTs still work as expected.

I am on Manjaro Linux, with Wine 5.22 staging.
I use 32-bit and 64-bit prefixes, and it fails on both.

- One example of "simple" plugin that does not work anymore is Mokafix's Monkey Orchestra (32 bits), that can be found here: https://vst4free.com/plugin/1524/
- A more complex plugin like Xfer Records' Serum (paid) still works.

Another note:
I have experienced something interesting after going back to release 3.2.1:
Some plugins, often the same ones that don't register in 3.5 due to timeouts, now load properly, but once the GUI is loaded, something hangs for 2/5 minutes in the host before sound can be generated from the plugin. While it's frozen, the VST GUI responds to mouse interaction correctly however.

**Comment by osxmidi** [comment]
> Since the upgrade to LinVst 3.5 (alike for Wine32 and Wine64 prefixes), most, but not all, plugins won't load anymore.
> 
>     * The .so files for the DLLs were correctly regenerated after the upgrade, more than once.
> 
>     * When using Ardour, or Renoise to register VST plugins, it hangs for a minute before failing. Again, this does not happen on some plugins.
> 
>     * Wine (5.22 Staging) works well otherwise. Wine apps using VSTs still work as expected.
> 
> 
> I am on Manjaro Linux, with Wine 5.22 staging.
> I use 32-bit and 64-bit prefixes, and it fails on both.

Hi.

Thanks for the info.

I've gone back to the previous version.

I'll test the new version some more, it did seem to run ok on Debian.
