### ISSUE TITLE
Issue with Loudness Monitoring

### ISSUE THREAD

**Issue by reedacartwright** [osxmidi/LinVst#178]
I'm experimenting with using windows loudness monitoring VSTs through this plugin. However, when I use the VSTs in Audacity via LinVST there is a consistent +3 LUFS gain. I assume this has something to do with Wine/LinVST converting the audio signal between stereo and mono, and the VSTs getting confused.

Does this make sense? Is there anyway to fix it?

Edit: If I hit "Apply" in Audacity I get the correct loudness for the reference file (-16 LUFS), but if I use "play" I get (-13 LUFS). Strange. I'm pretty sure this is a user problem, but I don't know where to look to fix it.

**Comment by keybreak** [comment]
Can you name dev / name / version of loudness monitoring VSTs so we can also test them?

**Comment by reedacartwright** [comment]
Here are the links to what I'm using:

- -16 LUFS reference: https://developers.google.com/assistant/downloads/loudness/tts-reference.wav
- https://youlean.co/download-youlean-loudness-meter/
- https://www.tb-software.com/TBProAudio/dpmeter5.html
- https://www.klangfreund.com/lufsmeter/
- https://www.klangfreund.com/multimeter/

The last two have Linux versions that can be used to compare.

**Comment by reedacartwright** [comment]
Here's another thing that I observed. If I hit "Play" there is a console message of the VST running and then existing and the loudness is measured as 3 LUFS highter. If I hit "Apply" there is no console message and the Loudness is measured correctly.

**Comment by reedacartwright** [comment]
I'm not sure it is an issue with your wrapper anymore. I created an issue with audacity in case it is on their end. https://github.com/audacity/audacity/issues/723
