### ISSUE TITLE
Plugins fail to load on Wine Staging 6.3

### ISSUE THREAD

**Issue by a-parhom** [osxmidi/LinVst#179]
I'm trying to load plugins in Reaper, but all of them fail. No output in console is present, no "LinVst version..." and no info about starting Wine. The issue happened after updating from Wine 6.2 to 6.3. I updated LinVst from 3.1.5 to 3.2.1 (I always build it from source) but nothing changed. Starting standalone plugin versions through Wine works though.

**Comment by osxmidi** [comment]
> I'm trying to load plugins in Reaper, but all of them fail. No output in console is present, no "LinVst version..." and no info about starting Wine. The issue happened after updating from Wine 6.2 to 6.3. I updated LinVst from 3.1.5 to 3.2.1 (I always build it from source) but nothing changed. Starting standalone plugin versions through Wine works though.

Hi,

It seems to be a bug with Wine Staging 6.3.

Try rolling back or installing Wine-Stable 6.

**Comment by osxmidi** [comment]
The bug has apparently been fixed, so Wine 6.4 should be ok when it's released.

**Comment by mitchell-gil96** [comment]
For reading purposes, which bug was it? The symlink file renames one, winegcc segfault or some other thing?

**Comment by thom-s** [comment]
Downgrading to wine-6.2-1 fixed the issue immediately for me, thank you for documenting this issue.

Will update this when wine 6.4 is available to me.

**Comment by FluxTape** [comment]
I can confirm that wine 6.4 works again
