### ISSUE TITLE
Problems on Opensuse leap 42.3

### ISSUE THREAD

**Issue by daschaffert** [osxmidi/LinVst#18]
Sorry for writing here, but I don't know how to get in touch with you on an other way!
I recently ahd to change to openseuse 42.3 (bevore was using 42.1) I was alway using the vsthost from dssi without any problems but vsthost isnt working anymore in 42.3 (I think it has someting to do with the g++ 32bit libraries - but I'm not sure)

So now I tryed using the LinVst but no Plugin I try is working. The librys are compiling fine and everything seems to be o.k. - but now DAW I tryed is handling the plugins :-)

I even tryed to use the lin-vst-server32.exe directly but no plugin is working ... do you have any advice what Im doing wrong???

again excuse me for writing here!

**Comment by osxmidi** [comment]
The only thing I can think of at the moment is that there might be something wrong with your multiarch setup if you are using the 64 bit opensuse

http://www.pilotlogic.com/sitejoom/index.php/wiki?id=398

**Comment by daschaffert** [comment]
when running the lin-vst-server.exe, no matter wich one (32/64) wine is
starting up but then fails no matter wich plugin I try to load. Would a
wine dbg Log for you be usefull ?

2017-09-04 6:32 GMT+02:00 osxmidi <notifications@github.com>:

**Comment by daschaffert** [comment]
no I can show you the DBG-Log seems it has to do something with ARGC ARGV -
well I'm not a coder but maybe you can help me anyway :-)

Backtrace:
=>0 0x00007f27cdaa49b4 __cfree+0x14() in libc.so.6 (0x000000000022f920)
  1 0x00007f27ccf5df24 _ZN18RemotePluginServerC1ESs+0x6a3() in
lin-vst-server (0x000000000022f920)
  2 0x00007f27ccf5b0fe _ZN15RemoteVSTServerC1ESsP7AEffectSs+0x2d() in
lin-vst-server (0x000000000022fa00)
  3 0x00007f27ccf5bc97 WinMain+0x7a6() in lin-vst-server
(0x000000000022faa0)
  4 0x00007f27ccf57f5b main+0x8a(argc=<is not available>, argv=<is not
available>)
[/home/abuild/rpmbuild/BUILD/wine-2.15/dlls/winecrt0/exe_main.c:49] in
lin-vst-server (0x0000000000000001)
  5 0x00007f27ccf60322 __wine_spec_exe_entry+0xa1(peb=<is not available>)
[/home/abuild/rpmbuild/BUILD/wine-2.15/dlls/winecrt0/exe_entry.c:36] in
lin-vst-server (0x00007f27ce3dc5b0)
  6 0x000000007b47c967 in kernel32 (+0x5c966) (0x00007fffff7ef000)
  7 0x000000007bca36ee in ntdll (+0x836ed) (0x00007ffef0874b60)
  8 0x000000007bc9c01a RtlRaiseException+0x85() in ntdll
(0x00007ffef0874b60)
  9 0x000000007bc685b0 in ntdll (+0x485af) (0x00007ffef0874b60)
  10 0x00007f27ce028643 wine_call_on_stack+0x12() in libwine.so.1
(0x00007ffef0874b60)
  11 0x00007f27ce028699 wine_switch_to_stack+0x8() in libwine.so.1
(0x00007fffff7e8000)
  12 0x000000007bc6fbec LdrInitializeThunk+0x50b() in ntdll
(0x00007fffff7e8000)
  13 0x000000007b483496 __wine_kernel_init+0x905() in kernel32
(0x00007ffef08752f0)
  14 0x000000007bc70e82 __wine_process_init+0x171() in ntdll
(0x00007ffef0876020)
  15 0x00007f27ce0271b2 wine_init+0x2b1() in libwine.so.1
(0x00007ffef08760a0)
  16 0x000000007c000e9c main+0x8b() in <wine-loader> (0x00007ffef0876638)
  17 0x00007f27cda496e5 __libc_start_main+0xf4() in libc.so.6
(0x0000000000000000)


2017-09-04 6:32 GMT+02:00 osxmidi <notifications@github.com>:

**Comment by osxmidi** [comment]
I think that error maybe caused by different LinVst versions being mixed up.

For new versions of LinVst, the vst plugins need to be (name) converted again using the new linvst.so.

The lin-vst-server.exe (lin-vst-server32.exe) and linvst.so need to be version matched.

**Comment by daschaffert** [comment]
Thats not possible. Its a fresh installiert oft the OS (from yesterday
linvst not included) and linvst fresh from git also yesterday

Am 05.09.2017 06:02 schrieb "osxmidi" <notifications@github.com>:

**Comment by osxmidi** [comment]
Seeing that it's not a version problem, then it maybe looks like a Wine problem.

argc and argv errors would suggest some sort of Wine app problem.

lin-vst-server.exe and lin-vst-server32.exe are Wine apps.

linvst.so is a Linux shared library.

linvst.so starts and connects to lin-vst-server.exe (lin-vst-server32.exe) and it seems that lin-vst-server.exe is not starting normally or some reason.

I havn't seen this problem before so it's hard to say what it definitely is.

**Comment by osxmidi** [comment]
winecrt0/exe_main.c handles the arguments, argc and argv.

So it seems that something is wrong with winecrt0

**Comment by daschaffert** [comment]
ok I dived deeper in to that problem -  and came to an strange solution!

If I start wineserver -f manually bevor loading the plugin then it is
working ...

I dont know why, but somhow loading the .so-file doesnt tricker wineserver
to start!

2017-09-05 10:23 GMT+02:00 osxmidi <notifications@github.com>:

**Comment by osxmidi** [comment]
Where is your wineserver located?

Maybe it needs the WINESERVER environmental variable to be set.

https://forum.winehq.org/viewtopic.php?f=8&t=29122
