### ISSUE TITLE
Works on Manjaro but doesn't work on Arch

### ISSUE THREAD

**Issue by slavikator** [osxmidi/LinVst#180]
Maybe I can get help here? How can I find out why it doesn't work on fresh installed Arch?

I have tested it on Manjaro and it just works after installing without any extra tasks. Doing the same on Arch, the vst plugin is trying to load, it times out and doesn't appear in the list of plugins.

**Comment by osxmidi** [comment]
Hi,

If Arch is running Wine Staging 6.3 then Wine Staging 6.3 has bugs.

If it's not that then I'd need a Terminal output to see if any errors are reported.

The way to do that is to start the Daw using the Terminal, I use Reaper for Terminal output but Ardour might do it as well.

Manjaro and Debian seem ok with Wine staging 6.2.

**Comment by slavikator** [comment]
Indeed, Wine on Arch is 6.3-1, on Manjaro 6.2-1.

Starting Ardour in the terminal doesn't tell much:

`Ardour6.6.0 (built using 6.6 and GCC version 10.2.0)
Ardour: [INFO]: Your system is configured to limit Ardour to 524288 open files
Ardour: [INFO]: Loading system configuration file /etc/ardour6/system_config
Ardour: [INFO]: Loading user configuration file /home/slavikator/.config/ardour6/config
Ardour: [INFO]: CPU vendor: GenuineIntel
Ardour: [INFO]: CPU brand: Intel(R) Xeon(R) CPU           X3360  @ 2.83GHz
Ardour: [INFO]: Using SSE optimized routines
Ardour: [INFO]: Loading plugin meta data file /usr/share/ardour6/plugin_metadata/plugin_tags
Ardour: [INFO]: Loading default ui configuration file /etc/ardour6/default_ui_config
Ardour: [INFO]: Loading user ui configuration file /home/slavikator/.config/ardour6/ui_config
Ardour: [INFO]: Loading 451 MIDI patches from /usr/share/ardour6/patchfiles
Ardour: [INFO]: Loading color file /usr/share/ardour6/themes/dark-ardour.colors
Ardour: [INFO]: Loading ui configuration file /etc/ardour6/clearlooks.rc
Ardour: [INFO]: Loading bindings from /etc/ardour6/ardour.keys
Loading ui configuration file /etc/ardour6/clearlooks.rc
Found nothing along /home/slavikator/.config/ardour6/templates:/usr/share/ardour6/templates
Scanning folders for bundled LV2s: /usr/lib/ardour6/LV2
Set cursor set to default
 loading from /home/slavikator/Music/Ardour/test as test templ  is_new 0 bp 0
`

**Comment by slavikator** [comment]
Thanks for helping. I have downgraded wine to 6.2 and now it works fine.

**Comment by vlig** [comment]
The same is for me.

**Comment by slavikator** [comment]
Wine 6.4 - works well

**Comment by vlig** [comment]
I'm afraid it's not working again with the wine 6.5 staging. I've late for an important voice conversation due to it (

**Comment by slavikator** [comment]
> I'm afraid it's not working again with the wine 6.5 staging. I've been late for an important voice conversation recently due to it (

This time, plugins I use even can't start standalone. Definitely wine issue, not LinVst, I assume.
