### ISSUE TITLE
rktools and Waves

### ISSUE THREAD

**Issue by zac-davis** [osxmidi/LinVst#181]
I just wanted to ask if rktools is required for Waves central since I can't seem to find an executable anywhere. If it isn't necessary what steps should be taken instead, or, if it is, where can I find an executable? Additionally, I don't see a waveshellxxxxx.dll to apply a wrapper to, according to the readme. Has something changed with Waves that prevents it from opening on Linux systems?

**Comment by osxmidi** [comment]
> I just wanted to ask if rktools is required for Waves central since I can't seem to find an executable anywhere. If it isn't necessary what steps should be taken instead, or, if it is, where can I find an executable? Additionally, I don't see a waveshellxxxxx.dll to apply a wrapper to, according to the readme. Has something changed with Waves that prevents it from opening on Linux systems?

Waves Central started to use Powershell and Powershell isn't compatible with Wine.

I don't know if earlier versions of Waves Central (that don't use Powershell) still work.

**Comment by zac-davis** [comment]
I see, thanks! Have you thought about removing the waves folder or amending the readme? Or is it still there for the older versions that could work?
