### ISSUE TITLE
TestVst: failed to start

### ISSUE THREAD

**Issue by Majora320** [osxmidi/LinVst#183]
Up until a month or two ago, LinVst worked perfectly on my machine, but recently it has stopped working -- my DAW just hangs indefinitely when trying to load LinVst'd plugins. I downloaded TestVst to try to get some more information on it, but running it causes this error:

```
$ pwd
/home/xxx/TestVst
$ echo $WINEARCH
win64
$ ./testvst.exe ~/.vst/Pulse.dll
002c:fixme:ver:GetCurrentPackageId (000000000032FDB0 0000000000000000): stub
wine: failed to start L"Z:\\home\\xxx\\TestVst\\testvst.exe.so"
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.
00f4:fixme:ver:GetCurrentPackageId (000000000032FDB0 0000000000000000): stub
003c:fixme:ver:GetCurrentPackageId (000000000032FDB0 0000000000000000): stub
``` 

I'm on Arch Linux running wine 6.5 (stable).

**Comment by osxmidi** [comment]
> Up until a month or two ago, LinVst worked perfectly on my machine, but recently it has stopped working -- my DAW just hangs indefinitely when trying to load LinVst'd plugins. I downloaded TestVst to try to get some more information on it, but running it causes this error:
> 
> ```
> $ pwd
> /home/xxx/TestVst
> $ echo $WINEARCH
> win64
> $ ./testvst.exe ~/.vst/Pulse.dll
> 002c:fixme:ver:GetCurrentPackageId (000000000032FDB0 0000000000000000): stub
> wine: failed to start L"Z:\\home\\xxx\\TestVst\\testvst.exe.so"
> Application could not be started, or no application associated with the specified file.
> ShellExecuteEx failed: File not found.
> 00f4:fixme:ver:GetCurrentPackageId (000000000032FDB0 0000000000000000): stub
> 003c:fixme:ver:GetCurrentPackageId (000000000032FDB0 0000000000000000): stub
> ```
> 
> I'm on Arch Linux running wine 6.5 (stable).

Hi.

Maybe try installing LinVst again and reconverting the plugins using linvstconvert.

I also had that testvst error but now I don't, maybe it's something to do with different Wine versions.

There are 2 ways to start testvst.

Change into the directory where testvst.exe is and then

./testvst.exe "pathtoplug"

or

wine testvst.exe.so "pathtoplug"

the last one should work.

**Comment by Majora320** [comment]
I reinstalled LinVst, deleted my .wine folder and reconverted the plugins and tried both commands, but the same thing happened. Might be a wine version thing; the only wine binaries that Arch provides are those for 6.5, but I can try building an earlier version from source if that would help in narrowing down the problem (though that might take a while).

**Comment by FluxTape** [comment]
LinVST on Arch with wine 6.5 isn't working for me either, downgrading to wine 6.4 fixed my issues.

**Comment by Majora320** [comment]
This does indeed fix it for me. However, it might be worth looking into why this breaks on the latest wine version, for future compatibility.

**Comment by slavikator** [comment]
Doesn't work on Arch with wine-6.5-2

**Comment by Majora320** [comment]
That doesn't work for me with wine 6.5; I also tried building from source, and that didn't work either (though, oddly enough, TestVst built from source worked perfectly).

**Comment by megamaced** [comment]
I confirm this issue on openSUSE Tumbleweed using wine 6.5. Was working fine in wine 6.4

**Comment by slavikator** [comment]
> I got wine 6.5-2 from https://archlinux.org/packages/multilib/x86_64/wine/ and it seems to work ok with Manjaro.

I have tried Manjaro and it works. But on my main Arch system - doesn't. 
So, what the difference could be?

**Comment by osxmidi** [comment]
> > I got wine 6.5-2 from https://archlinux.org/packages/multilib/x86_64/wine/ and it seems to work ok with Manjaro.
> 
> I have tried Manjaro and it works. But on my main Arch system - doesn't.
> So, what the difference could be?

It seems to work on Manjaro, but it's not working normally.

When I looked at the pid of the linvst server, there were 2 pids (there should be just one) which shows something is strange somewhere with Wine 6.5.

From what I've seen (based on other Wine users), there seems to be a wine app loading bug in Wine 6.5, problems with start.exe starting etc etc.

That would be 2 app loading bugs, one in Wine 6.3 and another in Wine 6.5.

Apparently the bug is fixed, so Wine 6.6 should be ok (maybe).

**Comment by slavikator** [comment]
> > > I got wine 6.5-2 from https://archlinux.org/packages/multilib/x86_64/wine/ and it seems to work ok with Manjaro.
> > 
> > 
> > I have tried Manjaro and it works. But on my main Arch system - doesn't.
> > So, what the difference could be?
> 
> It seems to work on Manjaro, but it's not working normally.
> 
> When I looked at the pid of the linvst server, there were 2 pids (there should be just one) which shows something is strange somewhere with Wine 6.5.
> 
> 2 linvst servers are getting loaded instead of the usual one.
> 
> From what I've seen (based on other Wine users https://forum.winehq.org/viewtopic.php?t=35106&p=132349), there seems to be a wine app loading bug in Wine 6.5, problems with start.exe starting etc etc https://bugs.winehq.org/show_bug.cgi?id=50867.
> 
> That would be 2 app loading bugs, one in Wine 6.3 and another in Wine 6.5.
> 
> Apparently the bug is fixed, so Wine 6.6 should be ok (maybe).
> 
> The difference between Manjaro and Arch, I don't know, maybe some different libraries.

Strange behavior. I have also tried wine 6.4 on Arch and the plugin doesn't work now. Before updating it to 6.5, it worked. So, updating wine and then downgrading to working version break something and it doesn't work anymore.

**Comment by osxmidi** [comment]
> > > > I got wine 6.5-2 from https://archlinux.org/packages/multilib/x86_64/wine/ and it seems to work ok with Manjaro.
> > > 
> > > 
> > > I have tried Manjaro and it works. But on my main Arch system - doesn't.
> > > So, what the difference could be?
> > 
> > 
> > It seems to work on Manjaro, but it's not working normally.
> > When I looked at the pid of the linvst server, there were 2 pids (there should be just one) which shows something is strange somewhere with Wine 6.5.
> > 2 linvst servers are getting loaded instead of the usual one.
> > From what I've seen (based on other Wine users https://forum.winehq.org/viewtopic.php?t=35106&p=132349), there seems to be a wine app loading bug in Wine 6.5, problems with start.exe starting etc etc https://bugs.winehq.org/show_bug.cgi?id=50867.
> > That would be 2 app loading bugs, one in Wine 6.3 and another in Wine 6.5.
> > Apparently the bug is fixed, so Wine 6.6 should be ok (maybe).
> > The difference between Manjaro and Arch, I don't know, maybe some different libraries.
> 
> Strange behavior. I have also tried wine 6.4 on Arch and the plugin doesn't work now. Before updating it to 6.5, it worked. So, updating wine and then downgrading to working version break something and it doesn't work anymore.

Did you run winecfg to auto update your wine prefix?

**Comment by slavikator** [comment]
yes, also tried to remove the wine prefix and install plugins on a new one.

**Comment by slavikator** [comment]
> > > > > I got wine 6.5-2 from https://archlinux.org/packages/multilib/x86_64/wine/ and it seems to work ok with Manjaro.
> > > > 
> > > > 
> > > > I have tried Manjaro and it works. But on my main Arch system - doesn't.
> > > > So, what the difference could be?
> > > 
> > > 
> > > It seems to work on Manjaro, but it's not working normally.
> > > When I looked at the pid of the linvst server, there were 2 pids (there should be just one) which shows something is strange somewhere with Wine 6.5.
> > > 2 linvst servers are getting loaded instead of the usual one.
> > > From what I've seen (based on other Wine users https://forum.winehq.org/viewtopic.php?t=35106&p=132349), there seems to be a wine app loading bug in Wine 6.5, problems with start.exe starting etc etc https://bugs.winehq.org/show_bug.cgi?id=50867.
> > > That would be 2 app loading bugs, one in Wine 6.3 and another in Wine 6.5.
> > > Apparently the bug is fixed, so Wine 6.6 should be ok (maybe).
> > > The difference between Manjaro and Arch, I don't know, maybe some different libraries.
> > 
> > 
> > Strange behavior. I have also tried wine 6.4 on Arch and the plugin doesn't work now. Before updating it to 6.5, it worked. So, updating wine and then downgrading to working version break something and it doesn't work anymore.
> 
> Did you run winecfg to auto update your wine prefix with the installed Wine version?

yes, also tried to remove the wine prefix and install plugins on a new one.

**Comment by Schroedingers-Cat** [comment]
> Apparently the bug is fixed, so Wine 6.6 should be ok (maybe).  

That doesn't seem to be the case over here with the recently released Win 6.6:
```
username@t430:$ cat /proc/version
Linux version 5.4.0-70-generic (buildd@lcy01-amd64-004) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021

username@t430:$ wine --version
wine-6.6

username@t430:$ ./testvst.exe "/home/username/.vst/2caudio/2C-Aether.dll" 
wine: failed to start L"Z:\\home\\username\\Downloads\\TestVst\\testvst.exe.so"
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.
```

**Comment by osxmidi** [comment]
> > Apparently the bug is fixed, so Wine 6.6 should be ok (maybe).
> 
> That doesn't seem to be the case over here with the recently released Win 6.6:
> 
> ```
> username@t430:$ cat /proc/version
> Linux version 5.4.0-70-generic (buildd@lcy01-amd64-004) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021
> 
> username@t430:$ wine --version
> wine-6.6
> 
> username@t430:$ ./testvst.exe "/home/username/.vst/2caudio/2C-Aether.dll" 
> wine: failed to start L"Z:\\home\\username\\Downloads\\TestVst\\testvst.exe.so"
> Application could not be started, or no application associated with the specified file.
> ShellExecuteEx failed: File not found.
> ```

wine testvst.exe.so "pathtoplug"

should be ok.

Something seems to be different about how newer versions of wine loads programs.

**Comment by Schroedingers-Cat** [comment]
> wine testvst.exe.so "pathtoplug"
> should be ok.  

That brings exactly the same error message as before.

**Comment by osxmidi** [comment]
> > wine testvst.exe.so "pathtoplug"
> > should be ok.
> 
> That brings exactly the same error message as before.

Wine 6.6 seems to need wine64 and not wine anymore to load winegcc made apps (which LinVst is made with).

Very Strange.

Anyway I have got LinVst and TestVst running with Wine 6.6 and Manjaro.

I'll attach the zip.

[LinVst-4.1-Debian-Stretch-Wine-6.6-Manjaro.zip](https://github.com/osxmidi/LinVst/files/6291367/LinVst-4.1-Debian-Stretch-Wine-6.6-Manjaro.zip)

**Comment by Schroedingers-Cat** [comment]
@osxmidi I can confirm that this fixed it for my Ubuntu 20.04/Wine6.6 as well. Thanks a lot!

**Comment by Schroedingers-Cat** [comment]
Weird - I used to have some outputs from testvst.exe when running a plugin. Even when trying to run a .dll that doesn't actually exist on the filesystem, I won't get an error message. All I get is some "fixme:font:get_name_record_codepage encoding 20 not handled, platform 1." and then nothing until I press enter which gives control back to the terminal.  

If the given plugin exists, the plugin window will be opened, that's why my first reaction was that it's fixed. But it seems that we don't receive all messsages we did with previous versions?

**Comment by osxmidi** [comment]
> Weird - I used to have some outputs from testvst.exe when running a plugin. Even when trying to run a .dll that doesn't actually exist on the filesystem, I won't get an error message. All I get is some "fixme:font:get_name_record_codepage encoding 20 not handled, platform 1." and then nothing until I press enter which gives control back to the terminal.
> 
> If the given plugin exists, the plugin window will be opened, that's why my first reaction was that it's fixed. But it seems that we don't receive all messsages we did with previous versions?

I tested it on Manjaro.

./testvst.exe "path-to-plugin"

gives the inputs and outputs

wine ./testvst.exe.so "path-to-plugin"

doesn't

It looks like it's something Wine is doing to take over the output when it's run like wine ./testvst.exe.so "path-to-plugin"

**Comment by Schroedingers-Cat** [comment]
True, it's the `wine testvst.exe.so 'path-to-plugin'` vs `./testvst.exe 'path-to-plugin'`, Thanks a lot, agian!

**Comment by osxmidi** [comment]
> True, it's the `wine testvst.exe.so 'path-to-plugin'` vs `./testvst.exe 'path-to-plugin'`, Thanks a lot, agian!

I made a mistake earlier.

With the way Wine-6.6 is now working it should be

wine64 testvst.exe.so 'path-to-plugin'

**Comment by Schroedingers-Cat** [comment]
On my system, it makes no difference whether I run `wine64 testvst.exe.so 'path-to-plugin'` or `wine testvst.exe.so 'path-to-plugin'`.

**Comment by megamaced** [comment]
using the latest LinVST 4.2 (manjaro) on openSUSE Tumbleweed wine 6.6 is working cheers

**Comment by Majora320** [comment]
Looks to be working perfectly now for me :) I'll go ahead and close this issue for now.
