### ISSUE TITLE
LinVst4.2 problems on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by rolodoom** [osxmidi/LinVst#184]
I upgraded to LinVst4.2.. Vstplugins stopped working. Take a long time to scan from VST host programs. Some times it didn't finish the initial scan. I did re-scan all Vstplugins folders with linvstconvert.

I  removed it and downgraded to LinVst 4.1 and re-scanned. Everything back to normal.

OS: Ubuntu 20.04.2 LTS x86_64 
Kernel: 5.4.0-72-lowlatency
Wine: wine-5.0 (Ubuntu 5.0-3ubuntu1)

**Comment by osxmidi** [comment]
> I upgraded to LinVst4.2.. Vstplugins stopped working. Take a long time to scan from VST host programs. Some times it didn't finish the initial scan. I did re-scan all Vstplugins folders with linvstconvert.
> 
> I removed it and downgraded to LinVst 4.1 and re-scanned. Everything back to normal.
> 
> OS: Ubuntu 20.04.2 LTS x86_64
> Kernel: 5.4.0-72-lowlatency
> Wine: wine-5.0 (Ubuntu 5.0-3ubuntu1)

Hi,

I'm not sure what it could be.

LinVst 4.2 mainly has changes to linvstconvert.

What daw are you using?

I'll try to test it with that daw.

**Comment by osxmidi** [comment]
I tested LinVst 4.2 using Kontakt and Absynth with Ubuntu 20.04 and Wine Staging 5.20 and it seemed ok as far as I could tell.

**Comment by rolodoom** [comment]
Hello there. The the time delay during scan is present on Reaper and Carla.

Maybe is the different version of wine? I'm using the default version that came with Ubuntu .

I'll stick to 4.1  for now 'cause it's just working for me.

Thanks for the quick answer.

**Comment by osxmidi** [comment]
> Hello there. The the time delay during scan is present on Reaper and Carla.
> 
> Maybe is the different version of wine? I'm using the default version that came with Ubuntu .
> 
> I'll stick to 4.1 for now 'cause it's just working for me.
> 
> Thanks for the quick answer.

I've put up a Ubuntu 20.04 Wine Staging 5.20 made version on the releases page.

**Comment by rolodoom** [comment]
Hi. I just tested using WineHQ wine-6.6 (Staging) and it worked perfectly!!

Thanks.
