### ISSUE TITLE
[VST] Kvlt Drums 2

### ISSUE THREAD

**Issue by nilzeronull** [osxmidi/LinVst#185]
What's up.

I'm trying to get Kvlt Drums 2 to work. Already got gdiplus installed and set up an override for d2d1 (according to an md5 sum I saw in the airwave repo).
Windows shows up just fine, however the Tooltips and menus are blank:

![2021-05-08-104407_811x571_scrot](https://user-images.githubusercontent.com/61620488/117532982-5fd5fe80-afea-11eb-825d-7c4c0babbcb5.png)

I'm on Bitwig 2.4.X, arch linux.

Any ideas?

**Comment by osxmidi** [comment]
> What's up.
> 
> I'm trying to get Kvlt Drums 2 to work. Already got gdiplus installed and set up an override for d2d1 (according to an md5 sum I saw in the airwave repo).
> Windows shows up just fine, however the Tooltips and menus are blank:
> 
> ![2021-05-08-104407_811x571_scrot](https://user-images.githubusercontent.com/61620488/117532982-5fd5fe80-afea-11eb-825d-7c4c0babbcb5.png)
> 
> I'm on Bitwig 2.4.X, arch linux.
> 
> Any ideas?

Hi,

I can't seem to get a demo of it to try.

It seems to be missing it's fonts.

Maybe it relies on corefonts.

"winetricks corefonts"

**Comment by osxmidi** [comment]
> Heya.
> 
> Installed the corefonts -- sadly didn't change anything as far as the UI is concerned.
> 
> Can I strace the plugin somehow?

Debugging Wine isn't easy.

It seems Wine is not handling the fonts for some reason.

You can see what dlls the plugin it is using by

"strings vstname.dll | grep -i dll"

**Comment by osxmidi** [comment]
Sometimes the overrides might be causing the problem.

**Comment by nilzeronull** [comment]
Pardon the delay. As for disabling the overrides, they sadly don't change anything.

Here's the dll list:


```bash
❯ strings KVLT\ Drums\ II.dll| rg -i dll
netapi32.dll
MAPI32.dll
kernel32.dll
user32.dll
Shell32.dll
ntdll
iphlpapi.dll
Hd2d1.dll
DWrite.dll
SHCore.dll
Wmvcore.dll
KVLT Drums II.dll
KERNEL32.dll
USER32.dll
GDI32.dll
COMDLG32.dll
ADVAPI32.dll
SHELL32.dll
ole32.dll
OLEAUT32.dll
WININET.dll
WS2_32.dll
VERSION.dll
SHLWAPI.dll
WINMM.dll
dbghelp.dll
IMM32.dll```
