### ISSUE TITLE
Freeverb2.dll has no UI in LinVst

### ISSUE THREAD

**Issue by Monsterovich** [osxmidi/LinVst#186]
![Freeverb](https://user-images.githubusercontent.com/3750982/117706806-0a5a4700-b1ce-11eb-92d8-2bb28cd1829b.png)

Some plugins like freeverb2 have no clientside UI which means LinVst should draw simple UI for the plugin's controls the same way other ladspa plugins do.

Something like this:
![](https://user-images.githubusercontent.com/3750982/117706998-48f00180-b1ce-11eb-8e5a-43104df3a8f2.png)

In order to use this plugin (freeverb2) I have to export presets and edit plugin settings manually which is not acceptable.

**Comment by osxmidi** [comment]
> ![Freeverb](https://user-images.githubusercontent.com/3750982/117706806-0a5a4700-b1ce-11eb-92d8-2bb28cd1829b.png)
> 
> Some plugins like freeverb2 have no clientside UI which means LinVst should draw simple UI for the plugin's controls the same way other ladspa plugins do.
> 
> Something like this:
> ![](https://user-images.githubusercontent.com/3750982/117706998-48f00180-b1ce-11eb-8e5a-43104df3a8f2.png)
> 
> In order to use this plugin (freeverb2) I have to export presets and edit plugin settings manually which is not acceptable.

Reaper does put up a default slider UI.

I don't know why Audacity doesn't.

**Comment by Monsterovich** [comment]
@osxmidi Thank you! It works fine. 

> Then remove the checkmark from the "Enable graphical interface" checkbox unchecked checkbox Enable graphical interface and click OK.

You can disable this checkbox (and set it to in-active state) for the plugins which don't have UI at all.
