### ISSUE TITLE
LinVst 4.2 and 4.5 does not work on Ubuntu 20.04

### ISSUE THREAD

**Issue by pramuko** [osxmidi/LinVst#188]
I installed LinVst 4.5 deb and then 4.2 zip on Ubuntu 20.04. Both produced so wrappers but none worked from Carla. Didn't have this issue with 4.1 deb.

**Comment by osxmidi** [comment]
> I installed LinVst 4.5 deb and then 4.2 zip on Ubuntu 20.04. Both produced so wrappers but none worked from Carla. Didn't have this issue with 4.1 deb.

I changed to making the deb packages using Manjaro and I think they should be made using Debian, I'll update it.
