### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by ShawkMusic** [osxmidi/LinVst#189]
When I try to install LinVst on Linux 5.10.36-2-MANJARO on pamac, I get an error. Here's the full build output:

```
Preparing...
Cloning linvst build files...
Checking linvst dependencies...
Resolving dependencies...
Checking inter-conflicts...
Checking keyring...
Checking integrity...
Loading packages files...
Checking file conflicts...
Checking available disk space...
Installing bison (3.7.6-1)...
Installing flex (2.6.4-3)...
Installing make (4.3-3)...
Installing patch (2.7.6-8)...
Installing fakeroot (1.25.3-2)...
Installing autoconf (2.71-1)...
Installing automake (1.16.3-1)...
Running post-transaction hooks...
Arming ConditionNeedsUpdate...
Updating the info directory file...

Building linvst...
==> Making package: linvst 4.5.r13.81f84be-1 (Fri 28 May 2021 10:17:01 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating LinVst git repo...
Fetching origin
  -> Found vstsdk3611_22_10_2018_build_34.zip
==> Validating source files with sha256sums...
    LinVst ... Skipped
    vstsdk3611_22_10_2018_build_34.zip ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of LinVst git repo...
Cloning into 'LinVst'...
done.
  -> Extracting vstsdk3611_22_10_2018_build_34.zip with bsdtar
==> Starting prepare()...
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
make: Makefile-64-32bit: No such file or directory
make: *** No rule to make target 'Makefile-64-32bit'.  Stop.
==> ERROR: A failure occurred in build().
    Aborting...

Preparing...
Cloning linvst3 build files...
Checking linvst3 dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building linvst3...
==> Making package: linvst3 1.8.2-1 (Fri 28 May 2021 10:17:32 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found LinVst3-1.8.2-Debian-Buster.zip
  -> Updating ArchStudioUtils git repo...
Fetching origin
==> Validating source files with sha256sums...
    LinVst3-1.8.2-Debian-Buster.zip ... Passed
    ArchStudioUtils ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting LinVst3-1.8.2-Debian-Buster.zip with bsdtar
  -> Creating working copy of ArchStudioUtils git repo...
Cloning into 'ArchStudioUtils'...
done.
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat '/var/tmp/pamac-build-gabriels/linvst3/src/ArchStudioUtils/w2lvst3': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...

Preparing...
Cloning linvst3 build files...
Checking linvst3 dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building linvst3...
==> Making package: linvst3 1.8.2-1 (Fri 28 May 2021 10:17:46 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found LinVst3-1.8.2-Debian-Buster.zip
  -> Updating ArchStudioUtils git repo...
Fetching origin
==> Validating source files with sha256sums...
    LinVst3-1.8.2-Debian-Buster.zip ... Passed
    ArchStudioUtils ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting LinVst3-1.8.2-Debian-Buster.zip with bsdtar
  -> Creating working copy of ArchStudioUtils git repo...
Cloning into 'ArchStudioUtils'...
done.
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat '/var/tmp/pamac-build-gabriels/linvst3/src/ArchStudioUtils/w2lvst3': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...

Preparing...
Cloning linvst build files...
Checking linvst dependencies...
Resolving dependencies...
Checking inter-conflicts...

Building linvst...
==> Making package: linvst 4.5.r13.81f84be-1 (Fri 28 May 2021 10:22:32 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating LinVst git repo...
Fetching origin
  -> Found vstsdk3611_22_10_2018_build_34.zip
==> Validating source files with sha256sums...
    LinVst ... Skipped
    vstsdk3611_22_10_2018_build_34.zip ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of LinVst git repo...
Cloning into 'LinVst'...
done.
  -> Extracting vstsdk3611_22_10_2018_build_34.zip with bsdtar
==> Starting prepare()...
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
make: Makefile-64-32bit: No such file or directory
make: *** No rule to make target 'Makefile-64-32bit'.  Stop.
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by osxmidi** [comment]
> 
> 
> When I try to install LinVst on Linux 5.10.36-2-MANJARO on pamac, I get an error. Here's the full build output:
> 
> ```
> Preparing...
> Cloning linvst build files...
> Checking linvst dependencies...
> Resolving dependencies...
> Checking inter-conflicts...
> Checking keyring...
> Checking integrity...
> Loading packages files...
> Checking file conflicts...
> Checking available disk space...
> Installing bison (3.7.6-1)...
> Installing flex (2.6.4-3)...
> Installing make (4.3-3)...
> Installing patch (2.7.6-8)...
> Installing fakeroot (1.25.3-2)...
> Installing autoconf (2.71-1)...
> Installing automake (1.16.3-1)...
> Running post-transaction hooks...
> Arming ConditionNeedsUpdate...
> Updating the info directory file...
> 
> Building linvst...
> ==> Making package: linvst 4.5.r13.81f84be-1 (Fri 28 May 2021 10:17:01 AM)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Updating LinVst git repo...
> Fetching origin
>   -> Found vstsdk3611_22_10_2018_build_34.zip
> ==> Validating source files with sha256sums...
>     LinVst ... Skipped
>     vstsdk3611_22_10_2018_build_34.zip ... Passed
> ==> Removing existing $srcdir/ directory...
> ==> Extracting sources...
>   -> Creating working copy of LinVst git repo...
> Cloning into 'LinVst'...
> done.
>   -> Extracting vstsdk3611_22_10_2018_build_34.zip with bsdtar
> ==> Starting prepare()...
> ==> Starting pkgver()...
> ==> Removing existing $pkgdir/ directory...
> ==> Starting build()...
> make: Makefile-64-32bit: No such file or directory
> make: *** No rule to make target 'Makefile-64-32bit'.  Stop.
> ==> ERROR: A failure occurred in build().
>     Aborting...
> 
> Preparing...
> Cloning linvst3 build files...
> Checking linvst3 dependencies...
> Resolving dependencies...
> Checking inter-conflicts...
> 
> Building linvst3...
> ==> Making package: linvst3 1.8.2-1 (Fri 28 May 2021 10:17:32 AM)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Found LinVst3-1.8.2-Debian-Buster.zip
>   -> Updating ArchStudioUtils git repo...
> Fetching origin
> ==> Validating source files with sha256sums...
>     LinVst3-1.8.2-Debian-Buster.zip ... Passed
>     ArchStudioUtils ... Skipped
> ==> Removing existing $srcdir/ directory...
> ==> Extracting sources...
>   -> Extracting LinVst3-1.8.2-Debian-Buster.zip with bsdtar
>   -> Creating working copy of ArchStudioUtils git repo...
> Cloning into 'ArchStudioUtils'...
> done.
> ==> Removing existing $pkgdir/ directory...
> ==> Entering fakeroot environment...
> ==> Starting package()...
> install: cannot stat '/var/tmp/pamac-build-gabriels/linvst3/src/ArchStudioUtils/w2lvst3': No such file or directory
> ==> ERROR: A failure occurred in package().
>     Aborting...
> 
> Preparing...
> Cloning linvst3 build files...
> Checking linvst3 dependencies...
> Resolving dependencies...
> Checking inter-conflicts...
> 
> Building linvst3...
> ==> Making package: linvst3 1.8.2-1 (Fri 28 May 2021 10:17:46 AM)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Found LinVst3-1.8.2-Debian-Buster.zip
>   -> Updating ArchStudioUtils git repo...
> Fetching origin
> ==> Validating source files with sha256sums...
>     LinVst3-1.8.2-Debian-Buster.zip ... Passed
>     ArchStudioUtils ... Skipped
> ==> Removing existing $srcdir/ directory...
> ==> Extracting sources...
>   -> Extracting LinVst3-1.8.2-Debian-Buster.zip with bsdtar
>   -> Creating working copy of ArchStudioUtils git repo...
> Cloning into 'ArchStudioUtils'...
> done.
> ==> Removing existing $pkgdir/ directory...
> ==> Entering fakeroot environment...
> ==> Starting package()...
> install: cannot stat '/var/tmp/pamac-build-gabriels/linvst3/src/ArchStudioUtils/w2lvst3': No such file or directory
> ==> ERROR: A failure occurred in package().
>     Aborting...
> 
> Preparing...
> Cloning linvst build files...
> Checking linvst dependencies...
> Resolving dependencies...
> Checking inter-conflicts...
> 
> Building linvst...
> ==> Making package: linvst 4.5.r13.81f84be-1 (Fri 28 May 2021 10:22:32 AM)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Updating LinVst git repo...
> Fetching origin
>   -> Found vstsdk3611_22_10_2018_build_34.zip
> ==> Validating source files with sha256sums...
>     LinVst ... Skipped
>     vstsdk3611_22_10_2018_build_34.zip ... Passed
> ==> Removing existing $srcdir/ directory...
> ==> Extracting sources...
>   -> Creating working copy of LinVst git repo...
> Cloning into 'LinVst'...
> done.
>   -> Extracting vstsdk3611_22_10_2018_build_34.zip with bsdtar
> ==> Starting prepare()...
> ==> Starting pkgver()...
> ==> Removing existing $pkgdir/ directory...
> ==> Starting build()...
> make: Makefile-64-32bit: No such file or directory
> make: *** No rule to make target 'Makefile-64-32bit'.  Stop.
> ==> ERROR: A failure occurred in build().
>     Aborting...
> ```

Those Arch etc packages are out of date and would need to be updated.

I don't maintain them.

I'd suggest to use the Manjaro release on the Releases page.

**Comment by osxmidi** [comment]
It's out of date.

I don't maintain it.

There is a Manjaro version of LinVst3 4.5 at https://github.com/osxmidi/LinVst3/releases

**Comment by ShawkMusic** [comment]
Yeah I ended up using the package `linvst-bin` and it worked. It seems to be up to date as well (version 4.5)
