### ISSUE TITLE
It seem to work only with plugins named without uppercase caracters.

### ISSUE THREAD

**Issue by lolgab** [osxmidi/LinVst#19]
I have a plugin called Emissary.so - Emissary.dll and Ardour doesn't see it.. If I rename it emissary.so and emissary.dll it works nicely.

Ps. The new embedded mode is great :1st_place_medal: :+1:

**Comment by lolgab** [comment]
I am using LinVst precompiled 1.7.6

**Comment by osxmidi** [comment]
Thanks.

I've tried the 64 bit Ignite Amps Emissary.dll with Ardour 5.11.4 and I can't seem to replicate the problem.

Maybe a space or some other character accidentally got into the filename somehow?

**Comment by lentferj** [comment]
I also have plugins working with only small letter, only capitals and mixed names.

**Comment by osxmidi** [comment]
I can't seem to duplicate it on my test setup, so I'll try some other setups.

**Comment by lentferj** [comment]
Maybe I wasn't clear: I do NOT have the problem the OP described. All plugins with any combination of capital and small letters work for me (in Ardour, Mixbus and Bitwig). I am on Debian 9 (with wine from winehq repository) and self-compiled linVST. It seems to be a user specific problem.

**Comment by lolgab** [comment]
Probably it is a problem in my setup. Thank you for your attention.
Can it be related to the fact that my path has spaces in it?
`/home/lorenzo/.wine/drive_c/Program Files/REAPER (x64)/Plugins/FX/Scaricati/VST2/`

**Comment by osxmidi** [comment]
lentferj, I understand what you meant now.

**Comment by osxmidi** [comment]
lolgab, the path you posted should be ok.

There should be no reason for having to use lower case names.

Maybe it's something to do with wine on your setup, it's hard to pin it down exactly.
