### ISSUE TITLE
LinVst 4.5 probably gui CPU leaks

### ISSUE THREAD

**Issue by Levitanus** [osxmidi/LinVst#190]
Simultaneously, I've moved from xubuntu to ubuntu studio under kde and from LinVST 4.1 to 4.5.
And, occasionally several FabFilter plugins stacked all CPU cores within loosing responsibility of mouse and overal system.

First I've thought the matter is in kde, but after installation of the version 4.1 problem disappeared.

```
Using winetricks 20200412-next - sha256sum: 5c62bc038fd3ac7fa1e0d09123c61e1034cc5431719f5a1768dcb4bd91990cca with wine-6.9 (Staging) and WINEARCH=win64
vcrun2013
w_workaround_wine_bug-37781
vcrun2015
iertutil
wininet
andale
arial
comicsans
courier
georgia
impact
times
trebuchet
verdana
webdings
corefonts
gdiplus
vcrun6sp6
urlmon
```

`Linux levitanus-main 5.11.0-17-lowlatency #18-Ubuntu SMP PREEMPT Thu May 6 21:25:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

```
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v3 Processor DRAM Controller (rev 06)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller (rev 06)
00:14.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI (rev 05)
00:16.0 Communication controller: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 (rev 05)
00:1b.0 Audio device: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller (rev 05)
00:1c.0 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 (rev d5)
00:1c.2 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #3 (rev d5)
00:1d.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 (rev 05)
00:1f.0 ISA bridge: Intel Corporation B85 Express LPC Controller (rev 05)
00:1f.2 SATA controller: Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] (rev 05)
00:1f.3 SMBus: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller (rev 05)
01:00.0 VGA compatible controller: NVIDIA Corporation GF116 [GeForce GTX 550 Ti] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GF116 High Definition Audio Controller (rev a1)
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 0c)
```

**Comment by osxmidi** [comment]
There is an opengl mesa/wine bug at the moment (see Common Problems/Possible Fixes in the readme).

It could be related to that or maybe something else.

I'll test some FabFilter plugins.

**Comment by Levitanus** [comment]
Mesa now is my headache as GTX550 now considered as rare and old... Even while works well)

**Comment by Levitanus** [comment]
I've exported mesa version and rescanned all plugins with v4.5 — still the same:
![image](https://user-images.githubusercontent.com/29713891/120313361-0d93af00-c304-11eb-90e7-85020704294b.png)

```levitanus@levitanus-main:~$ export MESA_GL_VERSION_OVERRIDE=4.5
levitanus@levitanus-main:~$ reaper
```

**Comment by osxmidi** [comment]
> I've exported mesa version and rescanned all plugins with v4.5 — still the same:
> ![image](https://user-images.githubusercontent.com/29713891/120313361-0d93af00-c304-11eb-90e7-85020704294b.png)
> 
> ```
> levitanus@levitanus-main:~$ export MESA_GL_VERSION_OVERRIDE=4.5
> levitanus@levitanus-main:~$ reaper
> ```

It might take a while to test this problem.

For the moment stick with the previous release.

**Comment by osxmidi** [comment]
> I've exported mesa version and rescanned all plugins with v4.5 — still the same:
> ![image](https://user-images.githubusercontent.com/29713891/120313361-0d93af00-c304-11eb-90e7-85020704294b.png)
> 
> ```
> levitanus@levitanus-main:~$ export MESA_GL_VERSION_OVERRIDE=4.5
> levitanus@levitanus-main:~$ reaper
> ```

I can't find anything obvious so far that might be causing the problems.

Try this 
[linvst-4.5-alt.zip](https://github.com/osxmidi/LinVst/files/6584455/linvst-4.5-alt.zip)

**Comment by Levitanus** [comment]
Thanks, I will at the end of the day. Sorry, now I'm stacked with active project...
