### ISSUE TITLE
No display

### ISSUE THREAD

**Issue by fractalf** [osxmidi/LinVst#191]
There's a couple of VSTs (Hive, Repro..) that just won't show the UI. The synth engine works fine and makes sound, but no display is shown. I'm talking about 64bit plugins (the 32bit doesn't work at all). 

I've read extensively about this (I'm not entirely new to LinVst, and have long experience in Linux) and tried out a whole lot of things, but it still doesn't work. Any input is much appreciated.

My setup:

Linux Mint 20.1
Kernel 5.4.0-74-lowlatency
LinVst 4.5
Bitwig 4.0 beta 2 (and 3.3.10)

I'm running the wine prefix with 64bit architecture (I've also tried arch win32) and have these installed
```
winetricks corefonts
winetricks gdiplus
winetricks vcrun6sp6
winetricks vcrun2013
winetricks vcrun2015
```

I've also added and disabled the `d2d1` dll.

Is there something very obvious/basic I'm missing here?

In advance, thank you very much :)

**Comment by osxmidi** [comment]
> There's a couple of VSTs (Hive, Repro..) that just won't show the UI. The synth engine works fine and makes sound, but no display is shown. I'm talking about 64bit plugins (the 32bit doesn't work at all).
> 
> I've read extensively about this (I'm not entirely new to LinVst, and have long experience in Linux) and tried out a whole lot of things, but it still doesn't work. Any input is much appreciated.
> 
> My setup:
> 
> Linux Mint 20.1
> Kernel 5.4.0-74-lowlatency
> LinVst 4.5
> Bitwig 4.0 beta 2 (and 3.3.10)
> 
> I'm running the wine prefix with 64bit architecture (I've also tried arch win32) and have these installed
> 
> ```
> winetricks corefonts
> winetricks gdiplus
> winetricks vcrun6sp6
> winetricks vcrun2013
> winetricks vcrun2015
> ```
> 
> I've also added and disabled the `d2d1` dll.
> 
> Is there something very obvious/basic I'm missing here?
> 
> In advance, thank you very much :)

I tried the Repro demo out and it seems ok.

I'm testing using Wine 6 Stable on Manjaro.

Repro and Hive have Linux versions as far as I know.

**Comment by fractalf** [comment]
Ok, thank you for replying, I will try some more, maybe clean all sheets etc..
