### ISSUE TITLE
Valhalla Supermassive support?

### ISSUE THREAD

**Issue by khughitt** [osxmidi/LinVst#192]
Greetings!

First off, apologies if this isn't the best place to ask for advice trouble-shooting a particular VST -- just let me know if there is a better outlet for this kind of thing and I would be happy to close this issue and move the discussion there.

I was wondering if you might have any suggestions for how to trouble-shoot an issue I'm encountering when attempting to install the free [Valhalla Supermassive VST](https://valhalladsp.com/shop/reverb/valhalla-supermassive/)?

Attempting to run the installer produces an error message:

> wine internal error cannot expand "autocf64" constant on this version of windows.

It seems like it may be an issue with the [Inno Setup](https://jrsoftware.org/ishelp/topic_consts.htm) installer used?

I tried installing Inno Setup itself, just in case, but that had no effect.

I also tried installing an earlier version of Supermassive (1.0.0) which includes 32-bit support, but the result was the same.

Any ideas what the issue might be, or more generally, what might be a good approach to try and track down the problem?

Also, unrelated but, any general suggestions for things to configure in winecfg, DLL's to install with winetricks, etc. that you find are _generally_ useful for this sort of thing? I didn't see any mention of this in the docs, but apologies if it has been discussed and I just missed it.

Any suggestions you can provide would be greatly appreciated.

Regardless, thank you for taking the time to create and share LinVst! I'm looking forwarding to never having to boot a non-linux machine again :)

**System info**:

- Arch Linux (5.12.9 64-bit)
- Wine 6.10
- Valhalla Supermassive 1.3.0

**Comment by keybreak** [comment]
1. Use x64 version
2. Try those **winetricks**:
   ```
   mfc42
   vcrun6
   ```
   Hopefully they'll help

**Comment by khughitt** [comment]
Works perfectly! Thanks for the guidance. I appreciate it.

Out of curiosity, how did you know those two libraries would help?

**Comment by keybreak** [comment]
https://gitlab.com/keybreak/linux-vst-compatibility-list

Tests...
