### ISSUE TITLE
Problem with AUR package in Manjaro /arch

### ISSUE THREAD

**Issue by Lalarian** [osxmidi/LinVst#193]
Hello!
It seems you just changed the naming of your path from:
https://github.com/osxmidi/LinVst/releases/download/4.5/LinVst-4.5-Manjaro.zip
to
https://github.com/osxmidi/LinVst/releases/download/4.5/LinVst-4.5.2-Manjaro.zip

This breaks compatibility with scripts like this:
https://aur.archlinux.org/packages/linvst-bin
It downloads the package using:
source=( "$url/releases/download/$pkgver/LinVst-$pkgver-$suffix.zip")
So I think the new scheme is hard to implant, because the url could arbitrarily change between the <major/minor> formatting and <major/minor/revision> all the time?

I wonder if the change was intended by reason, or if you just didn't know :)

**Comment by osxmidi** [comment]
> Hello!
> It seems you just changed the naming of your path from:
> https://github.com/osxmidi/LinVst/releases/download/4.5/LinVst-4.5-Manjaro.zip
> to
> https://github.com/osxmidi/LinVst/releases/download/4.5/LinVst-4.5.2-Manjaro.zip
> 
> This breaks compatibility with scripts like this:
> https://aur.archlinux.org/packages/linvst-bin
> It downloads the package using:
> source=( "$url/releases/download/$pkgver/LinVst-$pkgver-$suffix.zip")
> So I think the new scheme is hard to implant, because the url could arbitrarily change between the <major/minor> formatting and <major/minor/revision> all the time?
> 
> I wonder if the change was intended by reason, or if you just didn't know :)

I try not to break the aur links, but in this case it was because of a bug in LinVst-4.5-Manjaro.zip.

**Comment by Lalarian** [comment]
Thank you, very nice! :)

**Comment by baphomutt** [comment]
Seems there may still be an issue here. :( 
Am also on Manjaro, tried to install LinVst today via package and got the following error:
```
: (1/1) Parsing SRCINFO: linvst-bin
==> Making package: linvst-bin 4.5-1 (Mon 02 Aug 2021 09:54:50 PM CDT)
==> Retrieving sources...
  -> Found LinVst-4.5-Manjaro.zip
==> Validating source files with md5sums...
    LinVst-4.5-Manjaro.zip ... FAILED
==> ERROR: One or more files did not pass the validity check!
error downloading sources: linvst-bin
```
