### ISSUE TITLE
EZ Drummer Possible issue with v4

### ISSUE THREAD

**Issue by casual-droid** [osxmidi/LinVst#194]
Hi,
I've used ez drummer with linvst 3.x and it worked great.
However, an update to any v4 versions seems to break compatibility with ez drummer.
I get no sound out of the plugin (except when I change drum type in drop down menu of each sound, which effectively tells that the sounds are loaded in memory).
If I revert back to v3, it's OK.
Am I missing something?
Using reaper / Ubuntu 20.04 / Wine 6.0
All the best

**Comment by osxmidi** [comment]
> Hi,
> I've used ez drummer with linvst 3.x and it worked great.
> However, an update to any v4 versions seems to break compatibility with ez drummer.
> I get no sound out of the plugin (except when I change drum type in drop down menu of each sound, which effectively tells that the sounds are loaded in memory).
> If I revert back to v3, it's OK.
> Am I missing something?
> Using reaper / Ubuntu 20.04 / Wine 6.0
> All the best

Yes, you are right.

I made some changes and didn't realize that they caused EZDrummer problems.

I've fixed it and updated the 4.5.2 binaries.

Thanks for pointing out the problem.

**Comment by casual-droid** [comment]
I confirm this is working now with the new binaries.
Thanks for fixing this (awesome support). I thought this was an issue with my config.
Looks like v4 runs smoother than v3 too, great job on this.
