### ISSUE TITLE
Drag export of wav/midi to DAW

### ISSUE THREAD

**Issue by MusoCity** [osxmidi/LinVst#196]
Is there any way a drag and drop of wav or midi files can be accomplished from the Win VST to the Linux DAW ?

**Comment by osxmidi** [comment]
> Is there any way a drag and drop of wav or midi files can be accomplished from the Win VST to the Linux DAW ?

Usually the plugin makes a temp file somewhere.

The ones I know about are

MT-PowerDrumKit exports grooves to mtpdk.mid in the /home/user/Documents folder (the last dragged groove or fill to the composer) and then mtpdk.mid can be drag and dropped into the DAW. To deal with multiple grooves/fills (compositions), drag the composition from the composer window to outside of the MT-PowerDrumKit window and then mtpdk.mid should contain the whole composition.

EZDrummer2 (visual glitches can be removed by choosing the Windows XP version in winecfg). Exports EZdrummer Libraries clips to a midi file in the /home/user/.wine/drive_c/ProgramData/Toontrack/EZdrummer folder (the last dragged clip that was dragged outside of the EZDrummer2 window) and then the midi file can be drag and dropped into the DAW. Choose Select All (from the right side Menu drop down) to be able to drag multiple clips to the midi file in the /home/user/.wine/drive_c/ProgramData/Toontrack/EZdrummer folder

Addictive Drums 2 (Addictive Drums 2 requires that the dll (and therefore the renamed linvst.so) needs to be loaded from the installation directory, ie a fixed path). Drag the clip from the Beats window to outside of the Addictive Drums 2 window and then a midi file will appear (probably AD2Beat.mid) in /home/user/.wine/drive_c/users/user/My Documents/Addictive Drums 2/XXXXXX/Settings which should contain the clip and which can then be dragged to the DAW. Same thing applies for the recorded wav file (ADDrop.wav).

Steven Slate Drums SSD5 Drag the Groove/Fill from the Grooves window to outside of the SSD5 window and then a midi file will appear in /home/user/.wine/drive_c/users/user/Temp which should contain the clip and which can then be dragged to the DAW. Samples might need to be manually extracted (by clicking on the slatepack files) (using Archive Manager).

**Comment by MusoCity** [comment]
Thanks, I can open the folder with them in the media browser in Reaper I just though there maybe some way to copy the drag file location from the wine side to the Linux side but I suppose that is more of a wine feature request.

https://www.reatrak.com/downloads/biab/Drag-Drop-Wine-Linux.gif

**Comment by osxmidi** [comment]
> Thanks, I can open the folder with them in the media browser in Reaper I just though there maybe some way to copy the drag file location from the wine side to the Linux side but I suppose that is more of a wine feature request.
> 
> https://www.reatrak.com/downloads/biab/Drag-Drop-Wine-Linux.gif

Well, I think that's a bit hacky imo.

Wine needs to support Drag and Drop from Wine Windows to Linux Native Applications officially imo, not just for vst bridges but also for other Wine apps.

**Comment by MusoCity** [comment]
Thanks, I can open the folder with them in the media browser in Reaper I just though there maybe some way to copy the drag file location from the wine side to the Linux side but I suppose that is more of a wine feature request.

https://www.reatrak.com/downloads/biab/Drag-Drop-Wine-Linux.gif

**Comment by MusoCity** [comment]
yabridge has just implemented drag n drop
https://www.reatrak.com/images/BBPlugin-yabridge-drag2.gif

**Comment by osxmidi** [comment]
> yabridge has just implemented drag n drop
> https://www.reatrak.com/images/BBPlugin-yabridge-drag2.gif

Yeah, that's what I posted about above.

Wine doesn't officially support it.

The Audacity Windows version can be used to drag audio/midi clips to from the vst window (after previewing/arranging them in the vst such as MT-PowerDrumKit) and then the option of editing before saving and then dragged to the Linux Daw.
