### ISSUE TITLE
build instructions for Ubuntu

### ISSUE THREAD

**Issue by nacho-pancho** [osxmidi/LinVst#197]
Hi,
First of all, thank you for your work!
In the instructions under Make-Guide/Readme.md it says that, for Ubuntu, the dependencies can be installed via the package wine-stable-dev

At least in my version of Ubuntu (20.04), the correct package name is libwine-dev, so the line should be

sudo apt-get install libwine-dev libx11-dev

Thank you.
Ignacio.

**Comment by osxmidi** [comment]
> Hi,
> First of all, thank you for your work!
> In the instructions under Make-Guide/Readme.md it says that, for Ubuntu, the dependencies can be installed via the package wine-stable-dev
> 
> At least in my version of Ubuntu (20.04), the correct package name is libwine-dev, so the line should be
> 
> sudo apt-get install libwine-dev libx11-dev
> 
> Thank you.
> Ignacio.

Thanks, I have added it to the Make guide.
