### ISSUE TITLE
PR with README updates

### ISSUE THREAD

**Issue by stevemurr** [osxmidi/LinVst#199]
Hi,

Thanks for the awesome project.  I noticed the `README.md` could use some formatting love - would the project owners accept a PR that adds standard markdown formatting patterns and structure to the `README.md` file?  

Thanks,
Steven

**Comment by osxmidi** [comment]
> Hi,
> 
> Thanks for the awesome project. I noticed the `README.md` could use some formatting love - would the project owners accept a PR that adds standard markdown formatting patterns and structure to the `README.md` file?
> 
> Thanks,
> Steven

Hi, thanks.


The Readme's are a bit rough.

If you want to improve on it, then it will most likely be accepted.
