### ISSUE TITLE
Debugging plugins

### ISSUE THREAD

**Issue by lgarrido** [osxmidi/LinVst#20]
#Hi.

I am trying to get some plugins to work through LinVst. For instance, I can't get Sampletank 2.5.5.b to work (old, discontinued 32 bit version, it can be downloaded for free from ikmultimedia.com after registering). It is detected by Carla, but it won't show its GUI. Ardour doesn't even detect it.

It runs under fst, though, so maybe there is some problem with window embedding.

Ubuntu 16.04 LTS (Xenial) + KXStudio (wine-rt 2.0.1)

I understand this is a very complicated and delicate issue: missing DLLs, native vs builtin DLLs, copy protection mechanisms, 32 bit vs 64 bit WINEPREFIX, different versions of wine, etc. Also, some hosts seem to behave differently (carla and ardour, for instance.)

Anyway, is there any procedure that could give some clues about why it is not working? (I am a developer but not well versed in Wine specifics, other than run wine with some WINEDEBUG flags to find missing DLL dependencies).

Thanks!

**Comment by osxmidi** [comment]
There are various ways to try to work out what dll's might be needed to be overridden or added or disabled.

There is the wine debugger report when it crashes that lists the dll's that were loaded.

Using a hex editor on the vst binary and searching for dll is another method.

I could not initially get the new Line 6 Helix to run, but I picked up that the msvcr120.dll and gdiplus.dll (and especially the gdiplus.dll) were probably causing problems from scanning the vst Helix binary with a hex editor to see what dll's it might have been using.

The dll's that cause a fair amount of trouble are,  d2d1.dll (it's only partially implemented in Wine), gdiplus.dll, wininet.dll (net connection) and maybe some others.

**Comment by osxmidi** [comment]
I downloaded Sampletank 2.5.5.b and eventually got it to run ok with Linux Reaper on Debian 9 with Wine Staging 2.18.

The install is not smooth and I had a few Wine crashes during it, and one initial crash in Reaper where it seems to want some path set to it's wine default install path, so even though it crashed the path dialog box was still up and so I just hit ok.

**Comment by osxmidi** [comment]
I just reread your post.

I think the problems are due to you using wine-rt 2.0.1.

wine-rt can have problems and usually wine-staging is recommended instead.

wine-staging can have priorities set, so it can replace wine-rt.

**Comment by lgarrido** [comment]
OK, so a possible line of tracking problematic DLLs could be just scanning which of them are used and trying to override them one by one in winecfg.

```
strings .wine32/drive_c/Program\ Files/VstPlugIns/SampleTank2.x.dll | grep -i dll
kernel32.dll
mscoree.dll
user32.dll
KERNEL32.dll
USER32.dll
ADVAPI32.dll
VST.dll
```

I will look into wine-staging, thanks!
