### ISSUE TITLE
Help me understand LinVst

### ISSUE THREAD

**Issue by tamasfe** [osxmidi/LinVst#204]
Hi, first of all, thank you for this awesome project! I've been using it for quite a while now.

I've had some issues with wine updates breaking the library again and again, and while downgrading is possible, a lot of wine updates bring improvements in other applications. 

So I've decided to look into why this might happen and see if I can contribute fixes, however I'm more or less lost at even understanding what LinVst is doing and how it's structured. I have a few specific questions, but a general overview of the project would be much appreciated!

- From my understanding `some_vst.so` is a shim library that spawns a server with the instruction to load the actual VST, and communicates with it via IPC, is this correct? If yes, how does the whole process and the IPC exactly work?
- From what I've seen in issues, `winegcc` is to blame for a lot of breakages, is there a reason why it's needed specifically? Would it be possible to simply build the server in a windows environment instead?

**Comment by osxmidi** [comment]
> Hi, first of all, thank you for this awesome project! I've been using it for quite a while now.
> 
> I've had some issues with wine updates breaking the library again and again, and while downgrading is possible, a lot of wine updates bring improvements in other applications.
> 
> So I've decided to look into why this might happen and see if I can contribute fixes, however I'm more or less lost at even understanding what LinVst is doing and how it's structured. I have a few specific questions, but a general overview of the project would be much appreciated!
> 
>     * From my understanding `some_vst.so` is a shim library that spawns a server with the instruction to load the actual VST, and communicates with it via IPC, is this correct? If yes, how does the whole process and the IPC exactly work?
> 
>     * From what I've seen in issues, `winegcc` is to blame for a lot of breakages, is there a reason why it's needed specifically? Would it be possible to simply build the server in a windows environment instead?

Yes that's right.

winegcc is used to make the server part, which is a wine (windows) app.

The linvst.so part is a linux app.

They (the linux app and wine app parts) communicate via IPC.

There is nothing that can be done about Wine Staging at the moment until they fix the bug in a future release.
