### ISSUE TITLE
Waves V12 no Dialog window LinVst

### ISSUE THREAD

**Issue by molochworship** [osxmidi/LinVst#205]
Hello I got Waves V12 working flawlessly on Arch thanks to this script https://github.com/PietJankbal/powershell-wrapper-for-wine

The only problem is once I download the plugins and shell when I go to scan for the plugins the linvst plugin is picked up and it stays on it to scan for a bit but the dialog window does not appear that allows me to select the Plugins V12

I did read another issue on this in closed issue and I removed the *txt from the permissions folder in appdata 

If you have any idea why the dialog box does not appear please inform me other than that amazing job with LinVst !

**Comment by molochworship** [comment]
[Info]: Scanning: /home/user/bottles/waves/drive_c/Program Files/VSTPlugIns/WaveShell1-VST 12.7_x64.so
mlock fail1: Cannot allocate memory
002c:fixme:winediag:LdrInitializeThunk wine-staging 6.16 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
002c:fixme:ntdll:EtwEventActivityIdControl 0x1, 000000000021EDD0: stub
00fc:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x7bc2dcb7
LinVst Error: lin-vst-server not found or vst dll load timeout or LinVst version mismatch
[ERROR]: ** ERROR ** VSTFX : WaveShell1-VST 12.7_x64 could not be instantiated :(

[WARNING]: Cannot get VST information from '/home/user/bottles/waves/drive_c/Program Files/VSTPlugIns/WaveShell1-VST 12.7_x64.so': instantiation failed.
Scan Failed.

**Comment by osxmidi** [comment]
> Hello I got Waves V12 working flawlessly on Arch thanks to this script https://github.com/PietJankbal/powershell-wrapper-for-wine
> 
> The only problem is once I download the plugins and shell when I go to scan for the plugins the linvst plugin is picked up and it stays on it to scan for a bit but the dialog window does not appear that allows me to select the Plugins V12
> 
> I did read another issue on this in closed issue and I removed the *txt from the permissions folder in appdata
> 
> If you have any idea why the dialog box does not appear please inform me other than that amazing job with LinVst !

I don't think the dialog window to select the Plugins path applies anymore since Waves moved to using PowerShell.

I think your problem is probably due to Wine Staging (6.15 and 6.16) being broken at the moment.

Wine Staging needs to be downgraded to 6.14.

I did test Waves V12 a while ago and it seemed ok.
