### ISSUE TITLE
Native Instruments Reaktor 6 VST in Bitwig studio 2.5.1, Midi keyboard issue

### ISSUE THREAD

**Issue by atomik4** [osxmidi/LinVst#206]
Bitwig Studio 2.5.1
wine-6.14 (Staging)
LinVst-4.5.2-Manjaro
Native Instruments Reaktor 6
USB Midi Keyboard nektar impact gx61

There is some strange midi problem where a USB Midi Keyboard does not work for anything loaded into NI Reaktor 6 plugin when using Bitwig 2.5.1. What is strange is that other plugins have working midi keyboard (both native and linvst wine plugins) i.e. Massive X midi keyboard works.

What happens is start Bitwig and load Reaktor 6 instrument plugin, then load anything that's an instrument, for example Carbon 2. After it's loaded the Midi keyboard is pressed, tried all sorts different octaves too, no sound but the small activity led on the bitwig instrument square for Reaktor (in the lower-left corner by default) lights up every key press. So why is there no sound even when it appears bitwig to be receiving a trigger response from the USB Midi keyboard? 
I'm Stumped.

Can you verify is this an issue of broken in 2.5.x and then fixed in later version bitwig? Or is it bug in all versions?
I can attest that there is no issue with USB Midi keyboard support with Reaktor 6 in Renoise.

**Comment by osxmidi** [comment]
> Bitwig Studio 2.5.1
> wine-6.14 (Staging)
> LinVst-4.5.2-Manjaro
> Native Instruments Reaktor 6
> USB Midi Keyboard nektar impact gx61
> 
> There is some strange midi problem where a USB Midi Keyboard does not work for anything loaded into NI Reaktor 6 plugin when using Bitwig 2.5.1. What is strange is that other plugins have working midi keyboard (both native and linvst wine plugins) i.e. Massive X midi keyboard works.
> 
> What happens is start Bitwig and load Reaktor 6 instrument plugin, then load anything that's an instrument, for example Carbon 2. After it's loaded the Midi keyboard is pressed, tried all sorts different octaves too, no sound but the small activity led on the bitwig instrument square for Reaktor (in the lower-left corner by default) lights up every key press. So why is there no sound even when it appears bitwig to be receiving a trigger response from the USB Midi keyboard?
> I'm Stumped.
> 
> Can you verify is this an issue of broken in 2.5.x and then fixed in later version bitwig? Or is it bug in all versions?
> I can attest that there is no issue with USB Midi keyboard support with Reaktor 6 in Renoise.

I can't seem to duplicate the problem.

I tried the Reaktor 6 demo in the Bitwig 4 demo with a NanoPad as the Midi Controller and it was all ok as far as I could tell.

Maybe check your Bitwig controller settings.

![Screenshot](https://user-images.githubusercontent.com/26504179/133877492-ac278f0c-3276-4e20-b45f-155f6a3f2376.png)

**Comment by atomik4** [comment]
Well it's nice to know that the latest Bitwig 4 works, but unfortunately I am stuck on Bitwig 2.5.1

**Comment by osxmidi** [comment]
> Well it's nice to know that the latest Bitwig 4 works, but unfortunately I am stuck on Bitwig 2.5.1

Unfortunately I don't know much about Bitwig 2.5.1 and it's midi input, but I assume it should be similar to Bitwig 4.

Are you using Alsa or Jack?

I've never heard of someone having midi input problems with Bitwig 2.5 and LinVst.

Does Bitwig 2.5 Midi input work with other vst instrument plugins such as Cobalt for instance http://www.lesliesanford.com/vst/plugins/

**Comment by osxmidi** [comment]
Bitwig doesnt like a2jmidid apparently.

**Comment by atomik4** [comment]
I'm using Alsa, and the midi controller support is fully compatible.
![bitwig-midi](https://user-images.githubusercontent.com/90891182/133907353-632a8873-e870-4983-8f52-ecf8cc647488.png)
![bitwig-audio](https://user-images.githubusercontent.com/90891182/133907356-a3c6d5a9-cb97-4951-82d4-f09fc29ea6de.png)

It just seems to be a Reaktor 6 problem, as other plugins work fine - Massive X, Spitfire Audio Labs, Reason rack, Voltage Modular, etc. I tested Cobalt from the link you sent, and it works fine.

Reaktor support is a big deal for me as there are dozens of instruments and effects (and the ones you make yourself or by community). I was hoping to solve the issue, because Bitwig 2.5.1 has everything I need (I don't need the stuff they added to 3.x or 4.x - it's bloat). Otherwise I'll have to resort to dual booting some other O.S. like Windows or macOS, and obviously that's not so good.

What version of Reaktor 6 did you test/came with the demo?

**Comment by osxmidi** [comment]
6.4.3 (R0)
