### ISSUE TITLE
trying the install on mageia8

### ISSUE THREAD

**Issue by fhenryco** [osxmidi/LinVst#209]
In mageia8 , various libraries are not found by ld : for instance i get the message

/usr/bin/ld : can't find -ladvapi32

yet the dll is there 

/usr/lib64/wine/advapi32.dll

and i have added paths in your makefile accordingly

so i dont understand why the libraries are not found...any help would be appreciated

**Comment by osxmidi** [comment]
> In mageia8 , various libraries are not found by ld : for instance i get the message
> 
> /usr/bin/ld : can't find -ladvapi32
> 
> yet the dll is there
> 
> /usr/lib64/wine/advapi32.dll
> 
> and i have added paths in your makefile accordingly
> 
> so i dont understand why the libraries are not found...any help would be appreciated

I'm not sure what is causing it.

Maybe the Makefile needs a path for the 32 bit version in the LINK_WINE32 line.

**Comment by fhenryco** [comment]
just noticed that LD_FLAGS in the makefile is defined nowhere
does it mean that #LINK_FLAGS   = $(LDFLAGS) should be replaced by LINK_FLAGS = $(BUILD_FLAGS_WIN) or LINK_FLAGS = $(BUILD_FLAGS_WIN32) 
i thought that this project was not for developpers only

**Comment by osxmidi** [comment]
> eventually i managed to make it work in mageia because i dont need wine32 for my VSTs. what i still dont understand is the difference between embedded and standalone versions...

The standalone versions were old versions that had a separate window (not a window embedded into the daws plugin window).
