### ISSUE TITLE
Waves plugs V13 not working 

### ISSUE THREAD

**Issue by guglielmofratticioli** [osxmidi/LinVst#210]
I have linvst 4.5 with wine v17, Reaper fails to scan Waveshell1-VST 13.0, so all the v13 waves plugins fail. On the other hand v11 and v12 works fine

**Comment by osxmidi** [comment]
Keeping up with Waves changes is always difficult.

I'll try to see what is happening but no guarantees.

**Comment by guglielmofratticioli** [comment]
Have you checked out the solution by yabridge vst bridge? The waves v13 are working fine with that , well actually I don’t know how much is it different from linvst and if you can find a fixing strategy in there

**Comment by osxmidi** [comment]
> Have you checked out the solution by yabridge vst bridge? The waves v13 are working fine with that , well actually I don’t know how much is it different from linvst and if you can find a fixing strategy in there

Well, they do their thing and I do mine, whatever.

The trouble with Waves is that they changed to using Powershell and Powershell is very flaky with Wine.

Wine needs to incorporate Powershell in an official way.

Who knows what Waves will change for Windows 11 and whether Wine can handle it.

It could be an installation problem or maybe some hack is needed.

I've done hacks for Waves, but it gets to a point of whether it's worth it just for them, given Wine's limitations.

**Comment by osxmidi** [comment]
I've just had a look at it.

I installed Waves central v13 and installed a couple of demos (Bass Rider etc) and it seems to be ok as far as I can tell.

The installation of V13 seems the same routine as v12 to me.

Wine Staging is needed.

**Comment by guglielmofratticioli** [comment]
Wa Im trying that later, guess wine staging 6.22 has fixed that
