### ISSUE TITLE
Soothe2 crashing with wine 6.14+

### ISSUE THREAD

**Issue by nBalykin** [osxmidi/LinVst#211]
With wine 6.13 all works good.
the plugin interface opens fine, everything works, but if you try to close the plugin, the plugin freezes, the daw (reaper) also freezes
 Is it wine or linvst problem? Wine 6.15/16 is broken, so there are another bug. But 6.14, 6.17-22 have the same problem.

**Comment by osxmidi** [comment]
> With wine 6.13 all works good. the plugin interface opens fine, everything works, but if you try to close the plugin, the plugin freezes, the daw (reaper) also freezes Is it wine or linvst problem? Wine 6.15/16 is broken, so there are another bug. But 6.14, 6.17-22 have the same problem.

I tried it out on EndeavourOS (arch based) and wine-6.21 and Reaper and LinVst 4.5.2.

I used the latest 64 bit ilok installation.

After I got through all of the ilok hurdles, it seemed to run ok on my system, the window opens and closes ok. 

So, I can't reproduce the problem at the moment.

**Comment by nBalykin** [comment]
```
16.01.2022 14:51	systemd-coredump	Process 2257882 (reaper_host_x86) of user 1000 dumped core.

Module /home/mrnekit/SSD_Files/SHAREwineprefixes/plugins-64-2/drive_c/Program Files/Steinberg/VSTPlugins/oeksound/soothe2_x64.so with build-id 966e07daaa99cdcba7b13c13ea9804b7d6dda1f3
Module linux-vdso.so.1 with build-id 7099d493b8b7912b86d34047636c958a58b5961f
Module libXdmcp.so.6 with build-id 8ca0792d23c8b8b4c0864297512349292bea5955
Module libXau.so.6 with build-id 1c67764663e07bec24d8951e5fd93f4d165979ff
Module libxcb.so.1 with build-id 0d1ef11740a5daad2ee331e812a51aa6574af222
Module librt.so.1 with build-id 75484da2d6f1515189eefa076e0a40328834cd16
Module libX11.so.6 with build-id 5ba5798d193c0065014b8c6252a0678671c8d478
Module libm.so.6 with build-id 2b8fd1f869ecab4e0b55e92f2f151897f6818acf
Module ld-linux-x86-64.so.2 with build-id 040cc3dd10461562f177df39e3be2f3704258c3c
Module libc.so.6 with build-id 4b406737057708c0e4c642345a703c47a61c73dc
Module libgcc_s.so.1 with build-id 7f8508bb914546ada778809b64b99d234337d835
Module libstdc++.so.6 with build-id 9b5eeeb149bf3c4efe787fb398b44f00507aec87
Module libdl.so.2 with build-id 5abc547e7b0949f89f3c0e21ab0c8331a7440a8a
Module libpthread.so.0 with build-id 07c8f95b4f3251d08550217ad8a1f31066229996
Module libgtk3-nocsd.so.0 with build-id 1fc6e85b4231ceadaa3e30016eb6d4aa4e19f8ee
Module reaper_host_x86_64 with build-id 67a2ec132fee818642857778ad63508cf276b8f0
Stack trace of thread 2257898:
#0  0x00007fc8cf5bcd22 raise (libc.so.6 + 0x3cd22)
#1  0x00007fc8cf5a6862 abort (libc.so.6 + 0x26862)
#2  0x00007fc8cf5fed28 __libc_message (libc.so.6 + 0x7ed28)
#3  0x00007fc8cf60692a malloc_printerr (libc.so.6 + 0x8692a)
#4  0x00007fc8cf60bb0c __malloc_arena_thread_freeres (libc.so.6 + 0x8bb0c)
#5  0x00007fc8cf99927f start_thread (libpthread.so.0 + 0x927f)
#6  0x00007fc8cf67e5e3 __clone (libc.so.6 + 0xfe5e3)

Stack trace of thread 2257882:
#0  0x00007fc8cf9a58ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
#1  0x00007fc8cf99a743 __pthread_clockjoin_ex (libpthread.so.0 + 0xa743)
#2  0x0000000000410b7c n/a (reaper_host_x86_64 + 0x10b7c)
#3  0x0000000000404650 n/a (reaper_host_x86_64 + 0x4650)
#4  0x0000000000402e12 n/a (reaper_host_x86_64 + 0x2e12)
#5  0x00007fc8cf5a7b25 __libc_start_main (libc.so.6 + 0x27b25)
#6  0x0000000000403b2a _start (reaper_host_x86_64 + 0x3b2a)

Stack trace of thread 2257884:
#0  0x00007fc8cf646a95 clock_nanosleep@@GLIBC_2.17 (libc.so.6 + 0xc6a95)
#1  0x00007fc8cf64bc77 __nanosleep (libc.so.6 + 0xcbc77)
#2  0x00007fc8cf676a99 usleep (libc.so.6 + 0xf6a99)
#3  0x0000000000403cba n/a (reaper_host_x86_64 + 0x3cba)
#4  0x000000000041120b n/a (reaper_host_x86_64 + 0x1120b)
#5  0x00007fc8cf999259 start_thread (libpthread.so.0 + 0x9259)
#6  0x00007fc8cf67e5e3 __clone (libc.so.6 + 0xfe5e3)
ELF object binary architecture: AMD x86-64
```

I have this crash also on wine-staging 7 rc2 + wine-mono 7.0.0. How can I help to fix this or where can I found more logs? 
I need idea where to go next in order to understand the cause of the crash...

**Comment by osxmidi** [comment]
> ```
> 16.01.2022 14:51	systemd-coredump	Process 2257882 (reaper_host_x86) of user 1000 dumped core.
> 
> Module /home/mrnekit/SSD_Files/SHAREwineprefixes/plugins-64-2/drive_c/Program Files/Steinberg/VSTPlugins/oeksound/soothe2_x64.so with build-id 966e07daaa99cdcba7b13c13ea9804b7d6dda1f3
> Module linux-vdso.so.1 with build-id 7099d493b8b7912b86d34047636c958a58b5961f
> Module libXdmcp.so.6 with build-id 8ca0792d23c8b8b4c0864297512349292bea5955
> Module libXau.so.6 with build-id 1c67764663e07bec24d8951e5fd93f4d165979ff
> Module libxcb.so.1 with build-id 0d1ef11740a5daad2ee331e812a51aa6574af222
> Module librt.so.1 with build-id 75484da2d6f1515189eefa076e0a40328834cd16
> Module libX11.so.6 with build-id 5ba5798d193c0065014b8c6252a0678671c8d478
> Module libm.so.6 with build-id 2b8fd1f869ecab4e0b55e92f2f151897f6818acf
> Module ld-linux-x86-64.so.2 with build-id 040cc3dd10461562f177df39e3be2f3704258c3c
> Module libc.so.6 with build-id 4b406737057708c0e4c642345a703c47a61c73dc
> Module libgcc_s.so.1 with build-id 7f8508bb914546ada778809b64b99d234337d835
> Module libstdc++.so.6 with build-id 9b5eeeb149bf3c4efe787fb398b44f00507aec87
> Module libdl.so.2 with build-id 5abc547e7b0949f89f3c0e21ab0c8331a7440a8a
> Module libpthread.so.0 with build-id 07c8f95b4f3251d08550217ad8a1f31066229996
> Module libgtk3-nocsd.so.0 with build-id 1fc6e85b4231ceadaa3e30016eb6d4aa4e19f8ee
> Module reaper_host_x86_64 with build-id 67a2ec132fee818642857778ad63508cf276b8f0
> Stack trace of thread 2257898:
> #0  0x00007fc8cf5bcd22 raise (libc.so.6 + 0x3cd22)
> #1  0x00007fc8cf5a6862 abort (libc.so.6 + 0x26862)
> #2  0x00007fc8cf5fed28 __libc_message (libc.so.6 + 0x7ed28)
> #3  0x00007fc8cf60692a malloc_printerr (libc.so.6 + 0x8692a)
> #4  0x00007fc8cf60bb0c __malloc_arena_thread_freeres (libc.so.6 + 0x8bb0c)
> #5  0x00007fc8cf99927f start_thread (libpthread.so.0 + 0x927f)
> #6  0x00007fc8cf67e5e3 __clone (libc.so.6 + 0xfe5e3)
> 
> Stack trace of thread 2257882:
> #0  0x00007fc8cf9a58ca __futex_abstimed_wait_common64 (libpthread.so.0 + 0x158ca)
> #1  0x00007fc8cf99a743 __pthread_clockjoin_ex (libpthread.so.0 + 0xa743)
> #2  0x0000000000410b7c n/a (reaper_host_x86_64 + 0x10b7c)
> #3  0x0000000000404650 n/a (reaper_host_x86_64 + 0x4650)
> #4  0x0000000000402e12 n/a (reaper_host_x86_64 + 0x2e12)
> #5  0x00007fc8cf5a7b25 __libc_start_main (libc.so.6 + 0x27b25)
> #6  0x0000000000403b2a _start (reaper_host_x86_64 + 0x3b2a)
> 
> Stack trace of thread 2257884:
> #0  0x00007fc8cf646a95 clock_nanosleep@@GLIBC_2.17 (libc.so.6 + 0xc6a95)
> #1  0x00007fc8cf64bc77 __nanosleep (libc.so.6 + 0xcbc77)
> #2  0x00007fc8cf676a99 usleep (libc.so.6 + 0xf6a99)
> #3  0x0000000000403cba n/a (reaper_host_x86_64 + 0x3cba)
> #4  0x000000000041120b n/a (reaper_host_x86_64 + 0x1120b)
> #5  0x00007fc8cf999259 start_thread (libpthread.so.0 + 0x9259)
> #6  0x00007fc8cf67e5e3 __clone (libc.so.6 + 0xfe5e3)
> ELF object binary architecture: AMD x86-64
> ```
> 
> I have this crash also on wine-staging 7 rc2 + wine-mono 7.0.0. How can I help to fix this or where can I found more logs? I need idea where to go next in order to understand the cause of the crash... Anyway thanks!

It's probably due to iLok.

Can you run the iLok licence manager on Linux?

Is it the latest iLok version?

I'm using EndeavourOS  which is arch based with wine-staging 7 rc5 and the iLok Licence Manager works ok.

When the plugin starts (either on a scan or when it's loaded in the daw), the plugin checks the iLok license and if there is something wrong with the iLok installation then it might crash.

As far as I can tell, iLok does work with Wine but there might be some things that could cause problems such as various distro quirks or the state of someones wine  prefix (~/.wine), sometimes a complete delete of the ~/.wine folder (wineprefix) followed by a winecfg to rebuild  it and then reinstalls of the latest iLok and plugins might be required.
