### ISSUE TITLE
All VST parameters from project are on defaults after update to the D'n'D version

### ISSUE THREAD

**Issue by Levitanus** [osxmidi/LinVst#212]
As I can see — all parameters that are visible for the DAW and can be automated are set to defaults.
KONTAKT instruments, Superior drummer instruments, instrument selection in SWAM are saved. I can't remember what version I've updated from, but I feel it should be 4.5.

![изображение](https://user-images.githubusercontent.com/29713891/148365276-62908f33-7acb-4c12-a19a-5fd7ecc4dcaa.png)

So, I suppose, I've updated from `LinVST 4.5` to `LinVST 4.7` and from `winehq-stable` to `winehq-staging` (I've got problems with superior drummer GUI and looked for solution).
I've used linvst.so previously, now moved to drag'n'drop. Updated with `sudo cp FLODER/* /usr/bin` and with linvstconvert.

Currently my system is:

```
levitanus@levitanus-main:~$ uname -a
Linux levitanus-main 5.11.0-44-lowlatency #48-Ubuntu SMP PREEMPT Fri Dec 10 10:27:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
levitanus@levitanus-main:~$ wine --version
wine-7.0-rc4 (Staging)
```

If the matter is in Drag'n'Drop — how can I use simultaneously the both: simple and d'n'd versions?

**Comment by Levitanus** [comment]
Currently reconverted everything back to the regular LinVST and parameters have been recovered

**Comment by osxmidi** [comment]
LinVst 4.7 had a bug in it for a few hours before I realized it and fixed it, so I'd recommend downloading or rebuilding LinVst 4.7 again.

4.7.1 should be coming soon as well.

**Comment by Levitanus** [comment]
I'm sorry for the delay. As usual, bugs are discovered in the middle of arrangement. So, now I'm in the stage „It works. Stay off“? When the job is done — I'll try once again and write out!

**Comment by Levitanus** [comment]
Ok. I can not tell what exactly had happened. At first, I was sure this bug relevant to every VST plugin. Lately after several reupdates FabFilter plugins left only touched by this strange parameters behavior. So, I've cleaned everything I could find about FabFilter and reinstalled with updated versions. Till now everything works as expected.
