### ISSUE TITLE
Error: Maximum number of clients reached

### ISSUE THREAD

**Issue by defensem3ch** [osxmidi/LinVst#213]
I think this is a WINE error but thought maybe LinVst might be opening X11 window connections and not resetting them? If I have several plugins open in REAPER on several tracks, I have to restart my computer before new plugins will open. Using wine-7.0-rc6 on Linux Mint 20.3.

**Comment by osxmidi** [comment]
> I think this is a WINE error but thought maybe LinVst might be opening X11 window connections and not resetting them? If I have several plugins open in REAPER on several tracks, I have to restart my computer before new plugins will open. Using wine-7.0-rc6 on Linux Mint 20.3.

I think it might be a system problem, maybe.

I've never encountered the max number of clients error on Debian or Arch.

lsof can list open files https://askubuntu.com/questions/4499/how-can-i-diagnose-debug-maximum-number-of-clients-reached-x-errors

**Comment by defensem3ch** [comment]
Ok! Thanks for looking into it. This issue can be closed.
