### ISSUE TITLE
After wine-staging upgrade to 7.5, all linvst plugins open console window

### ISSUE THREAD

**Issue by defensem3ch** [osxmidi/LinVst#216]
Tested with latest LinVst 4.75

If the console windows are closed, REAPER will crash.

**Comment by osxmidi** [comment]
> Tested with latest LinVst 4.75
> 
> If the console windows are closed, REAPER will crash.

I noticed it too.

I think it's the wine developers doing something in 7.5, hopefully they will get rid of it in 7.6.

On Arch, the console windows close by themselves.

**Comment by osxmidi** [comment]
> Tested with latest LinVst 4.75
> 
> If the console windows are closed, REAPER will crash.

I'm pretty sure I've got a workaround for it.

It should be ok now.

**Comment by defensem3ch** [comment]
Thank you! Issue is resolved upon testing.
