### ISSUE TITLE
Where are the old versions and change logs?

### ISSUE THREAD

**Issue by lucmp** [osxmidi/LinVst#224]
Where are the old versions and change logs?

Especially the change logs. I would like to have a look at the change logs.

**Comment by osxmidi** [comment]
> Where are the old versions and change logs?
> 
> Especially the change logs. I would like to have a look at the change logs.

Versions are mostly driven by compatibility, compatibility with daws and with Wine and all of their quirks/changes/temporary changes/bugs whatever, that's why I don't bother with logs much because compatibility quirks/bugs with daws/wine are not a core part of LinVst and could also be temporary but they drive a lot of the updates.

Changes that have been made should be in the diffs in the source code.

**Comment by lucmp** [comment]
Well, the latest version doesn't work for me. I'm on Debian 9 and would like to have access to old versions of linvst.

**Comment by lucmp** [comment]
I need to apologize. I made a mistake.

First I ran the latest version's tester as $ wine testvst.exe [plugin path] and it failed, and I just assumed it wouldn't work because it's new and my system is old.

It turns out I ran the tester as $ ./testvst.exe [plugin path] and it worked. I have no idea why. You should know.

Then of course I tested it properly with many plugins and it seems to work.

linvstconvert doesn't work though. It runs, but I select the linvst.so file and the target folder and nothing happens.

Sorry for any trouble.

**Comment by osxmidi** [comment]
> I need to apologize. I made a mistake.
> 
> First I ran the latest version's tester as $ wine testvst.exe [plugin path] and it failed, and I just assumed it wouldn't work because it's new and my system is old.
> 
> It turns out I ran the tester as $ ./testvst.exe [plugin path] later and it worked. I have no idea why. You should know.
> 
> Then of course I tested it properly with many plugins and it seems to work.
> 
> linvstconvert doesn't work though. It runs, but I select the linvst.so file and the target folder and nothing happens.
> 
> Sorry for any trouble.

There is a new version 4.9.

linvstconvert has changed to allow updating newly added (newly installed vsts) and also to update all plugins to a new version.

So if someone was using LinVst 4.78 and then upgraded to LinVst 4.9 then after installing the LinVst 4.9 lin-vst-server files to /usr/bin they would then run linvstconvert and select the LinVst 4.9 linvst.so file and also the folder where their vst plugins are installed and then hit the "Update All Plugins (Upgrade All Plugins)" button.

After upgrading to the LinVst 4.9 version (like the above), then any additional vst installs only need the linvstconvert "Update Newly Added Plugins".

**Comment by osxmidi** [comment]
And check that the Daw plugin search paths point to the vst folder that was used in linvstconvert.

**Comment by lucmp** [comment]
They do, but I didn't test it with the DAW. I had the plugin's directory open in the file manager, ran linvstconvert and saw that no *.so was created. 

I will try the newest version later. 4.78 is working well, I'm afraid of changing it.

**Comment by osxmidi** [comment]
> They do, but I didn't test it with the DAW. I had the plugin's directory open in the file manager, ran linvstconvert and saw that no *.so was created.
> 
> I will try the newest version later. 4.78 is working well, I'm afraid of changing it.

The reason for LinVst 4.9 is a problem with the LinVst 4.8 memory caused by a library that LinVst 4.8 depended on. and it causes scanning problems especially with Reaper, so it looks like something either changed in the library and/or Reaper, compatibility problems.

LinVst 4.9 stops using the library.

**Comment by vssasks** [comment]
People are dumn. They use social networks, windows and macos and give their life under control of jews... Never upgrade anything if it works. Only backup and live with what you have.
