### ISSUE TITLE
Why can't we use symlinks?

### ISSUE THREAD

**Issue by lucmp** [osxmidi/LinVst#225]
Please tell me again why we can't use symlinks to linvst.so (the plugins don't work, I tried) instead of copying it over many many times. You must have said it before but I really don't remember that and I couldn't find it in the closed issues.

Thank you.

**Comment by osxmidi** [comment]
> Please tell me again why we can't use symlinks to linvst.so (the plugins don't work, I tried) instead of copying it over many many times. You must have said it before but I really don't remember that and I couldn't find it in the closed issues.
> 
> Thank you.

Hi.

If you mean using linvstconvert to convert a symbolic link that points to a folder of vst files then this one works.

[linvstconvert.zip](https://github.com/osxmidi/LinVst/files/12782215/linvstconvert.zip)

**Comment by lucmp** [comment]
No. I mean, instead of copying linvst.so over and renaming it with the same name as the target dll, make a symlink to the master linvst.so and rename the symlink with the same name as the target dll. 

In my mind, the DAW should see the symlink, open its target which is the master linvst.so and have it do the same magic it does as a fully copied file. 

I suppose the target of a symlink can't capture the "environment" (I assume its path) of the symlink, but the DAW knows the path. Can't they talk for a second when loading and exchange that information? Don't they already shake hands and talk to some extent?

**Comment by osxmidi** [comment]
> No. I mean, instead of copying linvst.so over and renaming it with the same name as the target dll, make a symlink to the master linvst.so and rename the symlink with the same name as the target dll.
> 
> In my mind, the DAW should see the symlink, open its target which is the master linvst.so and have it do the same magic it does as a fully copied file.
> 
> I suppose the target of a symlink can't capture the "environment" (I assume its path) of the symlink, but the DAW knows the path. Can't they talk for a second when loading and exchange that information? Don't they already shake hands and talk to some extent?

The Daws are looking for Linux dll files with the .so extension (or the .vst3 extension for vst3) and they try to load those files and test whether they are vst2 Linux dll files.

if a windows vst2 dll file is called Delay.dll then having a Linux Delay.so dll file associated with it allows a vst2 (windows to Linux) bridge to get the name of the windows vst plugin (ie Delay) and then load the wndows dll (Delay.dll) via wine while the Daw is loading the linux Delay.so file.

Symlinks involved in the name loading stage are probably going to have problems and each different Daw might have different symlink handling as well (incompatibilities).
