### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by forart** [osxmidi/LinVst#226]
Hi there, 1st of all thanks for your awesome (voluntary) work !

Since we've "doxed" your git in our [HyMPS project](https://github.com/forart/HyMPS) (under the [Adapters section](https://github.com/forart/HyMPS/blob/main/Adapters.md)), can you please fix licensing terms for it ?

Our "problem" is that does not generates a correct badge:

![](https://flat.badgen.net/github/license/osxmidi/LinVst/?label=LICENSE)
(generative url: https://flat.badgen.net/github/license/osxmidi/LinVst/?label=LICENSE)

This could easily be fixed by choosing a "correct" license file through the GH's wizard.

Although it may sounds like a minor aspect, a standardized license file could help other devs (and not only) to better/faster understand how reuse your code in other open projects and vice-versa.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by osxmidi** [comment]
> Hi there, 1st of all thanks for your awesome (voluntary) work !
> 
> Since we've "doxed" your git in our [HyMPS project](https://github.com/forart/HyMPS) (under the [Adapters section](https://github.com/forart/HyMPS/blob/main/Adapters.md)), can you please fix licensing terms for it ?
> 
> Our "problem" is that does not generates a correct badge:
> 
> ![](https://camo.githubusercontent.com/422963863ac77ce3b7fd9eee1c2accb9cfd01e472c19daaf9ee26b607725006c/68747470733a2f2f666c61742e62616467656e2e6e65742f6769746875622f6c6963656e73652f6f73786d6964692f4c696e5673742f3f6c6162656c3d4c4943454e5345) (generative url: https://flat.badgen.net/github/license/osxmidi/LinVst/?label=LICENSE)
> 
> This could easily be fixed by choosing a "correct" license file through the GH's wizard.
> 
> Although it may sounds like a minor aspect, a standardized license file could help other devs (and not only) to better/faster understand how reuse your code in other open projects and vice-versa.
> 
> Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.
> 
> Thanks in advance.

Hi.

I've added a new GPL 3 license file called LICENSE.

The GPL 3 license was in the COPYING  file, maybe that was causing the problems.

If there are any problems let me know.

**Comment by forart** [comment]
1st of all thanks for the fast reply !

As you can see above, it works correctly now.

Thanks again for your cool work.
