### ISSUE TITLE
no gui with wine 2.22 and master

### ISSUE THREAD

**Issue by lentferj** [osxmidi/LinVst#25]
Building linvst with wine 2.22 and current master using Makefile-embed6432 leads to no gui in Ardour and Mixbus.

Using Debian 9, wine 2.22 from winehq repositories, Ardour 5.12 and current Mixbus 32C.

**Comment by osxmidi** [comment]
Are there any output errors displayed from when Ardour is started from the command line?

**Comment by osxmidi** [comment]
Also, what does

ldd linvst.so 

show
