### ISSUE TITLE
This Issue with Bitwig

### ISSUE THREAD

**Issue by re23071998** [osxmidi/LinVst#26]
Just installed the latest 1.8 , and i got keyboard function working! Thanks!

But still has this problem with bitwig. I cant explain this (LOL) , but here's the video:
https://www.facebook.com/re23071998/videos/vb.100003923720274/980490468758401/

The first one is native linux vst and the 2nd one is linvst. I dont have this problem with airwave

Just pm me on facebook iif u need some help for testing out vst and stuff.

Thanks,

**Comment by osxmidi** [comment]
I'll look into it.

**Comment by osxmidi** [comment]
Should be ok now.

**Comment by re23071998** [comment]
Indeed!
