### ISSUE TITLE
Plugin window focused on mouse hover

### ISSUE THREAD

**Issue by re23071998** [osxmidi/LinVst#27]
I just compiled embed6432 version and everything works fine, but i got this weird behavior and also drag and drop from DAW browser doesnt work (but i can drag and drop from nautilus). I also tried on the different windows manager or wine version but still the same result.

Here's how its looks like: [video](https://www.facebook.com/re23071998/videos/vb.100003923720274/983041905169924/?type=2&theater&notif_t=video_processed&notif_id=1516072756377827)

Note:Zebra2 in this video is natiive linux VST

**Comment by osxmidi** [comment]
Does it only happen with Serum or also with other plugins running under LinVst?

I can't seem to reproduce it myself but I'll keep trying, but I'd say something is failing somewhere, maybe the focus.

You could try changing RevertToPointerRoot to RevertToParent or RevertToNone in the XSetInputFocus(display, child, RevertToPointerRoot, CurrentTime); line in linvst.cpp (line 125)

If that doesn't help then you could also try commenting out the focus by putting // in front of the XSetInputFocus(display, child, RevertToPointerRoot, CurrentTime); line in linvst.cpp

But commenting out the focus line will disable keyboard input.

Let me know what happens, so I can get some idea of what might be going wrong.

**Comment by re23071998** [comment]
its happen for all VST

**Comment by re23071998** [comment]
changing RevertToPointerRoot to RevertToParent or RevertToNone doest solve the problem.
But yeah, i dont think i have this problem before.

This problem doesnt happed when using standalone version

**Comment by re23071998** [comment]
just recompiled today and its working!!
Thanks!

**Comment by re23071998** [comment]
Im facing this issue again
