### ISSUE TITLE
How to use with PlayOnLinux?

### ISSUE THREAD

**Issue by metakeule** [osxmidi/LinVst#28]
Hi,

due to some dependency problems I must keep my 64bit wine-2.0.1 on my system, although I am
mainly using another 32bit wine via PlayOnLinux for most plugins.

I understand how to set the wine prefix to corresponding path, but how can I tell LinVST where to find the wine executable? (Hopefully that combination should get me the plugins running).

Thank you for your great effort. On my laptop LinVST works far better than airwave!

**Comment by osxmidi** [comment]
I don't know much about PlayOnLinux so what I say might not help with anything, but maybe it might.
I've never used PlayOnLinux, does it have it's wine binary in another place besides /usr/bin, then if it does a symbolic link in /usr/bin might help.

LinVst's remotevstclient.cpp uses  (execlp("/usr/bin/lin-vst-server.exe", "/usr/bin/lin-vst-server.exe", argStr, NULL))

So it looks for lin-vst-server.exe in /usr/bin

lin-vst-server.exe is a text file that deals with wine environmental variables and then it loads lin-vst-server.exe.so which is the main LinVst server. 

lin-vst-server.exe appears to use WINELOADER to find wine, I think.

So maybe WINELOADER could be set to a new path for the wine binary.

------------

#!/bin/bash


#declare -r WINEHQ_PATH=""    # will test plain wine later
declare -r WINEHQ-STAGING_PATH="/opt/wine-staging"
export HQ_PATH="$WINE-STAGING_PATH"    # use package from winehq, not distro

export WINEVERPATH="$HQ_PATH"
export PATH="$HQ_PATH/bin:$PATH"
export WINESERVER="$HQ_PATH/bin/wineserver"
export WINELOADER="$HQ_PATH/bin/wine"
export WINEDLLPATH="$HQ_PATH/lib/wine/fakedlls"
export LD_LIBRARY_PATH="$HQ_PATH/lib:$LD_LIBRARY_PATH"
