### ISSUE TITLE
Serum - Can't register

### ISSUE THREAD

**Issue by ArnaudE** [osxmidi/LinVst#29]
Hi,

I use several plugins through LinVST, but with Serum one weird thing : I can not register.

I can enter my serial, but when I press Ok it reverts to nothing, aka xxx-xxx etc.

Is there a workaround ?

**Comment by osxmidi** [comment]
Seems like a wine thing.

Have you tried copy/pasting the serial instead of typing it.

If all else fails maybe you could contact xferrecords https://www.xferrecords.com/forums/general/how-do-i-register-my-serum

**Comment by re23071998** [comment]
use wine-staging 2.21 to register

**Comment by ArnaudE** [comment]
wine-staging did the trick
