### ISSUE TITLE
TDR SlickEQ GE crash

### ISSUE THREAD

**Issue by Learn-Digital-Audio** [osxmidi/LinVst#3]
I tried TDR SlickEQ GE in LinVST. There is a free version I have not tried too:

http://www.tokyodawn.net/tdr-vos-slickeq/

As soon as I tried to open my serial number file inside the interface to unlock it, I got a crash. Any idea if this can be worked around?

Unhandled exception: page fault on read access to 0x00000000 in 64-bit code (0x00000001801df302).
Register dump:
 rip:00000001801df302 rsp:000000000023e300 rbp:000000000023e400 eflags:00010206 (  R- --  I   - -P- )
 rax:00000000000000ff rbx:0000000000000000 rcx:000000000000003d rdx:00000000006ccea0
 rsi:00000000008009a0 rdi:0000000000000002  r8:000000000000003d  r9:0000000000000000 r10:0000000000000000
 r11:00007f2fe3ea4070 r12:0000000000000000 r13:0000000000000000 r14:0000003d00000000 r15:000000000023e830
Stack dump:
0x000000000023e300:  00000000007f8ea0 00000000411cd7a9
0x000000000023e310:  0000002800000015 000000000000001c
0x000000000023e320:  00000000007f8ed0 00000000007f8e30
0x000000000023e330:  0000000000000000 0000000000000000
0x000000000023e340:  00000000007f8ea0 0000000000000000
0x000000000023e350:  00000000008009a0 00000000007f9ba1
0x000000000023e360:  00000000007f8e30 00000000007f8e4b
0x000000000023e370:  00000000007f8e4b 00000000007f8e80
0x000000000023e380:  00000000007f8e4c 00000000007f8e4c
0x000000000023e390:  00000001807030e9 0000000000792e60
0x000000000023e3a0:  00000000007f8e4b 000000000011590b
0x000000000023e3b0:  00000000007f9ba0 00000000007f8e80
Backtrace:
=>0 0x00000001801df302 in tdr vos slickeq ge (+0x1df302) (0x000000000023e400)
  1 0x00000001801dee6b in tdr vos slickeq ge (+0x1dee6a) (0x000000000023e511)
0x00000001801df302: movq	(%r10),%rax
Modules:
Module	Address					Debug info	Name (151 modules)
ELF	        7a800000-        7aa10000	Deferred        opengl32<elf>
  \-PE	        7a850000-        7aa10000	\               opengl32
ELF	        7b400000-        7b82c000	Deferred        kernel32<elf>
  \-PE	        7b420000-        7b82c000	\               kernel32
ELF	        7bc00000-        7bd48000	Deferred        ntdll<elf>
  \-PE	        7bc20000-        7bd48000	\               ntdll
ELF	        7c000000-        7c004000	Deferred        <wine-loader>
PE	       180000000-       180820000	Export          tdr vos slickeq ge
ELF	    7f2fc8747000-    7f2fc8951000	Deferred        libpciaccess.so.0
ELF	    7f2fc8951000-    7f2fc8b5d000	Deferred        libdrm_radeon.so.1
ELF	    7f2fc8b5d000-    7f2fc8d65000	Deferred        libdrm_nouveau.so.2
ELF	    7f2fc8d65000-    7f2fc8f89000	Deferred        libdrm_intel.so.1
ELF	    7f2fc8f89000-    7f2fc98de000	Deferred        i965_dri.so
ELF	    7f2fc98de000-    7f2fc9aef000	Deferred        libdrm.so.2
ELF	    7f2fc9aef000-    7f2fc9cf4000	Deferred        libxcb-dri2.so.0
ELF	    7f2fc9cf4000-    7f2fc9f0f000	Deferred        libxcb-glx.so.0
ELF	    7f2fc9f0f000-    7f2fca111000	Deferred        libx11-xcb.so.1
ELF	    7f2fca111000-    7f2fca314000	Deferred        libxdamage.so.1
ELF	    7f2fca314000-    7f2fca543000	Deferred        libglapi.so.0
ELF	    7f2fca543000-    7f2fca746000	Deferred        libxshmfence.so.1
ELF	    7f2fca746000-    7f2fca94d000	Deferred        libxcb-sync.so.1
ELF	    7f2fca94d000-    7f2fcab50000	Deferred        libxcb-present.so.0
ELF	    7f2fcab50000-    7f2fcad53000	Deferred        libxcb-dri3.so.0
ELF	    7f2fcad53000-    7f2fcafc6000	Deferred        libglx_mesa.so.0
ELF	    7f2fcafc6000-    7f2fcb27c000	Deferred        libgldispatch.so.0
ELF	    7f2fcb27c000-    7f2fcb4ad000	Deferred        libglx.so.0
ELF	    7f2fcb4ad000-    7f2fcb739000	Deferred        libgl.so.1
ELF	    7f2fcb739000-    7f2fcb9cc000	Deferred        dwrite<elf>
  \-PE	    7f2fcb740000-    7f2fcb9cc000	\               dwrite
ELF	    7f2fcb9cc000-    7f2fcbc61000	Deferred        d3dcompiler_43<elf>
  \-PE	    7f2fcb9e0000-    7f2fcbc61000	\               d3dcompiler_43
ELF	    7f2fcbc61000-    7f2fcc000000	Deferred        wined3d<elf>
  \-PE	    7f2fcbc80000-    7f2fcc000000	\               wined3d
ELF	    7f2fd0075000-    7f2fd02c7000	Deferred        d3d10<elf>
  \-PE	    7f2fd0080000-    7f2fd02c7000	\               d3d10
ELF	    7f2fd02c7000-    7f2fd04f8000	Deferred        dxgi<elf>
  \-PE	    7f2fd02d0000-    7f2fd04f8000	\               dxgi
ELF	    7f2fd04f8000-    7f2fd0784000	Deferred        d3d11<elf>
  \-PE	    7f2fd0500000-    7f2fd0784000	\               d3d11
ELF	    7f2fd0784000-    7f2fd0999000	Deferred        d3d10core<elf>
  \-PE	    7f2fd0790000-    7f2fd0999000	\               d3d10core
ELF	    7f2fd0999000-    7f2fd0baf000	Deferred        d3d10_1<elf>
  \-PE	    7f2fd09a0000-    7f2fd0baf000	\               d3d10_1
ELF	    7f2fd0baf000-    7f2fd0e2b000	Deferred        d2d1<elf>
  \-PE	    7f2fd0bc0000-    7f2fd0e2b000	\               d2d1
ELF	    7f2fd0e2b000-    7f2fd1082000	Deferred        usp10<elf>
  \-PE	    7f2fd0e30000-    7f2fd1082000	\               usp10
ELF	    7f2fd1604000-    7f2fd1818000	Deferred        libgpg-error.so.0
ELF	    7f2fd1818000-    7f2fd1afe000	Deferred        libgcrypt.so.20
ELF	    7f2fd1afe000-    7f2fd1d12000	Deferred        liblz4.so.1
ELF	    7f2fd1d12000-    7f2fd1f38000	Deferred        liblzma.so.5
ELF	    7f2fd1f38000-    7f2fd2140000	Deferred        librt.so.1
ELF	    7f2fd2140000-    7f2fd2345000	Deferred        libcap.so.2
ELF	    7f2fd2345000-    7f2fd25b8000	Deferred        libpcre.so.1
ELF	    7f2fd25b8000-    7f2fd2643000	Deferred        libsystemd.so.0
ELF	    7f2fd2643000-    7f2fd284b000	Deferred        libffi.so.6
ELF	    7f2fd284b000-    7f2fd2a72000	Deferred        libselinux.so.1
ELF	    7f2fd2a72000-    7f2fd2c75000	Deferred        libfreebl3.so
ELF	    7f2fd2c75000-    7f2fd2ec5000	Deferred        libdbus-1.so.3
ELF	    7f2fd2ec5000-    7f2fd3158000	Deferred        libgmp.so.10
ELF	    7f2fd3158000-    7f2fd3384000	Deferred        libhogweed.so.4
ELF	    7f2fd3384000-    7f2fd35bc000	Deferred        libnettle.so.6
ELF	    7f2fd35bc000-    7f2fd37cf000	Deferred        libtasn1.so.6
ELF	    7f2fd37cf000-    7f2fd3aff000	Deferred        libunistring.so.2
ELF	    7f2fd3aff000-    7f2fd3d21000	Deferred        libidn2.so.0
ELF	    7f2fd3d21000-    7f2fd3f86000	Deferred        libp11-kit.so.0
ELF	    7f2fd3f86000-    7f2fd41a1000	Deferred        libresolv.so.2
ELF	    7f2fd41a1000-    7f2fd43a5000	Deferred        libkeyutils.so.1
ELF	    7f2fd43a5000-    7f2fd45b4000	Deferred        libkrb5support.so.0
ELF	    7f2fd45b4000-    7f2fd47ea000	Deferred        libcrypt.so.1
ELF	    7f2fd47ea000-    7f2fd49fb000	Deferred        libavahi-client.so.3
ELF	    7f2fd49fb000-    7f2fd4c08000	Deferred        libavahi-common.so.3
ELF	    7f2fd4c08000-    7f2fd4f6f000	Deferred        libgnutls.so.30
ELF	    7f2fd4f6f000-    7f2fd5173000	Deferred        libcom_err.so.2
ELF	    7f2fd5173000-    7f2fd53a4000	Deferred        libk5crypto.so.3
ELF	    7f2fd53a4000-    7f2fd568a000	Deferred        libkrb5.so.3
ELF	    7f2fd568a000-    7f2fd58d7000	Deferred        libgssapi_krb5.so.2
ELF	    7f2fd58d7000-    7f2fd5b67000	Deferred        libcups.so.2
ELF	    7f2fd5b85000-    7f2fd5dc5000	Deferred        uxtheme<elf>
  \-PE	    7f2fd5b90000-    7f2fd5dc5000	\               uxtheme
ELF	    7f2fd5dc5000-    7f2fd5fcb000	Deferred        libxfixes.so.3
ELF	    7f2fd5fcb000-    7f2fd61d6000	Deferred        libxcursor.so.1
ELF	    7f2fd61d6000-    7f2fd63e6000	Deferred        libxi.so.6
ELF	    7f2fd63e6000-    7f2fd65e9000	Deferred        libxcomposite.so.1
ELF	    7f2fd65e9000-    7f2fd67f4000	Deferred        libxrandr.so.2
ELF	    7f2fd67f4000-    7f2fd69fe000	Deferred        libxrender.so.1
ELF	    7f2fd69fe000-    7f2fd6c04000	Deferred        libxxf86vm.so.1
ELF	    7f2fd6c04000-    7f2fd6e07000	Deferred        libxinerama.so.1
ELF	    7f2fd6e07000-    7f2fd700b000	Deferred        libxau.so.6
ELF	    7f2fd700b000-    7f2fd7233000	Deferred        libxcb.so.1
ELF	    7f2fd7233000-    7f2fd7572000	Deferred        libx11.so.6
ELF	    7f2fd7572000-    7f2fd7784000	Deferred        libxext.so.6
ELF	    7f2fd77a2000-    7f2fd7a5d000	Deferred        winex11<elf>
  \-PE	    7f2fd77b0000-    7f2fd7a5d000	\               winex11
ELF	    7f2fd7a5d000-    7f2fd7c90000	Deferred        msacm32<elf>
  \-PE	    7f2fd7a60000-    7f2fd7c90000	\               msacm32
ELF	    7f2fd7c90000-    7f2fd7f60000	Deferred        winmm<elf>
  \-PE	    7f2fd7ca0000-    7f2fd7f60000	\               winmm
ELF	    7f2fd7f60000-    7f2fd81a3000	Deferred        ws2_32<elf>
  \-PE	    7f2fd7f70000-    7f2fd81a3000	\               ws2_32
ELF	    7f2fd81a3000-    7f2fd83d3000	Deferred        mpr<elf>
  \-PE	    7f2fd81b0000-    7f2fd83d3000	\               mpr
ELF	    7f2fd83d3000-    7f2fd8668000	Deferred        wininet<elf>
  \-PE	    7f2fd83e0000-    7f2fd8668000	\               wininet
ELF	    7f2fd8668000-    7f2fd896e000	Deferred        crypt32<elf>
  \-PE	    7f2fd8680000-    7f2fd896e000	\               crypt32
ELF	    7f2fd896e000-    7f2fd8bb1000	Deferred        wintrust<elf>
  \-PE	    7f2fd8980000-    7f2fd8bb1000	\               wintrust
ELF	    7f2fd8bb1000-    7f2fd8f8c000	Deferred        oleaut32<elf>
  \-PE	    7f2fd8be0000-    7f2fd8f8c000	\               oleaut32
ELF	    7f2fd8f8c000-    7f2fd923b000	Deferred        rpcrt4<elf>
  \-PE	    7f2fd8fa0000-    7f2fd923b000	\               rpcrt4
ELF	    7f2fd923b000-    7f2fd9621000	Deferred        ole32<elf>
  \-PE	    7f2fd9260000-    7f2fd9621000	\               ole32
ELF	    7f2fd9621000-    7f2fd9873000	Deferred        winspool<elf>
  \-PE	    7f2fd9630000-    7f2fd9873000	\               winspool
ELF	    7f2fd9873000-    7f2fd9bbf000	Deferred        comctl32<elf>
  \-PE	    7f2fd9880000-    7f2fd9bbf000	\               comctl32
ELF	    7f2fd9bbf000-    7f2fd9e5f000	Deferred        shlwapi<elf>
  \-PE	    7f2fd9bd0000-    7f2fd9e5f000	\               shlwapi
ELF	    7f2fd9e5f000-    7f2fda320000	Deferred        shell32<elf>
  \-PE	    7f2fd9e80000-    7f2fda320000	\               shell32
ELF	    7f2fda320000-    7f2fda62d000	Deferred        comdlg32<elf>
  \-PE	    7f2fda330000-    7f2fda62d000	\               comdlg32
ELF	    7f2fda62e000-    7f2fda858000	Deferred        imm32<elf>
  \-PE	    7f2fda640000-    7f2fda858000	\               imm32
ELF	    7f2fda8d6000-    7f2fdab00000	Deferred        libexpat.so.1
ELF	    7f2fdab00000-    7f2fdad44000	Deferred        libfontconfig.so.1
ELF	    7f2fdad44000-    7f2fdaf77000	Deferred        libpng16.so.16
ELF	    7f2fdaf77000-    7f2fdb187000	Deferred        libbz2.so.1
ELF	    7f2fdb187000-    7f2fdb39d000	Deferred        libz.so.1
ELF	    7f2fdb39d000-    7f2fdb648000	Deferred        libfreetype.so.6
ELF	    7f2fdb648000-    7f2fdb864000	Deferred        version<elf>
  \-PE	    7f2fdb650000-    7f2fdb864000	\               version
ELF	    7f2fdb864000-    7f2fdbb0a000	Deferred        advapi32<elf>
  \-PE	    7f2fdb880000-    7f2fdbb0a000	\               advapi32
ELF	    7f2fdbb0a000-    7f2fdbeae000	Deferred        gdi32<elf>
  \-PE	    7f2fdbb20000-    7f2fdbeae000	\               gdi32
ELF	    7f2fdbeae000-    7f2fdc297000	Deferred        user32<elf>
  \-PE	    7f2fdbed0000-    7f2fdc297000	\               user32
ELF	    7f2fdc61f000-    7f2fdc841000	Deferred        lin-vst-server<elf>
  \-PE	    7f2fdc630000-    7f2fdc841000	\               lin-vst-server
ELF	    7f2fdc841000-    7f2fdca53000	Deferred        libnss_files.so.2
ELF	    7f2fe35ec000-    7f2fe3803000	Deferred        libgcc_s.so.1
ELF	    7f2fe3803000-    7f2fe3b0c000	Deferred        libm.so.6
ELF	    7f2fe3b0e000-    7f2fe3d12000	Deferred        libdl.so.2
ELF	    7f2fe3d12000-    7f2fe40d8000	Deferred        libc.so.6
ELF	    7f2fe40d8000-    7f2fe42f6000	Deferred        libpthread.so.0
ELF	    7f2fe4314000-    7f2fe46bc000	Dwarf           libwine.so.1
ELF	    7f2fe46be000-    7f2fe48e6000	Deferred        ld-linux-x86-64.so.2
ELF	    7fff12dbb000-    7fff12dbc000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000020    0
	0000001f    0
	00000014    0
	00000010    0
	0000000f    0
00000012 winedevice.exe
	0000001e    0
	00000019    0
	00000018    0
	00000013    0
0000001c plugplay.exe
	00000022    0
	00000021    0
	0000001d    0
00000023 explorer.exe
	0000002a    0
	00000029    0
	00000028    0
	00000027    0
	00000024    0
00000025 lin-vst-server.exe
	0000002c    0
	0000002b    0
	00000026    0
00000031 (D) Z:\usr\bin\lin-vst-server.exe
	00000038    1
	00000037    0
	00000036    0
	00000035    0
	00000033    0
	00000032    0 <==
System information:
    Wine build: wine-2.0
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 4.10.8-200.fc25.x86_64

**Comment by osxmidi** [comment]
Seems to be some sort of Wine problem, maybe due to an unimplemented or partly implemented function.

Maybe trying to add some real dll's to Wines library list might help.

I'll test some out.

**Comment by Learn-Digital-Audio** [comment]
Cheers!

**Comment by osxmidi** [comment]
If the vst tries to connect to it's site then it might be wininet.

There are tweaks for wininet in winetricks.

**Comment by Learn-Digital-Audio** [comment]
I don't think it tried to connect to it's site when it crashed. It crashed when I tried to open a file that contains my serial number, used for copy protection. There is no challenge/response going on, it's just a tiny serial number file with an invented '.tdr' (company name) extension.

When i try to open the serial file in a text editor it says "The file you opened has some invalid characters. If you continue editing this file you could corrupt this document.", could that be a problem?

**Comment by Learn-Digital-Audio** [comment]
The free version is really good too, and that has no serial number. If you got that working it would be a victory for free awesome software :)

**Comment by osxmidi** [comment]
It seems like it might be a file corruption thing.

It could still be checking for an internet connection (via wininet) even though it might be registering offline.

I don't know much about the plugin but the manual seems to say that there is offline and online registering.

I got the free version working ok, 64 bits and 32 bits but it crashes whenever I hit the ? button whatever that is.

**Comment by Learn-Digital-Audio** [comment]
Thanks for your input! The main thing that is so great about this plugin is the automatic volume matching as you alter the EQ, it is perfect and the only software that can do this. It really is a breakthrough.

I will leave it for now as so much other software is working OK, maybe I will investigate more in the future. Cheers.
