### ISSUE TITLE
Difference between this vst-bridge and airwave

### ISSUE THREAD

**Issue by zezic** [osxmidi/LinVst#30]
Just asking. Can you explain point difference between LinVst, https://github.com/abique/vst-bridge and https://github.com/phantom-code/airwave?
I don't read sources yet (sorry), but it's interesting to know technical difference between those 3 variants of VST bridges.

**Comment by osxmidi** [comment]
LinVst has nothing much in common with Airwave or Abique's vst-bridge from a code point of view.

I think Abique does great things with his vst bridge and other things like the u-he ports btw.

Airwave seems to be based on Abique's vst-bridge.

LinVst derives from wacvst which was a vst bridge/wrapper for the mac and was probably one of the first vst bridge/wrappers to use wine.

LinVst interfaces into wine in a different way than Airwave or Abique's vst-bridge especially with the window display part and LinVst has some real time optimisations that hopefully result in good performance and there are some optimisations for Reaper's automation that might also help in other daws.

**Comment by zezic** [comment]
Huh, so, that's definitely interesting to try now. Thank you!
