### ISSUE TITLE
build issue ubuntu 17.10

### ISSUE THREAD

**Issue by spamatica** [osxmidi/LinVst#31]
Hi, trying to build LinVst, had success with building under 17.04 (did not get it fully working though). For ...reasons.. I updated to 17.10 and now I get the following error when trying to build:

wineg++ -m32 -O2 -DSEM -DDRAG -DWINONTOP -I/usr/include/wine-development/windows -c paths.cpp -o paths.wine32.o
wineg++ -m32 lin-vst-server.wine32.o remotepluginserver.wine32.o paths.wine32.o -L/usr/lib/i386-linux-gnu/wine-development -lpthread -lrt  -o lin-vst-serverst32.exe
ld: Relocatable linking with relocations from format elf64-x86-64 (/usr/lib/x86_64-linux-gnu/wine/libwinecrt0.a(exe_entry.o)) to format elf32-i386 (lin-vst-serverst32.sJt4n9.o) is not supported
winebuild: ld failed with status 1
winegcc: /usr/lib/wine/winebuild failed
Makefile-standalone-6432:39: recipe for target 'lin-vst-serverst32.exe' failed
make: *** [lin-vst-serverst32.exe] Error 2

A missing package or what might be the reason?
Wine version is: wine-2.0.2 (Ubuntu 2.0.2-2ubuntu1)

**Comment by osxmidi** [comment]
That seems to be a 32 bit library linking error that I've also had in the past when some 32 bit winegcc component isn't installed properly.

winegcc is trying to link 32 bit code with 64 bit libraries whereas it should be linking with 32 bit libraries and it creates that error.

Try installing the 32 bit library packages again.

On Ubuntu/Debian 64 bits

sudo dpkg --add-architecture i386

sudo apt-get install libc6-dev-i386

sudo apt-get install gcc-multilib g++-multilib

sudo apt-get install libwine-development-dev:i386

**Comment by Zipdox** [comment]
Why is it compiling 32-bit anything in the first place
