### ISSUE TITLE
Parameters name doesnt shows up correctly

### ISSUE THREAD

**Issue by re23071998** [osxmidi/LinVst#33]
Only an half or so.
Pic: https://i.imgur.com/uLVnFNm.png

**Comment by osxmidi** [comment]
Thanks for the bug report.

I've fixed it.

It seemed to be because some plugins go over the 8 character limit for the parameter name function.

**Comment by re23071998** [comment]
Fixed, Thanks!!

**Comment by re23071998** [comment]
Serum still has this issue,
and parameter values still limited to 8 character for any plugins
https://i.imgur.com/NVl2GJ3.png

**Comment by osxmidi** [comment]
Thanks.

I missed a few parameter names.

I've updated the code and the Debian Stretch binary release.

**Comment by re23071998** [comment]
Fixed!!

**Comment by re23071998** [comment]
waves h-delay had this issue, and maybe another waves plugins
