### ISSUE TITLE
Can not initiate an instance of Synth1 inside Renoise

### ISSUE THREAD

**Issue by alesandar** [osxmidi/LinVst#36]
Anyone there who was able to initiate a Synth1 instance inside any DAW?

I am able to get most of my Windows VST plugins under Renoise 3.1 on Arch Linux, but a few of them get stuck during the Renoise plugin initialization process and Synth1 is the one I am missing the most.

I remember there was some special signal-handler inside the source-code of [airwave](https://github.com/phantom-code/airwave), without which Renoise was unable to do properly some stuff. I do not know if it's related at all. Also note that airwave wasn't handling that plugin very well (only visually - transparent glyphs in the presets section, but this one must have been related to a wine issue).

**Comment by osxmidi** [comment]
It's because Synth1 doesn't declare itself as a synth.

A workaround is install sqlitebrowser

sudo add-apt-repository ppa:linuxgndu/sqlitebrowser-testing

sudo apt-get update && sudo apt-get install sqlitebrowser


then follow the instructions from dblue about enabling synth1 as a synth (issynth)  http://forum.renoise.com/index.php/topic/33246-renoise-doesnt-recognize-predator-as-a-vsti/

right click to select hidden folder browsing with sqlitebrowser

The database file to edit is /home/user/.renoise/V3.1.0/ CachedVSTs_x64.db

**Comment by osxmidi** [comment]
So you add synth1's path to VST_PATH and then renoise scans it.

Then exit renoise and edit the database file  /home/user/.renoise/V3.1.0/ CachedVSTs_x64.db (enable hidden folders with right click in the file browser).

Go to the "Browse Data" tab in SQLite browser and choose the CachedPlugins table and then locate the entry for Synth1 and enable the "IsSynth" flag from "0" (false) to "1" (true) and save.

**Comment by osxmidi** [comment]
The above is if it's that IsSynth problem.

I just tried Synth1 out and I didn't need that IsSynth workaround and I just chose Synth1 from the right hand side "No plugin loaded" option and I loaded Synth1, but I don't really know how to use Renoise but Synth1 did load that way.

**Comment by alesandar** [comment]
It's weird that you've loaded it successfully. I do not think that it is that type "isSynth" problem, because airwave was able to do it out-of-the-box, except the rendering issue. Your Synth1 is probably v1.13-beta3, found on the KVR download redirectin URL, right? I will try to redownload it and copy linvst.so again.

**Comment by alesandar** [comment]
Initializing plugins... and it has just scanned the 32-bit version successfully! I am not really sure what was the problem, but the synth-detection in Renoise is very helpful. I believe that I have experienced similar problems in the past, thanks a lot.

Any ideas why it can not initialize the 64-bit version? I've used "Makefile-embed-6432" when I built the source.x

Also note that the same Synth1 rendering issue, as the one that used to occur with airwave, is also present with LinVst. Click on the preset selector field [1:initial sound] and see all the blank fields. However, I believe that this one is related to wine.

**Comment by osxmidi** [comment]
Yes v1.13-beta3.

I used the Synth1 64 bit version which was ok, maybe it's a wine thing on your system. hard to tell.

I noticed the presets but I don't think much can be done about it.

**Comment by osxmidi** [comment]
I've just been experimenting and Synth1 seems to need it's preset paths setup.

I don't know if I'm doing it totally right but I have got some presets to load.

Choose the opt button and then for the ExtBank(zip) browse and locate the zipbank folder in the Synth1 folder.

Then choose Program bank folders 00 and browse and locate the soundbank00 folder in the Synth1 folder etc.
