### ISSUE TITLE
Inter Plugin communication

### ISSUE THREAD

**Issue by lentferj** [osxmidi/LinVst#37]
Melda MCompare and Waves NLS have modes where different instances of the plugin communicate with each other. This does not work for both of these, probably because each instance runs in it‘s own wine context. On the other hand it does work for Meterplugs Perception (Source and Conroller plugin detect each other and communicate). Maybe there is a way to also make this work for NLS and MCompare?

**Comment by osxmidi** [comment]
Communication between plugin instances won't work with the LinVst wrapper (and other wrappers/bridges)  unfortunately.

**Comment by lentferj** [comment]
That was my expectation, too. Strangely or or rather fortunately it does work with Meterplugs Perception perfectly.
