### ISSUE TITLE
Waves plugins don't report latency

### ISSUE THREAD

**Issue by lentferj** [osxmidi/LinVst#38]
Don't know if this is an issue with Waves plugins or linVST/WINE. As far as I can tell none of the Waves plugins report plugin latency (checked in Ardour via "Edit with simple controls") even those that do have audible latency (Kramer HLS adds about 3.35ms of latency measures with LSP latency meter and tested in Mixbus parallel processing). Other plugins like IK Mulimedia Black 76 or Toonebosters Barricade v4 do report their latency.

**Comment by lentferj** [comment]
I tried with extracting the plugins with shell2vst.exe, but still no latency (or rather 0 samples reported when their obviously is latency) reported via "simple controls".

**Comment by osxmidi** [comment]
LinVst does handle latency, so I'm not sure why it's not working with Waves.

**Comment by lentferj** [comment]
I had some friends check the latency reporting in Mixbus on Mac and Win just make sure, and there it works (e.g. J37 Master Tape).

**Comment by osxmidi** [comment]
No, I'm still aware of it but right now Waves Central is broken in Wine Staging 3.12 and 3.13 so I'm trying to fix that and then I'll test some Waves plugins out.

Waves plugins should be no different to others when reporting the latency, so I'll see what happens.

**Comment by lentferj** [comment]
Very cool, thank you very much in advance. I created a list of Waves plugins and measured latency, if it helps.

**Comment by osxmidi** [comment]
I think I realize what's happening.

It seems to be a timing thing where the Waves plugin initially report 0 latency when the DAW first calls the Waves plugin but then the Waves plugin seems to update the latency afterwards and so the DAW misses it.

If I put in a latency printout when the GUI opens (much later than when the DAW first calls the Waves plugin for the latency) then the Waves plugins report a latency that is not 0.

I'll see what I can do about implementing a later latency call for the Waves plugins.

**Comment by osxmidi** [comment]
I've done some changes to the code.

Reaper seems to report the Waves plugin latency ok now.

**Comment by lentferj** [comment]
Great. I'll compile from source and give you feedback on behaviour in Ardour/Mixbus later today!

**Comment by lentferj** [comment]
I can confirm latency reporting works now in Mixbus and the numbers are very close to what I previously measured with LSP latency meter. Great work! Thanks a lot... Waves plugins have suddenly become actually useful ;)

**Comment by Schroedingers-Cat** [comment]
Using the latest release of LinVst, plugins from Voxengo and DMGAudio don’t seem to report any latency to Reaper v6.25. Tested with Voxengo Soniformer 3.12 and DMGAudio Multiplicity 1.07. Any idea why it’s not working? Native plugins from u-he report their latency just fine and even change it depending on plugin settings.
