### ISSUE TITLE
Win32 plugins not working / how to debug

### ISSUE THREAD

**Issue by tavasti** [osxmidi/LinVst#39]
I built LinVst with winehq-stable using Makefile-embed-6432, but Mixbus finds only 64 bit VSTs. How I could debug what is going wrong?

**Comment by lentferj** [comment]
The 32bit plugins are in a win32 Prefix, too?
Did you add the correct path for the 32bit plugins to Mixbus' VST search path?
Did you check the Mixbus log window? It usually tells quite a bit about what's going wrong, also with linVST wrapped plugins.
Also, you can try to start Mixbus from console, mabye that will give you more information.

**Comment by tavasti** [comment]
- Now 32bit plugins are on 32bit prefix (in the beginning they were not under any wine dir, lmms uses them from any location)
- Mixbus has correct dirs
- Mixbus says 32 bit plugins are blacklisted, no reason given, not in logs or output to console.

**Comment by tavasti** [comment]
Looks like 64bit ardour / mixbus can't use 32bit vst plugins, so problem is not related at all to LinVst
