### ISSUE TITLE
Addictive Drums, drag and drop not working

### ISSUE THREAD

**Issue by occulkot** [osxmidi/LinVst#40]
XLN Addictive drums 2 give ability to drag and drop midi beat sequence into the editor.

It works perfectly with on wine-staging reaper, but on reaper@native, mixbus4 i cannot drop midi onto the DAW. Cursor have block icon, same happen when i use prerecorded (with addictive drums) wav which should also drop on DAW Track.

Despite of that - AD2 works perfectly :)

OS: Arch linux
wine: wine-3.11 (Staging)
linvst: latest compiled with AUR

**Comment by osxmidi** [comment]
MixBus and Ardour don't support drag and drop in their vst plugin windows.

**Comment by occulkot** [comment]
Strange, its working fine on Mixbus@windows. I suspect the problem might be with location (but i dont know exactly how d'n'd works), ie. when draging from Addictive Drums pointer contains location of file to by dropped but instead of linux location schema it is windows file pointer. Strange though that it doesnt work on Mixbus@wine but works on Mixbus@windows.

**Comment by osxmidi** [comment]
Yes, drag and drop is probably enabled for the Windows Ardour/Mixbus vst window but it doesn't seem to be for the Linux Ardour/Mixbus vst window that LinVst has to deal with on Linux.

Linux Reaper and Linux Tracktion/Waveform are drag and drop ok

**Comment by occulkot** [comment]
thanks for anwser!

**Comment by xaptronic** [comment]
Hi - Sorry to be digging up old conversations, but am I reading this right that Drag and Drop from AD2 into Native running Reaper is expected to work? Are there any tips for troubleshooting / debugging this on my own?

**Comment by gandalf3** [comment]
@xaptronic I just ran into this myself.. If you haven't already found a solution, I found [this page](https://github.com/osxmidi/LinVst/tree/master/Tested-VST-Plugins) which mentions that the plugin writes midi data to a file called `mtpdk.mid` in `$XDG_DESKTOP_DIR`. It also definitely mentioned working drag and drop straight from the linvst window, at least on the windows version of the plugin, but I tried it (with the 64 bit version and without the d2d1 workaround which didn't seem to be necessary anymore?) and still wasn't able to drag and drop into native reaper.

**Comment by xaptronic** [comment]
Hi @gandalf3 - I did indeed discover this work around. If I remember correctly, the path in the page you linked to was "almost" correct in my setup. I also setup a symlink to the folder that the .mid file shows up in so that it was closer to my Reaper projects and then could just drag an item and then use Reaper media viewer to grab the file and place it in my project. I have used MT Power Drummer, however, not in this setup. If Drag and Drop doesn't work in MT Power Drummer either, then perhaps this issue isn't related to LinVst.

**Comment by rauldipeas** [comment]
Here, d'n'd never works on REAPER, in any plugin.

**Comment by xaptronic** [comment]
https://www.reddit.com/r/wine_gaming/comments/afynzy/making_drag_and_drop_work_inside_of_wine/ Ill try this, maybe a missing dll or something along those lines. If I can run via command line or maybe find a log somewhere. Will try to look at some point and see if there's any clues.

**Comment by gandalf3** [comment]
I can drag and drop the midi file from pcmanfm into reaper, so at least some form of drag and drop is working.

**Comment by rauldipeas** [comment]
> I can drag and drop the midi file from pcmanfm into reaper, so at least some form of drag and drop is working.

From file manager it works, but from plugins interface not.

**Comment by xaptronic** [comment]
I see the same thing: I can drag and drop from something native, but from something running through wine it does not work. I will try to get some debug info out of the wine process at some point over the weekend, as the above post suggest it may be something like a missing dll but could also be some other incompatibility.

**Comment by xaptronic** [comment]
I did not have much luck get any debug output out of wine related to drag and drop. I also tried installing a couple things from winetricks but that did not work either. I suspect if drag and drop from wine to native was solved there would be a more easily findable solution :/

**Comment by vlig** [comment]
The same is for me! Moreover, when I tried to drag out a test midi-item, the Reaper and jack itself just hung on, and only rebooting was the solution. I don't want to go back to the wine(((
