### ISSUE TITLE
Brainworx bx_masterdesk gui notworkin in Ardour/Mixbus and not loading in Bitwig

### ISSUE THREAD

**Issue by lentferj** [osxmidi/LinVst#44]
I tried to load the demo version of Brainworx Masterdesk plugin into Ardour and Mixbus. There is load, but looks very strange - and is practically unusable. Bitwig scans the plugin, but hangs on the scan.

A demo version is available here after registration:
https://www.plugin-alliance.com/en/products/bx_masterdesk.html

![grafik](https://user-images.githubusercontent.com/5664183/44122726-702b524e-a025-11e8-98c8-6c0254a0d9e3.png)

**Comment by lentferj** [comment]
Did your latest changes make it work?

**Comment by tnafele** [comment]
Any update on PA plugins? I tried two of them... They actually work fine except of the missing knobs. Could this also be an issue with d2d1.dll? I tried to install a native one, but I don't know which version would be needed. The few I tried made the GUI crash.
