### ISSUE TITLE
I can't get Serum to work

### ISSUE THREAD

**Issue by BillMess** [osxmidi/LinVst#46]
I'm using Linux Mint 19, the latest stable version of wine from the winehq website, and the latest Ubuntu version of Bitwig Studio 2.3.5. I've built LinVst with the Makefile-embed-6432 option, and I got every Vst plugin I want to work except for Serum.

By default, both the 32 bit and 64 bit version of Serum displays with a weird graphical glitch:
![screenshot from 2018-08-27 16-49-08](https://user-images.githubusercontent.com/36426287/44689742-2584c880-aa1e-11e8-8d4b-729ecf78945f.png)

Disabling d2d1 displays correctly, but it runs at like 5 frames a second which is unusable.

I tried the d2d1 version 6.1.7601.17514 32 bit dll override and set d2d1 to native, but then it displays a blank black screen:
![screenshot from 2018-08-27 16-45-57](https://user-images.githubusercontent.com/36426287/44690025-17837780-aa1f-11e8-988c-af4d815b366f.png)

I also tried setting HKEY_CURRENT_USER Software Wine Direct3D MaxVersionGL to 30002, but it didn't help in any of the situations. I also tried using wine staging, but that also didn't help. I also tried winetricks gdiplus, but it didn't help.

I'm using an AMD R9 285 graphics card. I tried it both with the default open source drivers that come with Linux Mint and the latest drivers from the padoka ppa.

Do you have any ideas how I can get this to work? I got Bitwig Studio recently, and now Serum is the only thing keeping me from finally leaving Windows.

**Comment by osxmidi** [comment]
d2d1 is a problem as it's not implemented in wine in a complete way.

Some seem to have success with d2d1 6.1.7601.17514 but others may not, maybe it's got something to do with some cards opengl drivers, I don't really know.

**Comment by BillMess** [comment]
Okay. That's a shame. Looks like I'll have to stick with Windows until wine fixes the problem.

**Comment by osxmidi** [comment]
Wine DXVK might help, I don't know much about it but apparently someone used it for Serum.

**Comment by BillMess** [comment]
Using Wine DXVK didn't help me either. Maybe I should just get a new graphics card.

**Comment by BillMess** [comment]
I tried removing my graphics card and reinstalling the OS using the Intel processor's built in graphics, but it produced the exact same result. Maybe I'm doing something wrong?

**Comment by BillMess** [comment]
I tried running Serum using the Windows version of Bitwig Studio under wine. It produces the same result except that with d2d1 disabled, it actually runs smoothly at 60fps instead of the 5fps I was getting using LinVst. There is noticeable aliasing and it flickers a bit, but it's more usable. However, Bitwig itself runs choppy and the windows are glitchy, so it's still unusable for me.

**Comment by nkkky** [comment]
Any changes on this? I've tried running Serum with Bitwig 3.3.10 on Ubuntu 20.04 LTS but the plugin "takes to long to load" after converting it with linvstxconvert and is not listed in the Plugin Folder in Bitwig.

**Comment by osxmidi** [comment]
> Any changes on this? I've tried running Serum with Bitwig 3.3.10 on Ubuntu 20.04 LTS but the plugin "takes to long to load" after converting it with linvstxconvert and is not listed in the Plugin Folder in Bitwig.

Serum is one of those plugins that rely on d2d1.

Wine tkg might be able to handle it, but I havn't tested it.

**Comment by nkkky** [comment]
I got it now with Airwave.

**Comment by osxmidi** [comment]
> I got it now with Airwave.

I've altered the loading, so Serum should load with Bitwig now and Wine 6 stable (Wine tkg might have some problems as it's experimental).

Choose run individually in settings plugins.
