### ISSUE TITLE
Ozone 8

### ISSUE THREAD

**Issue by durutti** [osxmidi/LinVst#47]
Although all other plugins form izotope ozone 8 work on mixbus 4.3 -ardour 5.12 Tonal balance control crashes the host. I am attaching the backtrace. Do you have any ideas why this might happening.

[backtrace.txt](https://github.com/osxmidi/LinVst/files/2363239/backtrace.txt)

**Comment by osxmidi** [comment]
Seems like it's probably a Wine d3d error of some sort.

Maybe some versions of Wine meant for gaming might help, I don't know much about them but maybe DXVK
