### ISSUE TITLE
Massive CPU usage increase after opening plugin gui

### ISSUE THREAD

**Issue by lentferj** [osxmidi/LinVst#48]
I found a strange behaviour with Waves (and other plugins, e.g. Noveltech Vocal enhancer).
When inserting the plugins in Ardour 5.12 without opening the plugin gui the CPU consumption of the corresponding lin-vst-server.exe.so process is minimal.
When you open the gui, the process will use 60-100% of one core (as seen in top). That would not be a problem an tolerable, if it went back to a normal usage after closing the plugin gui.
Unfortunatley it is not that way. After closing the plugin gui the cpu consumption of the process remains on the same high level.

**Comment by lentferj** [comment]
This seems to be a Ardour specific behaviour. I just tried with Noveltech Vocal Enhancer in Bitwig (I don't use Waves in Bitwig). There I see the same increase on opening the gui, but when I close the gui, the CPU consumption goes back to normal.

**Comment by osxmidi** [comment]
The 60-100% seems high.

I havn't seen that myself with the 4 Waves plugins that I've tested.
.
I'll look into it.

**Comment by osxmidi** [comment]
I can't duplicate it on my system.

It might have something to do with Wine and your video card drivers/setup. maybe.

https://drive.google.com/file/d/1g9KPXwJdCRjSnlf7G1DeVX3XXOCiTZGw/view?usp=sharing

**Comment by lentferj** [comment]
I am using a Radeon card with amdgpu driver. T-RackS plugins (which live in their own prefix) don‘t show this behavior. I have to cross check the overrides of my Waves and T-RackS prefixes. Could you post your overrrides you use for Waves?

**Comment by osxmidi** [comment]
I don't have any overrides but some Waves plugins seem to need a mfc140.dll override.

I would guess that it's some Wine GUI thread that's behaving weirdly for some reason.

**Comment by lentferj** [comment]
Could you try the HLS Kramer plugin in Ardour, too, please?

**Comment by lentferj** [comment]
Did you have top -c running in a terminal when testing in Ardour? DSP load of 18,4% seems pretty high assuming you have maybe 4 cores and HT and Ardour isn’t really doing anything except displaying the HLS plugin.

**Comment by osxmidi** [comment]
I'm using my test machine which is a 10 year old dual core laptop that's pretty slow.

**Comment by lentferj** [comment]
Ok, that explans it. For whatever reason I can not reproduce it with the HLS plugin anymore :/. I am not sure if I maybe used a self compiled debugging version of Ardour yesterday (as I am coding atm). Thank you very much for cross checking. The problem remains with the Noveltech plugin, though. But this is Plugin Alliance and I have to dig deeper how to make them work in a usable way, anyway.

**Comment by lentferj** [comment]
Seems to be d2d1 related. When I use native the CPU hit for Vocal Enhancer is ok, but the GUI is broken. With d2d1 disabled the GUI looks fine, but the CPU hit is huge. I tried an override with a Win7 d2d1.dll but that lets the plugin crash.
