### ISSUE TITLE
Tracktion 7 / Reaper (native) drag & drop from plugin window to editor

### ISSUE THREAD

**Issue by marcsabat** [osxmidi/LinVst#50]
I am trying to use MT Power DrumKit 2 (https://www.powerdrumkit.com/) under LinVst and it works fine except for the fact that I can't seem to drag "grooves" from the plugin window to the editor (tried both Tracktion 7 and Reaper native in embedded mode).

README is confusing for me because it says the following:

> (Drag and drop is not enabled) for items dragged and dropped from the vst window to the DAW/host window.

That would explain why it is not working. However it also says this:

> MT-PowerDrumKit (Disable d2d1 in the Libraries section of winecfg) (drag and drop ok with the LinVst embedded window and standalone window drag and drop enabled versions).

So: is drag&drop enabled from the plugin window to the editor or not? If it's a matter of needing some "love" what would be the changes needed in the code to make this feature work?

BTW, I am using the binaries found here: 
https://github.com/osxmidi/LinVst/releases/tag/2.3

**Comment by osxmidi** [comment]
Hi,

LinVst can only support drag and drop into the plugin window and not between the plugin and the DAW because of various limitations in how Wine works etc.

There is a workaround for Reaper though https://forum.cockos.com/showthread.php?p=2030985

**Comment by marcsabat** [comment]
That's a neat workaround giving the circumstances!

I took me a while to make this work because the exported file (mtpdk.mid) was saved in /home/<myusername/Documents and I expected the file to be found somewhere inside the ~/.wine/drivce_c folder.

Thanks for you efforts in LinVst and fast response!
