### ISSUE TITLE
dssi-vst-server: ERROR

### ISSUE THREAD

**Issue by wastee** [osxmidi/LinVst#51]
> Running well in wine REAPER.

# wine version
wine-3.20 (Staging) on Arch Linux

# REAPER version
Native REAPER v5.962 (get ERRORS)
wine REAPER v5.941

# winecfg settings
Native library:
- *atl100
- *msvcp100
- *msvcr100
- *vcomp100
- msvcp140

Stoped library:
- d2d1

# vst
iZotope.Ozone.8.Advanced.v8.02

# ERRORS
dssi-vst-server: ERROR: VST entrypoints "VSTPluginMain" or "main" not found in DLL "/home/tee/.wa/drive_c/vst/iZotope/64/iZOzone8VintageLimiter.dll"

> all iZOzone8*.dll show ERROR.

# what i had tried

remove iZotope folder. Native REAPER works well.

------------------------

How can i fix it? And what else do I need to provide? Thanks.

**Comment by osxmidi** [comment]
I think that Ozone has multiple dlls that get used by the main dll which is Ozone 8,dll.

So, I think that renaming linvst.so to Ozone 8.so and then loading Ozone 8 in the DAW is the way to go, or it seems to work ok but I havn't tested all of the Ozone features.
