### ISSUE TITLE
Cmake contribution.

### ISSUE THREAD

**Issue by Bzerk-Seven** [osxmidi/LinVst#53]
Hello,

I wrote sime simple CMake build files for the project ( for the moment, they only reproduce the Main Makefile process with same options).
I did not touch any of the files in teh repo, just added a liblinvst to hold the CMake file to build the library and an other one for the exe. It is necessary as they use 2 different compiler.
So far I can build on an ubuntu 18.04. I would like to extend those script to create deb packages (I have not dug this part of CMake yet).

Would you be interested in such a contribution ?

**Comment by osxmidi** [comment]
Yes, if it all works ok then I'd probably include it.
