### ISSUE TITLE
Make Releases more obvious by including a link in Readme.md

### ISSUE THREAD

**Issue by x7i7l** [osxmidi/LinVst#54]
This is a remarkable piece of software, but lacking knowledge in this stuff it took me a long time to discover that binaries were available under the "Releases" section. I think that users like me would benefit from a link to this displayed prominently in the Readme.md.

**Comment by osxmidi** [comment]
Good idea.

I've made a link in the Quick Start section of the Readme.

**Comment by x7i7l** [comment]
Nice one. Thanks!
