### ISSUE TITLE
PSP Audioware Lexicon PSP42 - strange graphics

### ISSUE THREAD

**Issue by lentferj** [osxmidi/LinVst#55]
All the PSP plugins seem to work like a charm with LinVST. But with this one I stumbled into unexpected problems, as it is one of the older plugins of theirs.

The GUI is a bit wierd. The animated content is frizzy.

![bildschirmfoto vom 2018-12-23 10-05-37](https://user-images.githubusercontent.com/5664183/50382235-f19f7400-069a-11e9-98ed-7fa64eceec28.png).

These DLLs seems to be involved.

$ strings Lexicon\ PSP42.dll | grep -i dll
shell32.dll
This indicates a bug in your application. It is most likely the result of calling an MSIL-compiled (/clr) function from a native constructor or from DllMain.
USER32.DLL
ADVAPI32.DLL
KERNEL32.dll
USER32.dll
GDI32.dll
COMDLG32.dll
ADVAPI32.dll
SHELL32.dll
ole32.dll
gdiplus.dll
Lexicon PSP42.dll
dllli

I tried different settings for gidplus in winecfg but it didn't change anything.
Any ideas?

**Comment by lentferj** [comment]
In case someone wants to try, a demo can be donwnloaded here:
http://www.pspaudioware.net/release/Lexicon_PSP42/Windows/native/

**Comment by osxmidi** [comment]
I tried some different versions.

1.5.3 seems ok but 1.6.2 isn't.

Seems like a Wine problem of some sort.

**Comment by lentferj** [comment]
Thanks for following, should have tried older versions, too. I can confirm 1.5.3 works for me, too.
