### ISSUE TITLE
No load GUI 

### ISSUE THREAD

**Issue by pdanc** [osxmidi/LinVst#56]
LinVst 2.32
Xubuntu 16.04 (x64)
Wine-staging 4.0-rc4

I install LinVst follow the official instructions (copy lin-vst-server files on /usr/bin/). Then I use the linvstconverter and obtain the '.so ' files. When I open Carla or QTractor the plugins load but without GUI. I can play instruments but no use the interface. On Carla I have the next log with Charlatan VSTi:

`LinVst version 2.32
Loading  /home/trn/borrar/vss/Charlatan_x64.dll
002a:fixme:x11drv:X11DRV_DestroyNotify window 0x3004e/5200001 destroyed from the outside
Plugin refused to open its own UI`

I try disabled d1d2 .dll but nothing happens. Also I try another version of LinVst (in this repository only one release): LinVst 1.7.6 from AVLinux repositoriy; with that version I can load GUI of vst but I can't move or close it, because the soft don't create the window.

I use two screens, but I set a one of them like 'primary screen', 'coz another users [solved](https://forum.renoise.com/index.php/topic/47839-solved-linux-windows-vst-dont-show-up-their-gui/) similar issue deactivating two screens. 

Similar issue in this [thread](https://linuxmusicians.com/viewtopic.php?f=47&t=19179&hilit=linvst) on LinuxMusicians.

**Comment by osxmidi** [comment]
If LinVst is run with another wrapper then gui etc problems might happen.

LinVst is made to run directly with the DAW and it's windows.

**Comment by pdanc** [comment]
That's true @osxmidi, on Ardour everything is ok :+1:
But what happen with Qtractor, is a powerful DAW with good handle of fxp and fxb files. I have problems with Qtractor v. 0.9.3

**Comment by osxmidi** [comment]
Qtractor 0.8.0-1 (Debian Stretch) seems to abort the vst scan for LinVst plugins.

Qtractor seems to do the same with Airwave (post by glowrak guy at https://www.linuxmusicians.com/viewtopic.php?t=17041)

I don't think there is much I can do but I will look into the qtractor scan problem and see if I can come up with something.
