### ISSUE TITLE
Unfiltered Audio plugins work in Reaper, not in Bitwig

### ISSUE THREAD

**Issue by x7i7l** [osxmidi/LinVst#57]
System: Lenovo B580, Ubuntu Studio 18.10, LinVst 2.3, Bitwig 2.4.3

Steps to Reproduce
1) Install Unfiltered Audio Plugin (ie Sandman Pro https://www.plugin-alliance.com/en/products/unfiltered_audio_sandman_pro.html)
2) Run the standard linvst procedure to create a .so file for the plugin
3) Point Bitwig to the directory where Sandman Pro is installed.

Expected Result
Bitwig finds Sandman Pro

Actual Result
Bitwig attempts to load the plugin for a long time before giving a message that "The plugin Sandman Pro is taking a long time to load." At which point the user can wait longer or abort. Waiting longer does not allow the plugin to resolve.

Additional Information
In Reaper, the Unfiltered Audio plugins load with linvst.
In Bitwig, other windows vst plugins load (ie Fab Filter) with linvst.
In Bitwig, it is possible to load the Unfiltered Audio plugins using "Airwave" (https://github.com/phantom-code/airwave).

**Comment by osxmidi** [comment]
I've made some changes and released LinVst version 2.4.

Unfiltered Audio Plugin seems to be ok on my system with the LinVst 2.4 changes.

**Comment by x7i7l** [comment]
Yes, you're right. Everything is working with 2.4.
Bravo!
