### ISSUE TITLE
VST3 supported?

### ISSUE THREAD

**Issue by wastee** [osxmidi/LinVst#59]
I notice "DDMF Metaplugin VST3 to VST2 wrapper (Drag and Drop VST3 files is ok)." in README.md file.
I dont't know what DDMF means. I tired to copy a linvst.so file to vst3 file path and rename it. Like what i did to vst2. 
It didn't work.

**Comment by osxmidi** [comment]
DDMF Metaplugin (the vst2 version) https://ddmf.eu/metaplugin-chainer-vst-au-rtas-aax-wrapper/ can wrap vst3 plugins and make them appear as vst2 plugins.

So, using the vst2 version of DDMF Metaplugin with LinVst, means that LinVst will load the DDMF Metaplugin and then DDMF Metaplugin can load vst3 plugins and so the DAW can then use the vst3 plugins.

DDMF Metaplugin has an interface a bit like Carla, where input and output connections between the DAW and the vst3 plugin can be made on a track.
DDMF Metaplugin seems to work pretty well with LinVst from my tests.

**Comment by wastee** [comment]
I tried "DDMF Metaplugin 3.2.1". 
But i can't see any UI in wine/native REAPER. 
![image](https://user-images.githubusercontent.com/22229962/50641475-05a07b00-0fa3-11e9-90fe-a82aa39d3f13.png)

What i miss? Thanks for your help.

--------------------

OS: Arch Linux
wine: wine-4.0-rc4 (Staging)

**Comment by osxmidi** [comment]
I think what might be happening is due to d2d1.
DDMF Metaplugin uses d2d1 and some video cards can't handle Wines d2d1, so d2d1 might need to be disabled by starting winecfg and selecting the Libraries tab and adding d2d1 and then editing the d2d1 entry and choose disable.

**Comment by osxmidi** [comment]
DDMF Metaplugin also needs the Microsoft Visual C++ 2010 Redistributable Package which is usually installed by default but if there is a problem then it is possible to also install it by using winetricks vcrun2010

**Comment by wastee** [comment]
Thanks for your advice. That's weird. Because i had disable d2d1 when i use serum VSTI.
And vcrun2010 already installed. Maybe i should swith to other version or try another way.

**Comment by wastee** [comment]
Finally  i use ddmf metaplugin v2.6.7.
It works!
Thanks for your help!
