### ISSUE TITLE
Crash on lin-vst-server.exe launch. Compiled on wine-rt kxstudio . LinVst 1.02

### ISSUE THREAD

**Issue by lolgab** [osxmidi/LinVst#6]
`DSSI VST plugin server v0.986
Copyright (c) 2004-2006 Chris Cannam
fixme:seh:dwarf_get_ptr unsupported encoding 9b
fixme:seh:dwarf_get_ptr unsupported encoding 22
fixme:seh:dwarf_get_ptr unsupported encoding 5d
wine: Unhandled page fault on read access to 0x00000000 at address 0x7f12f1ca4170 (thread 0127), starting debugger...
Unhandled exception: page fault on read access to 0x00000000 in 64-bit code (0x00007f12f1ca4170).
Register dump:
 rip:00007f12f1ca4170 rsp:000000000023f9d0 rbp:0000000000077950 eflags:00010246 (  R- --  I  Z- -P- )
 rax:0000000000000000 rbx:00007f12f1c890a0 rcx:0000000000000000 rdx:0000000000000000
 rsi:00007f12f462b780 rdi:00007f12f462a620  r8:00007f12f462b780  r9:00007f12f4060700 r10:0000000000000001
 r11:0000000000000246 r12:0000000000077950 r13:00007f12f1c87e40 r14:000000007b47c510 r15:0000000000000000
Stack dump:
0x000000000023f9d0:  0000000000000000 0000000000000000
0x000000000023f9e0:  0000000000000000 0000000000000000
0x000000000023f9f0:  0000000000000000 0000000000000000
0x000000000023fa00:  75646f4d74654700 656c646e6148656c
0x000000000023fa10:  0000000000000000 0000000000000000
0x000000000023fa20:  0064006e00690077 005c00730077006f
0x000000000023fa30:  ffff000000ffffff 0000ffffffff00ff
0x000000000023fa40:  0000000000202020 0000000000000000
0x000000000023fa50:  0000000000000000 0000000000000000
0x000000000023fa60:  0000000000000000 0000000000000000
0x000000000023fa70:  0000000000000000 0000000000000000
0x000000000023fa80:  0000000000000000 0000000000000000
Backtrace:
=>0 0x00007f12f1ca4170 WinMain+0x3b0() in lin-vst-server (0x0000000000077950)
  1 0x00007f12f1ca06f5 main+0xc4() in lin-vst-server (0x0000000000000001)
  2 0x00007f12f1ca85f3 __wine_spec_exe_entry+0x82() in lin-vst-server (0x000000000023fd40)
  3 0x000000007b47c5cf in kernel32 (+0x5c5ce) (0x000000000023fe40)
  4 0x000000007bc9c293 call_thread_func+0xd2() in ntdll (0x00007ffed80ac870)
  5 0x000000007bc94f52 RtlRaiseException+0x7d() in ntdll (0x00007ffed80ac870)
  6 0x000000007bc61540 in ntdll (+0x4153f) (0x00007ffed80ac870)
  7 0x00007f12f4882c43 wine_call_on_stack+0x12() in libwine.so.1 (0x00007ffed80ac870)
  8 0x00007f12f4882da9 wine_switch_to_stack+0x8() in libwine.so.1 (0x00007ffed80ac9c0)
  9 0x000000007bc67c6c LdrInitializeThunk+0x31b() in ntdll (0x00007ffed80ac9c0)
  10 0x000000007b483993 __wine_kernel_init+0xb02() in kernel32 (0x00007ffed80adc40)
  11 0x000000007bc68d68 __wine_process_init+0x177() in ntdll (0x00007ffed80adc80)
  12 0x00007f12f4881472 wine_init+0x2c1() in libwine.so.1 (0x00007ffed80add80)
  13 0x000000007c000b52 main+0x81() in <wine-loader> (0x00007ffed80ae288)
  14 0x00007f12f4286830 __libc_start_main+0xef() in libc.so.6 (0x000000007c000d20)
  15 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  16 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  17 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  18 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  19 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  20 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  21 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  22 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  23 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  24 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  25 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  26 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  27 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  28 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  29 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  30 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  31 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  32 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  33 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  34 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  35 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  36 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  37 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  38 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  39 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  40 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  41 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  42 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  43 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  44 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  45 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  46 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  47 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  48 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  49 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  50 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  51 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  52 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  53 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  54 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  55 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  56 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  57 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  58 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  59 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  60 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  61 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  62 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  63 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  64 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  65 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  66 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  67 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  68 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  69 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  70 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  71 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  72 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  73 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  74 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  75 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  76 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  77 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  78 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  79 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  80 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  81 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  82 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  83 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  84 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  85 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  86 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  87 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  88 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  89 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  90 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  91 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  92 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  93 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  94 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  95 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  96 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  97 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  98 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  99 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  100 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  101 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  102 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  103 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  104 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  105 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  106 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  107 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  108 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  109 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  110 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  111 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  112 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  113 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  114 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  115 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  116 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  117 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  118 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  119 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  120 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  121 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  122 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  123 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  124 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  125 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  126 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  127 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  128 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  129 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  130 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  131 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  132 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  133 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  134 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  135 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  136 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  137 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  138 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  139 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  140 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  141 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  142 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  143 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  144 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  145 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  146 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  147 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  148 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  149 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  150 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  151 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  152 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  153 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  154 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  155 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  156 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  157 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  158 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  159 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  160 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  161 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  162 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  163 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  164 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  165 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  166 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  167 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  168 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  169 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  170 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  171 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  172 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  173 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  174 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  175 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  176 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  177 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  178 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  179 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  180 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  181 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  182 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  183 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  184 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  185 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  186 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  187 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  188 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  189 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  190 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  191 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  192 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  193 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  194 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  195 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  196 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  197 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  198 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  199 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
  200 0x000000007c000c49 _start+0x28() in <wine-loader> (0x0000000000000000)
0x00007f12f1ca4170 WinMain+0x3b0 in lin-vst-server: movzbl	0x0000000000000000,%eax
Modules:
Module	Address					Debug info	Name (36 modules)
ELF	        7b400000-        7b811000	Dwarf           kernel32<elf>
  \-PE	        7b420000-        7b811000	\               kernel32
ELF	        7bc00000-        7bd20000	Dwarf           ntdll<elf>
  \-PE	        7bc20000-        7bd20000	\               ntdll
ELF	        7c000000-        7c004000	Dwarf           <wine-loader>
ELF	    7f12ef9fe000-    7f12efc26000	Deferred        imm32<elf>
  \-PE	    7f12efa10000-    7f12efc26000	\               imm32
ELF	    7f12efd76000-    7f12eff9f000	Deferred        libexpat.so.1
ELF	    7f12eff9f000-    7f12f01e2000	Deferred        libfontconfig.so.1
ELF	    7f12f01e2000-    7f12f0407000	Deferred        libpng12.so.0
ELF	    7f12f0407000-    7f12f0621000	Deferred        libz.so.1
ELF	    7f12f0621000-    7f12f08cb000	Deferred        libfreetype.so.6
ELF	    7f12f08cb000-    7f12f0af4000	Deferred        libtinfo.so.5
ELF	    7f12f0af4000-    7f12f0d16000	Deferred        libncurses.so.5
ELF	    7f12f0d16000-    7f12f0f30000	Deferred        version<elf>
  \-PE	    7f12f0d20000-    7f12f0f30000	\               version
ELF	    7f12f0f30000-    7f12f11c6000	Deferred        advapi32<elf>
  \-PE	    7f12f0f40000-    7f12f11c6000	\               advapi32
ELF	    7f12f11c6000-    7f12f1547000	Deferred        gdi32<elf>
  \-PE	    7f12f11e0000-    7f12f1547000	\               gdi32
ELF	    7f12f1547000-    7f12f1901000	Deferred        user32<elf>
  \-PE	    7f12f1570000-    7f12f1901000	\               user32
ELF	    7f12f1c8b000-    7f12f1ead000	Dwarf           lin-vst-server<elf>
  \-PE	    7f12f1c90000-    7f12f1ead000	\               lin-vst-server
ELF	    7f12f1ead000-    7f12f20bf000	Deferred        libnss_files.so.2
ELF	    7f12f20bf000-    7f12f22cb000	Deferred        libnss_nis.so.2
ELF	    7f12f22cb000-    7f12f24e4000	Deferred        libnsl.so.1
ELF	    7f12f24e4000-    7f12f26ed000	Deferred        libnss_compat.so.2
ELF	    7f12f3b3f000-    7f12f3d56000	Deferred        libgcc_s.so.1
ELF	    7f12f3d56000-    7f12f405f000	Deferred        libm.so.6
ELF	    7f12f4062000-    7f12f4266000	Deferred        libdl.so.2
ELF	    7f12f4266000-    7f12f462f000	Dwarf           libc.so.6
ELF	    7f12f4630000-    7f12f484d000	Deferred        libpthread.so.0
ELF	    7f12f4879000-    7f12f4c1f000	Dwarf           libwine.so.1
ELF	    7f12f4c21000-    7f12f4e49000	Deferred        ld-linux-x86-64.so.2
ELF	    7ffed816a000-    7ffed816b000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000020    0
	0000001f    0
	00000014    0
	00000010    0
	0000000f    0
00000012 winedevice.exe
	0000001c    0
	00000019    0
	00000018    0
	00000013    0
0000001d plugplay.exe
	00000022    0
	00000021    0
	0000001e    0
00000023 lin-vst-server.exe
	00000024    0
00000025 explorer.exe
	0000002a    0
	00000029    0
	00000028    0
	00000027    0
	00000026    0
00000126 (D) Z:\usr\bin\lin-vst-server.exe
	00000127    0 <==
System information:
    Wine build: wine-2.0.1
    Platform: x86_64
    Version: Windows XP
    Host system: Linux
    Host version: 4.10.0-21-generic
`

**Comment by osxmidi** [comment]
What vst plugin was being used?

**Comment by osxmidi** [comment]
I'm not sure what the issue might be.

LinVst has been tested with Wine-stable 2.0, Wine-devel 2.4 and Wine-staging 2.8 on a variety of distros.

It could be that Wine-rt is just different in some way and/or maybe the windows vst might need some dll overrides.
