### ISSUE TITLE
Better convert tools for CLI usage

### ISSUE THREAD

**Issue by ghost** [osxmidi/LinVst#66]
The current implementation of the CLI convert tools is not really useful when it comes to batch conversion of directories. I think it should be easier to do this via bash, so I wrote a small script that in my impression is a bit more convenient to use.

I've attached the script file to this issue and I would be happy to share and create a pull request in case you consider it useful! Many thanks.

[convert-cli.zip](https://github.com/osxmidi/LinVst/files/2856234/convert-cli.zip)

**Comment by osxmidi** [comment]
Yes, sure, create a pull request.

**Comment by aaaaaaaaargh** [comment]
PR is merged and the script is in master. Thank you!
