### ISSUE TITLE
Filter cutoff gets set to 50% when MIDI note on received in Bitwig

### ISSUE THREAD

**Issue by lentferj** [osxmidi/LinVst#69]
I experience a strange behaviour in Bitwig 2.4.3 with some synth plugins (at least TAL-UNO-LX and The Legend). When ever a MIDI note on arrives at the plugin, the slider or knob for filter cutoff gets set to 50%. I can then change the value, but as soon as the next note on arrives, it's reset again.

**Comment by lentferj** [comment]
Forgot to mention: I do not see this problem in Ardour/Mixbus or when I load the plugins via carlarack into Bitwig. So it's not a pressing problem, but using the synth directly in Bitwig would be nice for parameter automation, etc.

**Comment by osxmidi** [comment]
That is strange because I can't imagine what would reset it like that.

I'll look into it.

**Comment by osxmidi** [comment]
I can't seem to duplicate it

[img]https://drive.google.com/uc?export=download&id=1awrF2pY62OlSexnDh4wyvBEjoyRbeO6Y[/img]

**Comment by lentferj** [comment]
hmm... you are right. In TAL U-No-LX it seems to be preset depended. I have some patch banks from "The Unfinished" where this happens. Trying to find one from the default banks that exhibits this behaviour. In case you have the "Protozoa" bank, try "PD Quarters".

With Synapse Audio - The Legend it seems to happen with all of the presets.

I will also need to check this on native Windows.....

**Comment by osxmidi** [comment]
I can't seem to duplicate it with the Legend either.

https://drive.google.com/file/d/1trIg76UBL_xtNcSuIhRjULyEn4ZJPio4/view?usp=sharing

**Comment by lentferj** [comment]
That is strange now for sure. Are you using Bitwig 2.4.3?

**Comment by osxmidi** [comment]
Yes version 2.4.3 with Wine Staging 4.2 and MX Linux (Debian Stretch).

**Comment by lentferj** [comment]
I am kinda stuck here.
I am on Debian Stretch with wine-staging-4.1 from winehq
I reinstalled Bitwig, pulled latest master for linVST and recompiled.
I detached all my controllers.

Still I have the same problem. I need to do a screen capture of this phenomenon :(

I tried upgrading to wine 4.2, but the iLok Manager wouldn't work with that. And I did have this behaviour before, with 3.x versions of WINE, too.

**Comment by lentferj** [comment]
Ok, so here is a quick screen capture...
https://youtu.be/Z4Dys5NqX_I

What I find remarkable is that the change of the cut of freq seems to happen only "inside" the plugin. As you can see on the bottom, the value is not transferred back to Bitwig when it changes through "note on". It is when I move the knob with the mouse, though.

**Comment by osxmidi** [comment]
I'll try to test it on some other systems.
