### ISSUE TITLE
keys non-functional in embedded vst window

### ISSUE THREAD

**Issue by myrocketship** [osxmidi/LinVst#7]
Using the 32/64 bit embedded version (don't know about other variants), keyboard input does not work, even when clicking on the "do not send keystrokes to host" button in the top right corner of the plugin window.

Hosts tested: 
Mixbus 4.x
Ardour 5.x

VSTs tested:
Kontakt 5.x (both full version and player)
DMG
FabFilter
KORG
iZotope

OS: Ubuntu (KDE Neon) 64bit
WM: Plasma 5.x
Wine: both wine-staging and wine-development 2.x

**Comment by osxmidi** [comment]
I'll look into it and see what's happening.

**Comment by osxmidi** [comment]
Seems like key forwarding isn't implemented on Linux Ardour.

http://forum.renoise.com/index.php/topic/45432-linux-computer-keyboard-does-not-work-in-ardour/

https://github.com/Ardour/ardour/blob/master/gtk2_ardour/lxvst_plugin_ui.cc

void
LXVSTPluginUI::forward_key_event (GdkEventKey*)
{
	std::cerr << "LXVSTPluginUI : keypress forwarding to linuxVSTs unsupported" << std::endl;
}
