### ISSUE TITLE
No Sidechain input in Mixbus with Waves plugin

### ISSUE THREAD

**Issue by lentferj** [osxmidi/LinVst#71]
I was playing around with Waves inPhase plugin in Mixbus. Unfortunatley the Sidechain Input that's needed to make use of it does not appear in Mixbus' "Pinout" setup. I am not quite sure if this is a problem with LinVST/Mixbus or a Waves/Mixbus problem.
![bildschirmfoto vom 2019-03-01 10-21-23](https://user-images.githubusercontent.com/5664183/53628755-2801ee00-3c0c-11e9-8d2f-d9c04baf4e24.png)

**Comment by lentferj** [comment]
I checked with another plugin that depends on sidechain input. In this case the inputs appear..

![bildschirmfoto vom 2019-03-01 10-51-53](https://user-images.githubusercontent.com/5664183/53630343-24706600-3c10-11e9-8680-5fbe31a42623.png)

**Comment by osxmidi** [comment]
What happens with the InPhase stereo version?

**Comment by osxmidi** [comment]
I don't know much about the InPhase plugin.

I found this about the inputs/outputs https://forum.cockos.com/showthread.php?t=205445

**Comment by osxmidi** [comment]
I tried it out with Ardour.

https://drive.google.com/file/d/1F1atxdgGoW4AQ2h03s9uEYx_iDKKT7Ef/view?usp=sharing

https://drive.google.com/file/d/15-EQnZDuztT79ZP9jkOcR9q3f1D_RcUG/view?usp=sharing

https://www.youtube.com/watch?v=jsDdKwA29R0

**Comment by osxmidi** [comment]
InPhase is only reporting 1 input when the DAW asks for the plugins input count.

**Comment by lentferj** [comment]
I have asked around a bit and this really seems to be a Waves problem. Doesn‘t work with Mixbus on Windows either. Either because Waves only enables this for ‚officially supported‘ DAWs or because it‘s a VST3 feature with Waves plugins only. Thanks for checking anyway!

**Comment by osxmidi** [comment]
The VST3 version could be used with LinVst and DDMF btw.

I testes a Waves VST3  plugin using DDMF and it seemed to run pretty well.
