### ISSUE TITLE
xruns / bitwig / equator

### ISSUE THREAD

**Issue by patricksebastien** [osxmidi/LinVst#72]
Hi, to my surprise I was able to use Roli - Equator VST in bitwig linux! I'm running ubuntu-studio (low latency kernel everything really stable), but equator injects some xruns in jack. I was wondering if there's something I can do to avoid this. I found an article talking about realtime priority: https://wiki.winehq.org/Wine-Staging_Environment_Variables

Any ideas?

**Comment by osxmidi** [comment]
It can depend on various things, the kernel the hardware etc, usb based devices might be variable.

The rtirq script might help.

**Comment by patricksebastien** [comment]
**Kernel:**
Ubuntu Studio - Linux THEREMIN 4.15.0-45-lowlatency #48-Ubuntu SMP PREEMPT Tue Jan 29 17:45:27 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Hardware:**
Surface Pro 3 - x64 i7-4650u 3.3 Ghz - on performance

**USB soundcard:**
Edirol UA-25EX (does it makes a difference, like using Focusrite would help?)

**RTIRQ**
I have threadirqs configured in grub, and modified /etc/default/rtirq to remove "snd":
RTIRQ_NAME_LIST="usb i8042"

**TWEAKS**
I ran this script (https://github.com/raboof/realtimeconfigquickscan) and made the following change:
/etc/sysctl.conf (fs.inotify.max_user_watches = 524288)

Would be nice to include some free VST (synth, fx) in your repo, so that we can easily test.

**Comment by osxmidi** [comment]
Some other things might be to look at pulseaudio and running services.

There is some overhead from Wine and sometimes even the vst's display can affect latency seeing that the vst's display depends on Wine and so does the audio processing, so even things like Linux video drivers and video hardware might possibly have an effect.

**Comment by patricksebastien** [comment]
So yes, I now understand that everything is interconnected. From my conclusion (will close this thread, it's very specific), equator vst -> bitwig -> jack very difficult for low latency, but equator in carla (using LinVst afaik) works if not pushing too much on the hardware (cpu) / software (like running bitwig, pure data etc). Thanks for LinVst!
