### ISSUE TITLE
Crashes when saving lxvst presets

### ISSUE THREAD

**Issue by myrocketship** [osxmidi/LinVst#73]
I have been finding that versions beginning 20180917 cause immediate crashes in Ardour-5.12 when trying to save an lxvst preset both new or overwriting. Ardour just disappears, segfault-like.
It can work very occaisionally (1% of the time). Kontakt is a definite problem.

Using embed-6432.
Wine versions make no difference.
Festige or VST headers make no difference.
32bit or 64bit plugins make no difference.
Compiler options make no difference.
Ubuntu 16.04 & 18.04.
Versions prior to 20180917 work just fine.

I have no idea how to debug this further.

**Comment by osxmidi** [comment]
You mean LinVst version 2.32 ? (if you start Ardour from the terminal then when a LinVst vst is loaded it will display the LinVst version in the terminal).

I've been through the 2018 09 17 changes and I can't see anything I changed about the presets.

I also tried saving a session with a LinVst vst in Ardour (Ardour/MXLinux/Wine-Staging 4.3) and everything seemed ok.
