### ISSUE TITLE
Keyboard input not recognized on Wayland

### ISSUE THREAD

**Issue by Sangeppato** [osxmidi/LinVst#74]
I don't know if it's possible to fix this, but anyway I'll report it:
Running a Gnome session on Wayland, any VST running through LinVst won't accept the keyboard input, so it's impossible to type anything (for example to save some presets). Running stand-alone programs through wine on wayland works just fine though. I know Wine is quite tied to X, so I'm not sure this is a LinVst issue

**Comment by lentferj** [comment]
Which DAW are you using? In Ardour and Mixbus there is a small ‚catch the keyboard‘  icon in every plugin window.

**Comment by Sangeppato** [comment]
I'm running Reaper, I don't see anything like that.. Does it work for plugins through Wine on Wayland?

**Comment by lentferj** [comment]
Not sure, it works for LinVST plugins in Ardour on X11, that don’t work without this enabled. Depends on the plugins, though.

**Comment by Sangeppato** [comment]
Well, the point of this bug is that it's not working under Wayland, using X11 everything is nice and cool here as well

**Comment by osxmidi** [comment]
It might be a window manager focus problem of some sort.
