### ISSUE TITLE
Freeze while scanning VSTs in Reaper

### ISSUE THREAD

**Issue by kmkrebs** [osxmidi/LinVst#75]
LinVst has been working beautifully for me for months, but I've begun experiencing a freeze-up when I start Reaper and it scans VSTs.  It only started in the last day or two.
I'm running the latest version of LinVst, compiled from the git repo on Antergos Linux, with Wine 4.5.

```$ reaper
DSSI VST plugin server v0.986
Copyright (c) 2012-2013 Filipe Coelho
Copyright (c) 2010-2011 Kristian Amlie
Copyright (c) 2004-2006 Chris Cannam
LinVst version 2.43
Loading  /home/kmkrebs/.wine/drive_c/vst/sysnths/Alpha3/Alpha.dll
dssi-vst-server[1]: exiting
```
At that point Reaper stops loading and hangs there.

**Comment by osxmidi** [comment]
I've been making some changes for version 2.5 and maybe you made LinVst with something not quite finished by me at the time.

Try it with what's on github now, which is pretty close to what will be version 2.5.

**Comment by kmkrebs** [comment]
Unfortunately the problem continues.  I re-cloned the repo to make sure I had the latest changes, and also made sure to delete and re-copy the *.so files for my VSTs.
Is there anything you suggest I try to get more information on the source of the problem?

**Comment by osxmidi** [comment]
You could try using the 2.43 binary and see if that runs ok.

If it doesn't run ok, then there might be a Wine problem of some kind.

**Comment by kmkrebs** [comment]
The good news -- I downloaded the 2.43 source, compiled that, and everything worked perfectly. 

The bad news -- I tried your second recommendation and commented out line 1048 in linvst.cpp from the current git repo.  After compiling and updating all the .so files, I get the same freezing behaviour.

**Comment by osxmidi** [comment]
I've made some more changes to the code.

If you want to try it out and get back to me then that would be helpful.

**Comment by kmkrebs** [comment]
Sadly no luck with the latest changes.

**Comment by kmkrebs** [comment]
Good news -- the latest git build works!

**Comment by osxmidi** [comment]
Thanks for the feedback.
