### ISSUE TITLE
futex wait

### ISSUE THREAD

**Issue by KottV** [osxmidi/LinVst#76]
Hi,

version ddc8f1ea05fd02dd4de9571cc8212008c95cebef and some previous, (works fine on 5f0ca853ae4b06235d2ac4b6099fc61b86a7677b)
when closing plugin window, process is waiting for thread finish, (I guess):

futex(0x7fd73f0b69d0, FUTEX_WAIT, 1804, NULL

strace 1804 gives a endless loop of:

nanosleep({tv_sec=0, tv_nsec=1000000}, NULL) = 0

(openSUSE TW, kernel 5.0.6, glibc 2.29)

**Comment by osxmidi** [comment]
Thanks for letting me know.

I've been trying a different way to destroy the wine vst window and it might have some problems.

If -DXECLOSE is removed from the Makefiles then it goes back to the old way.

If that fixes the problem then try to let me know if you can, as then I will know that the new destroy wine window has some compatibility problems with some distros.

**Comment by KottV** [comment]
yes, without -DXECLOSE plugin's window closes normally

**Comment by osxmidi** [comment]
Thanks for the feedback.

I've removed -DXECLOSE from the makefiles.

**Comment by osxmidi** [comment]
I've changed some of the thread code and it seems to be ok on my system but maybe not others.

**Comment by KottV** [comment]
I've tested now, works as should
Thank You!
