### ISSUE TITLE
Script to centrally manage bridged VSTs

### ISSUE THREAD

**Issue by Goli4thus** [osxmidi/LinVst#77]
Hi osxmidi,

I've made a python script to centrally manage bridged VSTs (console UI, minimal dependencies):

https://github.com/Goli4thus/linvstmanage

I'm open for feedback.

**Comment by osxmidi** [comment]
Looks good to me.

I'll include a link in the readme or include it here if you like.

**Comment by Goli4thus** [comment]
Nice to hear!
From a user perspective it probably would be best if it came packaged with LinVst itself. 
So I'm all for including it.

But an additional short mention in the Readme wouldn't hurt either to allow people, who delay upgrading until the next official LinVst release, to discover it.

Shall we put it into a sub folder within 'convert' (i.e. convert/manage)? A 'manage' folder at top level?
Or something else?

**Comment by osxmidi** [comment]
Yes, a manage folder sounds good.

**Comment by Goli4thus** [comment]
I've created a pull request. Therefore closing this issue.

**Comment by keybreak** [comment]
@Goli4thus 
That's outstanding idea, exactly what i was searching for!

So if i get you right, now with your script we can just list all needed plugins in .ini file and then hit update when needed to mass-update all LinVst **.so**'s?
