### ISSUE TITLE
LinVst 2.5 disables keyboard input for plugins in Mixbus5

### ISSUE THREAD

**Issue by AegisPrime** [osxmidi/LinVst#83]
2.4.3 works as expected, when you click on a field using 2.5 and try to enter a number, you can't.

Tested with Mixbus 5.2.191 and TDR SlickEQ GE (and other plugins).

**Comment by osxmidi** [comment]
Keyboard input seems to be ok with Reaper and Ardour5 for LinVst 2.5.

I don't think I changed any of the keyboard code but I'll try to look into it.

**Comment by AegisPrime** [comment]
Just to add to the mystery, I've noticed that hitting the little keyboard icon (in the top right on Mixbus plugin windows) allows entry in the fields but, in 2.4.3 this step wasn't necessary. Thanks for looking into it - LinVst is excellent! Aegis.
