### ISSUE TITLE
Experimental Mac version?

### ISSUE THREAD

**Issue by citrusui** [osxmidi/LinVst#84]
I found a [forum link online](https://forum.cockos.com/showthread.php?t=191243) that had information on an experimental port of LinVst to Mac. However, it seems that link (to the releases page) no longer shows a download for Mac. Are there any plans to bring back Mac support?

**Comment by osxmidi** [comment]
Yes I did have a Mac version early on but it didn't seem to get much interest.

I might bring it back at some point, but not at the moment.

**Comment by dmnsgn** [comment]
@osxmidi Is the mac version still around and functional by any chance? I'd be interested try and convert a windows/linux vst to mac.
