### ISSUE TITLE
Using LinVST in Arch Linux

### ISSUE THREAD

**Issue by Fourstepper** [osxmidi/LinVst#87]
I use Manjaro. 

I downloaded the LinVST package from the AUR repository using yay AUR helper, but I cannot figure out where to find the files that I need for the conversions. 

Sorry, a little noobish, I know.

Thanks for pointing me the right way!

**Comment by osxmidi** [comment]
Download the LinVst binary from https://github.com/osxmidi/LinVst/releases

In the convert folder there is linvstconvert and linvstconverttree (linvstconverttree can also convert sub directories).

Start linvstconvert (or linvstconverttree) and then select the linvst.so file and then select the folder that contains the vst dll files and hit convert and then it's just a case of pointing the DAW to search the vst dll path.

Also copy all of the lin-vst-serverxxxx files to /usr/bin.

The linvstconvert (linvstconverttree) binaries should run on Manjaro ok.

**Comment by Fourstepper** [comment]
Thank you!
