### ISSUE TITLE
Using LinVST in Slackware based Porteus with REAPER

### ISSUE THREAD

**Issue by s3n3wen** [osxmidi/LinVst#88]
My setup steps:

1) Converted a windows vst (GuitarGadgets64.dll from Musical Entropy) using linvstconvert from LinVst-2.53-Debian-Stretch.zip package 

2) Copied the server files from he embedded folder to /usr/bin 

3) From REAPER DAW I tried to re-scan VST but the following message appears >> 

"lin-vst-server/vst not found or LinVst version mismatch"

I'm using wine-3.5

I tried to run lin-vst-serverst.exe directly with wine (maybe I shouldn't) and it gives me "BAD EXE format" message.

What could be the cause? I'm a newbie, I'm wondering if you can help me with this..

Thank you..

**Comment by osxmidi** [comment]
Probably a mix up of some sort.

I've been making a few changes recently, so I'd suggest downloading it again and reinstalling.

It's probably a good idea to delete the previous lin-vst-server files 
sudo rm /usr/bin/lin-vst*

Then copy the lin-vst-serverxxxxxx files to /usr/bin from the embedded folder 
"sudo cp lin-vst* /usr/bin"

Then using linvstconvert (or linvstconverttree for sub directories) choose linvst.so and then choose the vst dll folder and hit convert and then point the DAW to scan the vst dll folder.
