### ISSUE TITLE
Don’t delete tags and releases

### ISSUE THREAD

**Issue by Jacalz** [osxmidi/LinVst#89]
It looks like tags and releases here on GitHub are removed after a new version is published. This is a really terrible thing to do as it makes it harder to look back in time for what has changed between releases and it makes it hard for rebuilds if a distribution wants to package it and need to hold back an update.

If this really is the case, please doing so and I will see to try to get this packaged for the Solus distribution :)

**Comment by osxmidi** [comment]
ok.
I'll leave the previous versions.

**Comment by Jacalz** [comment]
Thank you very much for that! I will be sure to package you wonderful software for the Solus repo :)
