### ISSUE TITLE
LinVST error message box too small

### ISSUE THREAD

**Issue by AnClark** [osxmidi/LinVst#92]
When LinVST encounts errors while DAW is loading VST plugins, it's always hard for me to find out the error dialog of LinVST. The dialog is **just a tiny tiny window with extremely small fonts**.

Hope that this would be improved in the next release.

**Comment by osxmidi** [comment]
I could improve it and I'll keep it in mind for future versions.

**Comment by AnClark** [comment]
OK!
By the way, I'm really great to have LinVST with REAPER configured on my Debian, so I can continue to produce music on Linux! Thanks for your brilliant work!
