### ISSUE TITLE
LinVST produces .so without vendor

### ISSUE THREAD

**Issue by keybreak** [osxmidi/LinVst#93]
LinVST always produce Unknown Vendor, which is bad for what we have in mind [here](https://github.com/Goli4thus/linvstmanage/issues/1) for the future
Tested with some free VST plugins in Renoise.

Windows:
![image](https://user-images.githubusercontent.com/47599989/62769683-23d2da00-baa2-11e9-9cb0-036bf260fcfe.png)

Linux:
![image](https://user-images.githubusercontent.com/47599989/62769708-33522300-baa2-11e9-9107-f2dcf2dc73b6.png)

```
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.2.4-1-MANJARO
Shell: bash 5.0.7
DE: Deepin 15.11
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
```
_____

P.S. Airwave have same results as Windows, probably you should check their code for cure :smile_cat:

**Comment by osxmidi** [comment]
Seems to be a Renoise thing.

If I print out the vendor (the vendorlin line below) then it's there but apparently Renoise doesn't pick it up for some reason.


LinVst version 2.54
Loading  /home/osxuser/vst/TAL-Reverb-4.dll
vendorlin TAL-Togu Audio Line
Renoise LOG> VstPlugs: Analyzing VST plugin 'Unknown Vendor: TAL-Reverb-4', Unique ID:1919243828, Version:2400

**Comment by keybreak** [comment]
hmm...That's weird!

I'm not familiar on code details, but maybe Renoise use some other variable to determine vendor?
What if you parse & compare resulted .so metadata of LinVST with Airwave?

There should be something

**Comment by osxmidi** [comment]
I'll have to look into what Renoise is doing because it's doing something different to the other daws.

Airwave doesn't do much differently to LinVst for the vendor name, except that Airwave doesn't have a string copy max length but LinVst does and from what I can make out at the moment it seems Renoise might have trouble with the max length.

**Comment by osxmidi** [comment]
I think I've found out what is going wrong and I've updated the source code.

Renoise seems to have a cache, so to get the changes happening the cache needs to be deleted which I did by doing the below in the /home/user folder

sudo rm -R Renoise
sudo rm -R .renoise

**Comment by keybreak** [comment]
> I think I've found out what is going wrong and I've updated the source code.

Thx!
I'll try that out :)

P.S. Careful to recommend just rm, there are also settings in there...
vst cache is stored specifically here:
~/.renoise/V3.1.1/CachedVSTs_x64.db
~/.renoise/V3.1.1/CachedFailedVSTs_x64.db

But i've tested on clean, and cleaned cache before double-check, but it's still unknown vendor for any LinVST plugin.

**Comment by keybreak** [comment]
Yes, i approve new build fixed the issue, thank you very much again :+1: 

_______

btw, what's the best goto place for list of LinVST compatibility this days?
Or should i create new?

I'm about to test all of my ~2500 Windows plugins with LinVST, that might be huge testing / fixing help for you, so i'd like to make sure i haven't missed best place to list results :smile:

**Comment by osxmidi** [comment]
That's a lot of testing.

You could upload the list here and I'll host it or you could let me know of a link to it and I'll post the link here.

**Comment by keybreak** [comment]
Right, cool!
In case of bugs / problems i can start to post it here in issues as well?

> That's a lot of testing.

Yep, but i'm very interested in making Linux better and since i'm not coder that could be most valuable investment of time :smile_cat:

**Comment by osxmidi** [comment]
Yes, you can post in the issues but I would guess that a fair few problems will be with Wine and the d2d1.dll that is only half implemented in Wine and also other Wine problems.

If Wine had a functioning d2d1 then a lot of the more modern plugins would start working ok.

**Comment by keybreak** [comment]
Yeah...Ain't winetricks fully solves d2d1 with replacement though?

**Comment by osxmidi** [comment]
I don't know about how a d2d1 override would go, as it might vary from system to system.

This page has some dll override options https://blog.inagaki.in/en/linux-waves-plugins-en/
