### ISSUE TITLE
Plugin window opens with no UI & closes a second later (Bitwig 3)

### ISSUE THREAD

**Issue by shagia** [osxmidi/LinVst#94]
Regarding the Roland JV-1080 plugin, this may just be a compatibility issue and Wine might not support the methods it uses to draw, but the plugin cannot launch it's GUI. It plays audio, you can play the initial preset just fine, playing with the public plugin parameters also works just fine, but attempting to open the window does nothing, besides closing it's own window a second later.

Are there any notes for the Roland Cloud collection's compatibility and what libraries they use? Testing if the d2d1 library was playing with it came with no luck.

```
Distro: Ubuntu 19.04
Kernel:  5.0.0-15-generic 
LinVST 2.6
Wine-4.13 (Staging)
```

**Comment by osxmidi** [comment]
Could you test loading the plugin and opening it's gui using Reaper from a terminal.

When Reaper is started from a terminal window, Wine outputs what's going on when the plugin is loading.

If you can copy the terminal output and post it here then I might be able to see what is going on.

**Comment by shagia** [comment]
```Loading  /home/shagia/.wine/drive_c/Program Files (x86)/Steinberg/VSTPlugins/Roland VS/JV-1080.dll
00d3:fixme:ver:GetCurrentPackageId (0x40dfd80 (nil)): stub
SetupMidiTask```

Opening the plugin: 
```(reaper:40309): Gdk-WARNING **: 00:47:06.325: gdk_window_set_user_time called on non-toplevel```

In Reaper, instead of just straight closing, it instead starts as a blank decently sized window.

**Comment by osxmidi** [comment]
It might be a d2d1 problem.

Maybe disable d2d1 in the winecfg Libraries tab.

I can't test the plugin because there is no demo.

**Comment by shagia** [comment]
Sorry for a late response, unfortunately no dice on disabling d2d1 or testing some other DX related libraries.

If you're up for it and it's not too much of a hoop to test, there's a 30 day Roland Cloud trial you can try. Client works fine as long as you have wininet set to builtin, client downloads dll's that are convertible. I'm trying other plugins from the collection and the Sound Canvas works fine..
![DSK_19 08 13_00 04 35](https://user-images.githubusercontent.com/13505837/62921561-f5812300-bd5d-11e9-952f-402ca9bdc672.png)

Otherwise, no stress. I might wanna buy a physical JV anyway :smile:
