### ISSUE TITLE
[VST] arcDev Noise Industries DubbBox 2 v2.0

### ISSUE THREAD

**Issue by keybreak** [osxmidi/LinVst#97]
## Description

1. Use automation on any parameter
2. Now each time you close GUI of plugin it will produce "TRRRR" and a lot of xruns (about 200)

Here's plugin (free. just hard to find this days) and test-project with automation demo.
[test.tar.gz](https://github.com/osxmidi/LinVst/files/3522095/test.tar.gz)

Such thing doesn't happen with same .dll on Windows, was unable to test with airwave since it doesn't produce GUI at all :laughing: 

## Dependencies

**strings "arcDev.Dubb.Box.RC1.dll" | grep -i '.dll'**
```
KERNEL32.DLL
ADVAPI32.dll
COMCTL32.dll
comdlg32.dll
GDI32.dll
ole32.dll
OLEAUT32.dll
SHELL32.dll
SHLWAPI.dll
USER32.dll
WINMM.dll
se_vst.dll
```

## Enviroments

```
 OS: Manjaro 18.0.4 Illyria
 Kernel: x86_64 Linux 5.2.4-1-MANJARO
 Shell: bash 5.0.7
 DE: Deepin 15.11
 WM: Deepin WM
 dm: LightDM 
 gcc v: 9.1.0 
 tk: Qt 5.13.0 
 driver: nvidia v: 430.26 
 WINE: 4.13-staging amd64
```

## Winetricks
```
gdiplus
andale
arial
comicsans
courier
georgia
impact
times
trebuchet
verdana
webdings
corefonts
tahoma
wininet
fontsmooth=rgb
win7
```

**Comment by osxmidi** [comment]
Seems like a Wine display/dll problem with that plugin as other plugins are ok.

**Comment by keybreak** [comment]
Yeah, looks like so...
I've also found out that same thing happens with `arcDev Noise Industries ET-200 v1.0`, but not the other ones from same vendor, weirdly enough those 2 of same plugins different version are ok:
`arcDev Noise Industries DubbBox v1.0`
`arcDev Noise Industries | ET-301 v1.5`

Nothing we can do on LinVST / Wine level with those differences?
