### ISSUE TITLE
[VST] Boomplug BoomComb v1.1

### ISSUE THREAD

**Issue by keybreak** [osxmidi/LinVst#99]
## Description

- No GUI on nvidia proprietary drivers
- There is GUI on VirtualBox VM, but it's xtremely laggy GUI on both plugin & DAW when opened - which eventually will lead to crash very soon

No expert here, but looks like d2d1.dll?

Here's .dll 
[BoomComb.tar.gz](https://github.com/osxmidi/LinVst/files/3525795/BoomComb.tar.gz)

## Dependencies

**strings "BoomCombVST.dll" | grep -i '.dll'**
```
USER32.dll
d2d1.dll
DWrite.dll
KERNEL32.dll
ole32.dll
BoomCombVST.dll
```

## Enviroments

```
 OS: Manjaro 18.0.4 Illyria
 Kernel: x86_64 Linux 5.2.4-1-MANJARO
 Shell: bash 5.0.7
 DE: Deepin 15.11
 WM: Deepin WM
 dm: LightDM 
 gcc v: 9.1.0 
 tk: Qt 5.13.0 
 driver: nvidia v: 430.26 
 WINE: 4.13-staging amd64
```

## Winetricks
```
gdiplus
andale
arial
comicsans
courier
georgia
impact
times
trebuchet
verdana
webdings
corefonts
tahoma
wininet
fontsmooth=rgb
win7
```

**Comment by lentferj** [comment]
Did you try disabling d2d1?

**Comment by keybreak** [comment]
Tried on real machine with nvidia, by adding **d2d1 (disable)** override, if that's correct?
Still no GUI, although on this machine plugin itself is working fine with or without override through DAW default controls.
